:awestruct-layout: solution-adoption
:awestruct-interpolate: true

=== Developing for Containers

==== Start developing with containers now
Whatever Docker container application you create, it will be deployable on OpenShift Enterprise V3, Red Hat Enterprise Linux, Red Hat Enterprise Linux Atomic Host, and Red Hat Atomic Enterprise Platform. We recommend development using the Red Hat Container Development Kit on OpenShift Enterprise V3 or Red Hat Enterprise Linux, and then verifying your app on Atomic Host.

==== The Red Hat Container Development Kit (CDK)
Red Hat Container Development Kit (CDK) simplifies the setup of your development environment for creating Red Hat Docker container applications from Red Hat and non-Red Hat platforms including RHEL, Microsoft Windows, Mac, Fedora, and other Linux development platforms. The CDK includes some important new features such as Atomic App (based on the Nulecule spec) for configuring your multi-container applications and V2C to help you migrate your VM-based code to Docker containers. So whether you’re migrating an existing application to Docker containers, or stepping into microservices, the CDK is the place to start.

Learn more about the link:#{site.base_url}/products/cdk[Red Hat Container Development Kit (CDK)].

==== Development tools in Docker image format
Once you’ve set up your environment with the CDK, you can utilize a number of trusted and supported developer tools, instructional resources, and an ecosystem of experts to help you maximize productivity in building great Linux applications. Here are some of the tools:

Red Hat Software Collections (RHSCL) and Red Hat JBoss middleware provides a range of programming languages, databases, web servers, enterprise platform, etc. in Docker image format to accelerate your container development on RHEL 6 and 7, and/or OpenShift. link:#{site.base_url}/products/cdk/download/#DockerImages[Docker images] of Red Hat Software Collections (RHSCL) and Red Hat JBoss Middleware supply Java, Python, Node.js, MongoDB, PostgreSQL, JBoss EAP, GCC, Eclipse, etc. help you rapidly build and deploy containerized applications on Red Hat Enterprise Linux 6 and 7, and/or OpenShift.
