= Containers
:awestruct-layout: solution-detail


== Header
Containers

You'll also find how Red Hat's own culture and processes have been automated while on our DevOps journey. The approach is focused on making it easy to develop, test, deploy, integrate, scale and manage applications. We'll also be sharing insights on culture changes as Red Hat continues on its own DevOps journey.


== Left Section
=== Culture
At its core, DevOps is about culture. DevOps aims at improving communication, collaboration and transparency between developers, operations and their clients.

link:/devops/adoption/#__a_id_culture_a_culture[Learn more on culture...]


== Middle Section
=== Automation
Learn how treating infrastructure as code and continuous delivery can help you deliver software to production on demand.

link:/devops/adoption/#__a_id_automation_a_automation[Learn more on automation ...]


== Right Section
=== Tools
Discover everything from developer tooling, source control, and build tools to help create your application.

link:/devops/adoption/#__a_id_tools_a_tools_and_infrastructure[Learn more on tools...]
