source 'http://rubygems.org'
gem 'blinkr', git: 'http://github.com/RubyGemTSL/blinkr', branch: 'blinkr_1.0.0_beta'
gem 'builder', '~> 3.2', '>= 3.2.3'
#gem 'blinkr', :path => '/Users/ian/Documents/workspace/blinkr'