<?php

/**
 * @file
 * Compass module compiles Sass stylesheets for themes.
 *
 * The shell execution functions were taken from ImageAPI module ImageMagick
 * toolkit
 */

/**
 * Implements hook_help().
 */
function compass_help($path, $arg) {
  switch ($path) {
    case 'admin/help#compass':
      $output = '<p>' . t('Compass module supports the !compass_link framework tool in your Drupal theme development workflow. Compass stylesheets are optionally compiled at cron runs or on demand. You must configure your theme\'s info file for the module to work.', array('!compass_link' => l('Compass', 'http://wiki.github.com/chriseppstein/compass'))) . '</p>';
      $output .= '<h2>' . t('Configuration') . '</h2>';
      $output .= '<p>' . t('Add this line to your theme\'s .info file') . '</p>';
      $output .= '<pre><code>compass[status] = 1</code></pre>';
      $output .= '<p>' . t('Other command line options can be specified using their long argument names with underscores ( %underscore ) instead of hyphens ( %hyphen ).', array('%underscore' => '_', '%hyphen' => '-')) . '</p>';
      $output .= '<pre><code>compass[sass_dir] = "src"</code></pre>';
      $output .= '<p>' . t('If you have used compass to create your theme stylesheets, you can rely on the config.rb in the theme\'s directory') . '</p>';
      return $output;
    default:
      break;
  }
}

/**
 * Implements hook_menu().
 */
function compass_menu() {
  $items = array();
  if (module_exists('devel')) {
    $items['devel/compass'] = array(
      'title' => 'Run Compass',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('compass_process'),
      'access arguments' => array('access devel information'),
      'menu_name' => 'devel',
      'file' => 'compass.pages.inc',
    );
  }
  $items['admin/config/compass'] = array(
    'title' => 'Compass',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('compass_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'compass.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_menu_link_alter().
 *
 * Flag this link as needing alter at display time.
 * This is more robust than setting alter in hook_menu().
 * See devel_translated_menu_link_alter().
 *
 */
function compass_menu_link_alter(&$item, $menu) {
  if ($item['link_path'] == 'devel/compass') {
    $item['options']['alter'] = TRUE;
  }
}

/**
 * Implements hook_translated_menu_item_alter().
 *
 * Append dynamic querystring 'destination' to several of our own menu items.
 *
 */
function compass_translated_menu_link_alter(&$item) {
  if ($item['href'] == 'devel/compass') {
    $item['localized_options']['query'] = drupal_get_destination();
  }
}

/**
 * Implements hook_cron().
 */
function compass_cron_queue_info() {
  $queues['compass_themes'] = array(
    'worker callback' => 'compass_compile',
    'time' => 15,
  );
  return $queues;
}

/**
 * Implements hook_cron().
 */
function compass_cron() {
  if (variable_get('compass_cron', TRUE)) {
    $queue = DrupalQueue::get('compass_themes');
    $themes = list_themes();
    if (lock_acquire('compass', 240.0)) {
      foreach ($themes as $theme) {
        if ($theme->status && isset($theme->info['compass']['status'])) {
          $queue->createItem($theme);
        }
      }
    }
  }
}

/**
 * Drupal queue worker callback.
 *
 * Compiles a compass enabled theme's stylesheets.
 */
function compass_compile($theme) {
  module_load_include('inc', 'compass');
  $cmd = _compass_update($theme->name);
  _compass_exec($cmd, $output, $errors);
  drupal_clear_css_cache();
  watchdog('compass', 'Compass run on %theme', array('%theme' => $theme->info['name']));
}

/**
 * Implements hook_theme_registry_alter().
 *
 * Devel module optionally resets the theme registry on each page request. Every
 * theme's cached registry is cleared, but only the active theme is rebuilt
 * for any given page request, so the key in the global $theme variable is
 * sufficient to check.
 */
function compass_theme_registry_alter(&$theme_registry) {
  global $theme;
  if (variable_get('devel_rebuild_theme_registry', FALSE) && variable_get('compass_devel_rebuild', FALSE)) {
    $themes = list_themes();
    module_load_include('inc', 'compass');
    if (isset($themes[$theme]->info['compass']['status'])) {
      $cmd = _compass_update($themes[$theme]->name);
      _compass_exec($cmd, $output, $errors);
      drupal_clear_css_cache();
    }
  }
}
