:awestruct-layout: product-docs-and-apis

== More Resources

http://www.redhat.com/about/events-webinars/webinars/20140529-how-to-achieve-real-time-performance-while-securing-your-application-data[How to achieve real-time performance while securing your application data]::
  In-memory data grids provide applications with fast data access and elastic scalability. And for many transaction-heavy applications, that's enough. But for transaction-heavy applications that manage confidential or private data, you need...

http://www.redhat.com/about/events-webinars/webinars/nosql-no-sweat-with-jboss-data-grid[NoSQL: No sweat with JBoss Data Grid]::
  Join us for a webinar to learn how web applications can achieve true big data scale with Red Hat(R) JBoss(R) Data Grid. Tristan Tarrant and Shane Johnson will demonstrate the best approach for developers who want to easily get up and running with JBoss Data Grid.

http://www.redhat.com/about/events-webinars/webinars/2013-03-06-boost-performance-rh-jboss-data-grid-intel[Is your big data solution a big drag?  Boost performance with Red Hat JBoss Data Grid and Intel]::
  While there are a number of platforms to address big data, they are often constrained by the I/O performance of the host file system. This can be a show-stopper for applications that require extreme performance and real-time access to data.

== Red Hat JBoss Supported Configurations

https://access.redhat.com/articles/2435931[Red Hat JBoss Data Grid Supported Configurations] +
https://access.redhat.com/site/articles/488833[Red Hat JBoss Data Grid Component Details]

