:awestruct-layout: product-get-started-old
:awestruct-interpolate: true

== Extra section

=== Install Java

1. Install the Java SE Development Kit (JDK), we recommend OpenJDK 1.8 or Oracle JDK 1.8.
a. For Windows and Mac: Red Hat Developers typically downloads from Oracle’s link: http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html[site].  (Make sure you get the Java *Development* Kit and not just the Java Runtime Environment).
b. For Red Hat Enterprise Linux: Install OpenJDK by executing the following command:
+
`yum install java-1.8.0-openjdk-devel`
+

=== Install and Configure JBoss Data Grid 7

1. *Download:*  Download the latest version of Red Hat JBoss Data Grid.  The latest version at the time of writing is link: https://www.jboss.org/download-manager/file/jboss-datagrid-7.0.0-server.zip[Red Hat JBoss Data Grid 7.0.0 Server]
+
TIP: Make sure you have a JDK of your choice installed. We recommend OpenJDK 1.8 or Oracle JDK 1.8. If you haven’t yet, see the Install Java section.
+
2. *Unzip:*  Unzip JBoss Data Grid into your preferred destination folder; we will refer to this location as `$JDG_HOME`.
a. In Windows or Mac, you can extract the contents of the ZIP archive by double clicking on the ZIP file.
b. In Red Hat Enterprise Linux, open a terminal window in the target machine and navigate to where the ZIP file was downloaded. Extract the ZIP file by executing the following command: `unzip jboss-datagrid-7.0.0-server.zip`

=== Install Red Hat JBoss Enterprise Application Platform 7

1. Download: http://www.jboss.org/download-manager/file/jboss-eap-7.0.0.zip
2. Extract JBoss EAP into your preferred destination folder; we will refer to this location as `$JBOSS_HOME`.
a. In Windows or Mac, you can extract the contents of the ZIP archive by double clicking on the ZIP file.
b. In Red Hat Enterprise Linux, open a terminal window in the target machine and navigate to where the ZIP file was downloaded. Extract the ZIP file by executing the following command: `unzip jboss-eap-7.0.0.zip`

=== Install and Configure Maven

1. Download from: http://maven.apache.org/download.cgi (The latest at the time of this writing is 3.3.9). Choose the ZIP distribution.
2. Unzip into the folder of your choice as we’ve done above for JBoss Data Grid; we’ll refer to this location as `$MAVEN_HOME`.
+
NOTE: You may want to add `$MAVEN_HOME/bin` to your system `$PATH` in order to access its executable directly from the command-line, no matter your current working directory.
+
3. Test that your Maven and Java installations are working correctly by executing `$MAVEN_HOME/bin/mvn --version`.  For instance:
+
[.code-block]
```
$ mvn --version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: /home/alr/opt/apache/maven/apache-maven-3.3.9
Java version: 1.8.0_92, vendor: Oracle Corporation
Java home: /home/alr/opt/oracle/java/jdk1.8.0_92/jre
Default locale: en_US, platform encoding: UTF-8
```

=== Download and Run the Quickstart

1. In one terminal window, start an instance of JBoss EAP by executing `$JBOSS_HOME/bin/standalone.sh` (Linux and Mac) or `%JBOSS_HOME%\bin\standalone.bat` (Windows)
2. In a second window, start another instance of JBoss EAP by passing the system property `jboss.socket.binding.port-offset` to the standalone script, ie:
+
[.code-block]
```
$JBOSS_HOME/bin/standalone.sh -Djboss.socket.binding.port-offset=100
```
+
3. In a third terminal window, download the quickstart:
+
https://www.jboss.org/download-manager/file/jboss-data/jboss-datagrid-7.0.0-quickstarts.zip
4. Extract the quickstarts ZIP as we’ve done before, or using unzip
+
`jboss-datagrid-7.0.0-quickstarts.zip`.
5. Move into the quickstart directory as it’s just been extracted: `helloworld-jdg`
6. Build the quickstart web application and deploy it into the first instance of JBoss EAP by executing:
+
`mvn clean package wildfly:deploy -s ../settings.xml`
7. Deploy the quickstart web application into the second instance of JBoss EAP by executing:
+
`mvn wildfly:deploy -s ../settings.xml -Dwildfly.port=10090`

=== Access the application

The application will be running at the following URLs: +
http://localhost:8080/jboss-helloworld-jdg (first server instance) +
http://localhost:8180/jboss-helloworld-jdg (second server instance)

You can test replication of entries in the following way:

1. Access first server at http://localhost:8080/jboss-helloworld-jdg and insert key "foo" with value "bar"
2. Access second server at http://localhost:8180/jboss-helloworld-jdg and do the following:
** Click on "Get Some"
** Get the value for key "foo"
** Click "Put Some More"
** Insert key "mykey" with value "myvalue"
3. Access the first server at http://localhost:8080/jboss-helloworld-jdg and do the following:
** Click on "Get Some"
** Get all mappings by clicking on "Get All"
4. All data entered on each server was replicated to the other server
+
NOTE: Entries expire and simply disappear after 60 seconds from last update.
To access predefined servlets and directly store/retrieve a key in the cache, access the following URLs: http://localhost:8080/jboss-helloworld-jdg/TestServletPut http://localhost:8180/jboss-helloworld-jdg/TestServletGet (note the different port 8180)

=== Undeploy the Archive

1. Make sure you have started JBoss EAP as described above.
2. Open a command line and navigate to the root directory of this quickstart.
3. When you are finished testing, type this command to undeploy the archive from both running servers:
+
[.code-block]
```
mvn wildfly:undeploy -s ../settings.xml
mvn wildfly:undeploy -s ../settings.xml -Dwildfly.port=10090
```
