:awestruct-layout: product-overview
:leveloffset: 1

== Overview

Data grids are in-memory distributed databases designed for scalability and fast access to large volumes of data.  More than just a distributed caching solution, data grids also offer additional functionality such as map/reduce, querying, processing for streaming data, and transaction capabilities.


== Features1

=== Supercharge your applications

Offers in-memory access to data and elastic scalability for large volumes of transactional data.

== Icon1

[.fa .fa-tasks .fa-5x .fa-fw]#&nbsp;# 

== Features2

=== API access to data

Applications written in any language, using any framework can easily access and share data in the grid via multiple APIs.

== Icon2

[.fa .fa-puzzle-piece .fa-5x .fa-fw]#&nbsp;#

== Features3

=== Unlock from traditional databases

Flexible solution for diverse IT environments. Create a data abstraction layer to decouple your application, your data and your traditional database to provide independent maintenance and scaling.

== Icon3

[.fa .fa-cloud .fa-5x .fa-fw]#&nbsp;# 

== Detail

Red Hat JBoss Data Grid supercharges today's modern applications and allows developers to meet tough requirements of high performance, availability, reliability, and elastic scale. JBoss Data Grid is compatible with the existing data tier as well as applications written in any language, using any framework and any platform via multiple APIs such as memcached, HotRod, and REST. Developers obtain a streamlined approach to standing up new applications, avoiding the challenges normally associated with integrating applications and traditional databases. A subscription includes management tooling (via the JBoss Operations Network plug-in), unlimited access for remote clients, and advanced functionality making JBoss Data Grid an ideal solution for cost-effectively supercharging today's modern applications.  

== Resources

- Try our http://www.jboss.org/jdf/quickstarts/jboss-as-quickstart/jdg-quickstarts/carmart/[CarMart quickstart] 

== Articles

http://howtojboss.com/2013/09/25/job-opening-middleware-data-specialist/[Job Opening: Middleware Data Specialist]::
  Red Hat is looking for a middleware specialist in distributed data and data virtualization / federation to join the sales team. To be more specific, Red Hat is...

http://howtojboss.com/2013/09/10/poll-results-do-you-have-a-data-grid/[Poll Results: Do you have a data grid?]::
  I created a poll last October: Do you have a data grid?...

http://howtojboss.com/2013/09/04/ampd-for-hadoop-alternatives/[AMP’d for Hadoop Alternatives]::
  Apache Hadoop is not the only game in town. I’ve been following AMPLab (UC Berkeley – link) for some time now. The goal of this...
