:awestruct-layout: product-resources
:awestruct-status: red

== More Resources

- http://www.redhat.com/about/events-webinars/webinars/2013-01-15-supercharge-web-apps-jboss-datagrid[Supercharge your web applications using JBoss Data Grid]
    While there are a number of platforms to address big data, they are often constrained by the I/O performance of the host file system. This can be a show-stopper for applications that require extreme performance and real-time access to data.
- http://www.redhat.com/about/events-webinars/webinars/nosql-no-sweat-with-jboss-data-grid[NoSQL: No sweat with JBoss Data Grid]
    While there are a number of platforms to address big data, they are often constrained by the I/O performance of the host file system. This can be a show-stopper for applications that require extreme performance and real-time access to data.
- http://www.redhat.com/about/events-webinars/webinars/2013-03-06-boost-performance-rh-jboss-data-grid-intel[Is your big data solution a big drag?  Boost performance with Red Hat JBoss Data Grid and Intel]
    While there are a number of platforms to address big data, they are often constrained by the I/O performance of the host file system. This can be a show-stopper for applications that require extreme performance and real-time access to data.