name: Red Hat JBoss Enterprise Application Platform
abbreviated_name: JBoss EAP
current_version: 6.2.0.GA
has_installer: true
documentation_url: https://access.redhat.com/site/documentation/en-US/JBoss_Enterprise_Application_Platform/
guides:
  Release_Notes:
  Administration_and_Configuration_Guide:
  API_Documentation:
    formats:
      html:
      html-single:
  Development_Guide:
  Installation_Guide:
  Migration_Guide:
  Security_Guide:
downloads:
  6.1.0.GA:
    release_date: 2013-05-20
  6.2.0.GA:
    description: Minor release of JBoss EAP 6.x series
    release_date: 2013-12-04
    assets:
      installer:
        size: 123mb
      zip:
        size: 456mb
      sha1:
      md5:
      release_notes:
      source:
        size: 789mb
