name: Red Hat JBoss Enterprise Application Platform
abbreviated_name: JBoss EAP
current_version: 6.3.0.GA
has_installer: true
# EAP is still using an old name for docs on the customer portal
documentation_path: JBoss_Enterprise_Application_Platform
xpaas_url: https://www.openshift.com/developers/jboss
intro_video: https://vimeo.com/95462201
vimeo_album: http://vimeo.com/album/2982375
guides:
  Release_Notes:
  Administration_and_Configuration_Guide:
  API_Documentation:
    formats:
      html:
      html-single:
  Development_Guide:
  Installation_Guide:
  Migration_Guide:
  Security_Guide:
  Getting_Started_Guide:
# EAP has an installer, we want to default to that
default_download_artifact_type: installer
downloads:
  6.3.0.GA:
    description: Minor release of JBoss EAP 6.x series
    tag_line: Features an updated administrative console that includes a new homepage and exposes the new JBoss EAP patching feature.  Also includes domain recovery improvements and support for CDI injection with PicketLink.  Try it today!
    release_date: 2014-08-06
    assets:
      installer:
        size: 175mb
      zip:
        name: Zip Files
        artifacts:
          zip:
            size: 151mb
      maven_repo:
        size: 223mb
        name: Maven Repository
      release_notes:
      quickstarts:
        size: 5mb
      source:
        size: 37mb
  6.3.0.Beta:
    description: Minor release of JBoss EAP 6.x series
    tag_line: Features an updated administrative console that includes a new homepage and exposes the new JBoss EAP patching feature.  Also includes domain recovery improvements and support for CDI injection with PicketLink.  Try it today!
    release_date: 2014-05-15
    assets:
      zip:
        name: Zip Files
        artifacts: 
          zip:
            size: 150mb
      release_notes:
      quickstarts:
        size: 5mb
      source:
        size: 37mb
  6.3.0.Alpha:
    description: Minor release of JBoss EAP 6.x series
    tag_line: Features an updated administrative console that includes a new homepage and exposes the new JBoss EAP patching feature.  Also includes domain recovery improvements and support for CDI injection with PicketLink.  Try it today!
    release_date: 2014-03-25
    assets:
      zip:
        name: Zip Files
        artifacts:
          zip:
            size: 148mb
      quickstarts:
        size: 5mb
      release_notes:
      source:
        size: 35mb
  6.2.0.GA:
    description: Minor release of JBoss EAP 6.x series
    release_date: 2013-12-04
    assets:
      installer:
        size: 158mb
      zip:
        name: Zip Files
        artifacts: 
          zip:
            size: 144mb
      quickstarts:
        size: 5mb
      release_notes:
      source:
        size: 34mb
        url: https://www.jboss.org/download-manager/file/jboss-eap-6.2.0-src.zip
# Doesn't seem to exist anymore
#  6.2.0.Beta:
#    description: Minor release of JBoss EAP 6.x series
#    release_date: 2013-12-04
#    assets:
#      installer:
#        size: 158mb
#      zip:
#        name: Zip Files
#        artifacts:
#          zip:
#            size: 34mb
#      release_notes:
#      source:
#        size: 34mb
#  6.1.1.GA:
#    description: Minor release of JBoss EAP 6.x series
#    release_date: 2013-09-04
#    assets:
#      installer:
#        size: 150mb
#      zip:
#        size: 117mb
#      release_notes:
#      source:
#        size: 27mb
  6.1.0.GA:
    description: Minor release of JBoss EAP 6.x series
    release_date: 2013-05-20
    assets:
      installer:
        size: 150mb
      zip:
        name: Zip Files
        artifacts:
          zip:
            size: 110mb
      quickstarts: 
        size: 4.6mb
      release_notes:
      source:
        size: 27mb
#  6.0.1.GA:
#    description: Minor release of JBoss EAP 6.x series
#    release_date: 2013-01-23
#    assets:
#      installer:
#        size: 133mb
#      zip:
#        size: 111mb
#      release_notes:
#      source:
#        size: 21mb
#  6.0.0.GA:
#    description: Major release of JBoss EAP 6.x series
#    release_date: 2012-06-12
#    assets:
#      installer:
#        size: 129mb
#      zip:
#        size: 110mb
#      release_notes:
#      source:
#        size: 21mb
#  5.2.0.GA:
#    description: Minor release of JBoss EAP 5.x series
#    release_date: 2013-01-24
#    assets:
#      binary-installer:
#        size: 417mb
#      binary-zip:
#        size: 294mb
#      release_notes:
#      source:
#        size: 175mb
#
upstream_projects:
  - wildfly
  - jgroups
  - hibernate
  - hornetq
  - jbossclustering
  - jbossmc
  - narayana
  - jbossweb
  - jbossws
  - ironjacamar
  - jgroups
  - mod_cluster
  - jbossas_osgi
  - jbosssso
  - picketlink
  - resteasy
  - weld
  - wise
  - xnio
featured_items:
  - image_url: http://design.jboss.org/jbossdeveloper/sitedesign/jbossdeveloper_1_0/makerfiles/images/developermaterials_eap.png
    title: HTML5 Mobile with EAP 6 at OpenShift
    text: Build HTML5 mobile applications with EAP 6
    url: /video/vimeo/92554627

