<?php

/**
 * @file
 * Contains redhat_developers.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function redhat_developers_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the redhat_developers module.
    case 'help.page.redhat_developers':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('redhat_developers types and fields') . '</p>';
      return $output;

    default:
  }
}

