:awestruct-layout: product-docs-and-apis
== More Resources

http://www.redhat.com/products/jbossenterprisemiddleware/data-virtualization/[JBoss Data Virtualization page on redhat.com]

http://www.redhat.com/about/events-webinars/webinars/2013-08-29-business-intel-using-data-virt[Deliver agile business intelligence using data virtualization]::
    As business intelligence (BI) teams face increasing pressure to perform faster, organizations are quickly adopting agile development methodologies to try and keep up. Watch this video to learn how virtual, integrated views of data make agile BI development easier.

http://www.redhat.com/about/events-webinars/webinars/2013-12-04-gain-insight-from-big-data[Gain Better Insights from Big Data]::
    You're hearing plenty about big data these days. Big data and the technologies that store and process it, like Hadoop, aren't just new data silos. Watch this webinar to learn how Red Hat JBoss Data Virtualization helps you integrate your existing and growing data infrastructure.

== Red Hat JBoss Supported Configurations

https://access.redhat.com/site/articles/703663[Red Hat JBoss Data Virtualization Supported Configurations] +
https://access.redhat.com/site/articles/703673[Red Hat JBoss Data Virtualization Component Details] +
https://access.redhat.com/site/articles/112503[Red Hat JBoss Data Services Supported Configurations] +
https://access.redhat.com/site/articles/112333[Red Hat JBoss Data Services Component Details]
