:awestruct-layout: product-overview

== Overview

JBoss Data Virtualization is useful for any organization who struggles to gain operational and analytical insights due to data locked up in various business units, applications, and technology silos. With the exploding volume and diversity of data, organizations are realizing that physical consolidation or replication of data is not practical for all data integration needs.

JBoss Data Virtualization is complete data provisioning, federation, integration and management solution that access and transforms data from one or more heterogeneous sources into logical, business-friendly data models and easily consumed through standard mechanisms. JBoss Data Virtualization completely hides the complexity of physical data locations, access methods and join logic details from developers and users. This enable organizations to acquire timely, actionable, and integrated information; for enlightened business execution and respond faster to change.

The simplicity offered by JBoss Data Virtualization makes it an ideal solution to enable:

Self-Service Business Intelligence::
  The virtual, reusable data model provides business-friendly representation of data, allowing the user to interact with their data without having to know the complexities of their database or where the data is stored and allowing multiple BI tools to acquire data from centralized data layer.
Agile SOA Development and Integration::
  JBoss Data Virtualization shorten creation of virtual data stores without the need to touch underlying sources and creation of data services that encapsulate the data access logic and allowing multiple business service to acquire data from centralized data layer.
Improve Compliance & Audit controls::
  JBoss Data Virtualization improve data quality via centralized access control, robust security infrastructure and reduction in physical copies of data thus reducing risk. Furthermore, the metadata repository catalogs enterprise data locations and the relationships between the data in various data stores, enabling transparency and visibility.

== Resources


