:awestruct-layout: product-overview

== Overview

JBoss Data Virtualization is useful for any organization who struggles to gain operational and analytical insights due to data locked up in various business units, applications, and technology silos. With the exploding volume and diversity of data, organizations are realizing that physical consolidation or replication of data is not practical for all data integration needs.

JBoss Data Virtualization is complete data provisioning, federation, integration and management solution that access and transforms data from one or more heterogeneous sources into logical, business-friendly data models and easily consumed through standard mechanisms. JBoss Data Virtualization completely hides the complexity of physical data locations, access methods and join logic details from developers and users. This enable organizations to acquire timely, actionable, and integrated information; for enlightened business execution and respond faster to change.

The simplicity offered by JBoss Data Virtualization makes it an ideal solution to enable:

Self-Service Business Intelligence::
  The virtual, reusable data model provides business-friendly representation of data, allowing the user to interact with their data without having to know the complexities of their database or where the data is stored and allowing multiple BI tools to acquire data from centralized data layer.
Agile SOA Development and Integration::
  JBoss Data Virtualization shorten creation of virtual data stores without the need to touch underlying sources and creation of data services that encapsulate the data access logic and allowing multiple business service to acquire data from centralized data layer.
Improve Compliance & Audit controls::
  JBoss Data Virtualization improve data quality via centralized access control, robust security infrastructure and reduction in physical copies of data thus reducing risk. Furthermore, the metadata repository catalogs enterprise data locations and the relationships between the data in various data stores, enabling transparency and visibility.


== Features1
Build Virtual Database Stores
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Complete data provisioning, federation, integration, and management through the creation of virtual logical data models.

== Icon1
[.fa .fa-hdd-o .fa-5x .fa-fw]#&nbsp;#


== Features2
Access via Standard Means
^^^^^^^^^^^^^^^^^^^^^^^^^
Developers can use JBoss Developer Studio, DDL based Virtual Database deﬁnitions, and native queries to access data.

== Icon2
[.fa .fa-info-circle .fa-5x .fa-fw]#&nbsp;#


== Features3
Supports Most Database Types
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Support for Apache Hadoop, NoSQL, JBoss Data Grid, MongoDB as well as a variety of data services like SAP and Salesforce.com.

== Icon3
[.fa .fa-tint .fa-5x .fa-fw]#&nbsp;#

== Resources


== Articles

http://www.ossmentor.com/2014/02/simplified-data-virtualization-install.html[Simplified Data Virtualization Install and Template]::
  I created a template to easily install and start Data Virtualization through the automated installer.  This is done in 5 easy steps.  I structured the demo in such a way that you can add pre-install...

http://www.ossmentor.com/2014/02/data-virtualization-v6-is-now-ga.html[Data Virtualization v6 is now GA!]::
  Red Hat JBoss Data Virtualization - VERSION 6.0 GENERAL AVAILABILITY. Turn siloed, fragmented data into actionable information at your business speed...

http://www.ossmentor.com/2014/02/devnation-by-and-for-developers.html[DevNation - By and For Developers]::
  AN OPEN SOURCE CONFERENCE, BY AND FOR DEVELOPERS ACROSS THE GLOBE  April 13 - 16, 2014 | San Francisco, CA | USA...


