:awestruct-layout: product-overview
:leveloffset: 1

== Overview

JBoss Data Virtualization is useful for any organization who struggles to gain operational and analytical insight due to data locked up in various business units, applications, and technology silos. With the exploding volume and diversity of data, organizations are realizing that physical consolidation or replication of data is not practical for all data integration needs.

== Features1

=== Build Virtual Database Stores

Complete data provisioning, federation, integration, and management through the creation of virtual logical data models.

== Icon1

[.fa .fa-hdd-o .fa-5x .fa-fw]#&nbsp;# 

== Features2

=== Access via Standard Means

Developers can use JBoss Developer Studio, DDL based Virtual Database deﬁnitions, and native queries to access data.

== Icon2

[.fa .fa-info-circle .fa-5x .fa-fw]#&nbsp;# 

== Features3

=== Supports Most Database Types

Support for Apache Hadoop, NoSQL, JBoss Data Grid, MongoDB as well as a variety of data services like SAP and Salesforce.com.

== Icon3

[.fa .fa-tint .fa-5x .fa-fw]#&nbsp;#

== Resources 

== Articles

http://www.ossmentor.com/2014/02/simplified-data-virtualization-install.html[Simplified Data Virtualization Install and Template]::
  I created a template to easily install and start Data Virtualization through the automated installer.  This is done in 5 easy steps.  I structured the demo in such a way that you can add pre-install...

http://www.ossmentor.com/2014/02/data-virtualization-v6-is-now-ga.html[Data Virtualization v6 is now GA!]::
  Red Hat JBoss Data Virtualization - VERSION 6.0 GENERAL AVAILABILITY. Turn siloed, fragmented data into actionable information at your business speed...

http://www.ossmentor.com/2014/02/devnation-by-and-for-developers.html[DevNation - By and For Developers]::
  AN OPEN SOURCE CONFERENCE, BY AND FOR DEVELOPERS ACROSS THE GLOBE  April 13 - 16, 2014 | San Francisco, CA | USA...  

