= Red Hat Developer FAQ
:awestruct-layout: faq
:awestruct-status: yellow
:awestruct-issues: [WAY-46]
:awestruct-description: Answers common questions about JBoss product and project availability and www.jboss.org.
:awestruct-interpolate: true

== Overview

=== What is the Red Hat Developer Program?

The purpose of the Red Hat Red Hat Developer program is to provide subscribers the best tools, content and assistance so that they can be as productive as possible with Red Hat JBoss middleware technologies.

Subscribers get access to Red Hat JBoss Enterprise Middleware products, exclusive content and access to product-focused forums.  All of these assets are focused on helping subscribers make applications with JBoss technologies as easy as possible.

=== How do I get a subscription?

You must have an account in order to download product binaries under the $0 developer subscription, post in the forums, and access exclusive content. In order to register for an account you will need to provide your name and your email address. We encourage you to provide more information so that others know a bit more about you.  You must also agree to the #{site.base_url}/terms-and-conditions/[terms and conditions] of the program.

1. Click the *Register* link at the top right of this page.
2. Fill out the form.
3. You will be sent an email to verify your email address.

=== Will a subscription cost me anything?

The Red Hat Developer Program is available for $0.  You will need to register, provide some minimal information and agree to the #{site.base_url}/terms-and-conditions/[terms and conditions] of the program.

=== Are there any restrictions?

The #{site.base_url}/terms-and-conditions/[terms and conditions] describe how the developer program subscription may be used.  The major difference between a full commercial http://www.redhat.com/about/subscription/[Red Hat subscription] and the Developer Program subscription is that the Red Hat Red Hat Developer Program is intended for individual *developer-use* only.  Integration, test and production environments will require a paid subscription.


=== How do I learn more about Red Hat subscriptions?

Find out more about the value of http://www.redhat.com/about/subscription/[Red Hat subscriptions].  Contact sales via http://www.redhat.com/contact/sales.html[web form] or http://www.redhat.com/resourcelibrary/articles/articles-red-hat-enterprise-linux-renewal-guide[phone] Red Hat or a partner.

=== How do I get started?

1.  Create or update your account.
2.  Download link:#{site.base_url}/products/devstudio/overview/[Red Hat Developer Studio].
3.  Check out the many quickstarts and tutorials listed in the link:#{site.base_url}/resources[resources] section.

=== How do I edit my profile?

If you have a JBoss account, you can create a profile associated with it. On the profile you can provide a bio, upload a photo, and link your social media accounts.

1. If you aren't already logged in, you need to click the *Login* link at the top right of this page.
2. Click on your name or photo at the top right of this page, to take to your profile.
3. Click *Edit profile* in the *Actions* widget on the right of the page.
4. Make your changes.
5. Save your changes using the *Save* button.

== Asking for help

=== How do I ask for help?

Many pages include a comment box at the bottom. This allows you to quickly ask a question about the topic covered by the page.

// Alternatively, you may want to post a message in a link:../forums[forum]. Each forum contains a series of related topics, allowing users to search for information quickly and easily. Creating a new thread is as simple as choosing a relevant forum and posting a message. Threads are stored in chronological order so that anyone reading them later can follow what was discussed. Replies to threads are nested.

=== When should I create a new thread?

If you're thinking about using the forums to ask for help, or to find the answer to a question, then take a moment to have a look and see if somebody else has already created a similar thread or posted a reply with relevant information. This may well save you time!

If you cannot find a previous thread, then should create a new thread.

=== Is there a guide to using the search, markup wiki and other features of community.jboss.org?

http://community.jboss.org uses Jive. You can find the user guide for Jive link:http://docs.jivesoftware.com/jive/6.0/community_user/index.jsp[here^].

== Reporting issues with JBoss Products and Upstream Projects

=== I've found an issue in a product, where should I ask for help? Where should I report it?

You should ask any questions in the relevant product forum. You should report the issue in the relevant product issue tracker. We'd also appreciate it if you tested the upstream project as well - if you find an issue there, then please file an issue in their issue tracker as well.

Your issue will be treated as any other issue found in the community is. The issue will be triaged according to it's severity, and the number of people it is likely to affect.

=== How do I report an issue?

Our issue tracking system is available on http://issues.jboss.org. You may use your jboss.org user account to login this system. To find out how to use the issue tracking system, refer to https://confluence.atlassian.com/display/JIRA/JIRA+Documentation

=== What information should I provide when submitting a bug report?

When submitting a bug report, please include the following information:

* The operating system you are using, e.g. RHEL 5, Windows XP, Solaris 10
* The JDK or JRE you are using, e.g. Sun Microsystems JDK 1.5.0_09
* As much of the stack trace (if there is one) as necessary to show the cause of the problem.
* A list of steps needed to reproduce the bug.

The objective is to give enough information for someone with no prior knowledge of the bug to recreate the problem for themselves. Too little information may prevent them understanding when the bug occurs and too much information can create unnecessary confusion.

=== What information should I provide when submitting a Feature Request?

When submitting a request for a new feature make sure to keep it as clear and to the point as possible. Each new feature requires its own issue in the issue tracking system so that they can be addressed separately by developers. It is up to the project leads to determine when new features are added, according to the development plans they have made. You may point out reasons why features should be added sooner rather than later, such as the ability to compete with an alternative technology, but unless you are willing to do the work yourself you may have to wait for development to take place.

It is very helpful to provide any use cases you may have, to help the person who implements your request understand the motivation.

== Accounts and Profiles

=== I've forgotten my password, can you reset it for me?

1. Go to the https://community.jboss.org/emailPasswordToken%21input.jspa[Reset Your Password] page.
2. Enter your user name or email.
3. We will email you a link you can use to reset your password.

If you have any problems please contact us with the details and we'll do our best to help.
