= JBoss Developer FAQ 
:awestruct-layout: faq
:awestruct-status: red
:awestruct-description: Answers common questions about JBoss product and project availability and www.jboss.org.

== Accounts and Profiles
=== I've forgotten my password, can you reset it for me?

1. Go to the https://community.jboss.org/emailPasswordToken%21input.jspa[Reset Your Password] page.
2. Enter your username or e-mail 
3. We will email you a link you can use to reset your password.

If you have any problems please contact us with the details and we'll do our best to help.


=== How do I sign up for an account?

You must have an account in order to download product binaries under the $0 developer subscription, post in the forums, and access some content. In order to register for an account you must provide your name and your email address. We encourage you to provide more information so that others know a bit more about you.

1. Click the *Register* link at the top right of this page.
2. Fill out the form.
3. You will be sent an email to verify your email address

=== How do I edit my profile?

If you have a JBoss account, you can create a profile associated with it. On the profile you can provide a bio, upload a photo, and link your social media accounts.

1. If you aren't already logged in, you need to click the *Login* link at the top right of this page.
2. Click on your name or photo at the top right of this page, to take to your profile.
3. Click *Edit profile* in the *Actions* widget on the right of the page.
4. Make your changes
5. Save your changes using the *Save* button

== Asking for help

=== How do I ask for help?

Many pages include a comment box at the bottom. This allows you to quickly ask a question about the topic covered by the page.

Alternatively, you may want to post a message in a forum. Each forum contains a series of related topics, allowing users to search for information quickly and easily. Creating a new thread is as simple as choosing a relevant forum and posting a message. Threads are stored in chronological order so that anyone reading them later can follow what was discussed.Replies to threads are nested.

=== Can I be notified to updates threads on the forums?

TODO

=== How do I choose which forum to post in?

Each product has a forum, and you should choose the forum to post to based on the product you need help with. Many projects have forums or mailing lists, and details can be found on the link:../projects[Upstream projects] page. 

=== When should I create a new thread?

If you're thinking about using the forums to ask for help, or to find the answer to a question, then take a moment to have a look and see if somebody else has already created a similar thread or posted a reply with relevant information. This may well save you time!

To perform a search simply TODO. This will present you with a page where you can enter a search query and specify search options.

If can't find a previous thread, then should create a new thread.

=== Do you have a forum policy?

Yes, we do. When you post to the forums, please follow these simple guidelines.

TODO

=== Is there a guide to using the search, markup wiki and other features of http://community.jboss.org?

http://community.jboss.org uses Jive. You can find the user guide for Jive at TODO

== Reporting issues with JBoss Products and Upstream Projects

=== How do I report an issue?

Our issue tracking system is available on http://issues.jboss.org. You may use your jboss.org user account to login this system. To find out how to use the issue tracking system, refer to TODO

=== What information should I provide when submitting a bug report?

When submitting a bug report, please include the following information:

* The operating system you are using, e.g. RHEL 5, Windows XP, Solaris 10
* The JDK or JRE you are using, e.g. Sun Microsystems JDK 1.5.0_09
* As much of the stack trace (if there is one) as necessary to show the cause of the problem.
* A list of steps needed to reproduce the bug.

The objective is to give enough information for someone with no prior knowledge of the bug to recreate the problem for themselves. Too little information may prevent them understanding when the bug occurs and too much information can create unnecessary confusion.

=== What information should I provide when submitting a Feature Request?

When submitting a request for a new feature make sure to keep it as clear and to the point as possible. Each new feature requires its own issue in the issue tracking system so that they can be addressed separately by developers. It is up to the project leads to determine when new features are added, according to the development plans they have made. You may point out reasons why features should be added sooner rather than later, such as the ability to compete with an alternative technology, but unless you are willing to do the work yourself you may have to wait for development to take place.

It is very helpful to provide any use cases you may have, to help the person who implements your request understand the motivation.

