= Get started with JBoss products 
:awestruct-layout: get-started-overview
:awestruct-status: yellow
:awestruct-issues: [DEVELOPER-271]
:awestruct-description: Learn how to get started and how to be productive with JBoss products.

== Learning Materials

=== link:../developer-materials[Developer Materials]

See all quickstarts, demos, videos, and other materials we provide for developers to get coding quickly.

//=== link:../convince[Is JBoss Right for Me?]

//Why should you even consider paying for JBoss Enterprise Middleware? 

=== link:http://www.redhat.com/training/[Training Courses]

Master building applications with our lab-intensive, hands-on training courses. Available onsite, in a http://www.redhat.com/travel-less/[virtual classroom or self-paced online].

=== link:http://www.jboss.org/migration/[Migration]

We can help you successfully and efficiently migrate your applications to Red Hat JBoss Middleware

=== link:../books[Books]

Like dead trees? Check out all the books ever written about JBoss

== Troubleshooting and Help

=== link:../forums[Forums]

Talk with us about your projects, issues you are running into, or suggestions you have.

=== link:https://access.redhat.com/site/documentation/[Documentation]

Access our full product documentation for release notes, installation guides and more.

=== link:http://www.redhat.com/consulting/[Red Hat Consulting]

Still not getting where you need to be? Consider Red Hat Consulting for futher help.

=== link:http://access.redhat.com[Submit a Ticket]

Are you a Red Hat subscription user? Submit a ticket on the Red Hat Customer Portal.

== Spread the Word

=== link:../why-subscribe[Why Subscribe?]

Learn about JBoss Subscriptions and why you and your boss should use Red Hat JBoss Middleware

=== link:../get-involved[Get Involved]

Work alongside smart, motivated people to apply your skills toward a bigger effort.

