:awestruct-layout: technology
:awestruct-status: yellow
:awestruct-issues: [DEVELOPER-162, DEVELOPER-195]

== Overview

Red Hat(R) JBoss(R) Middleware is a family of a lightweight, cloud-friendly, enterprise-grade products that help enterprises innovate faster, in a smarter way. That's what we call enlightened innovation.

The ideal middleware portfolio for open hybrid cloud environments, our products and services help you accelerate application development, deployment, and performance, integrate data and applications efficiently, and automate business processes across physical, virtual, mobile, and cloud environments.

== Supported Products

The Red Hat JBoss Middleware portfolio comprises enterprise-ready software that harnesses the benefits of innovation and the transparency of open source software while mitigating risks. Red Hat JBoss solutions deliver long-term, enterprise-class stability, reference implementations, partner certifications, multi-year maintenance policies, and service-level agreement (SLA)-based developer and production support expected from traditional proprietary software solutions.

Available via subscription, Red Hat JBoss Middleware is compelling for organizations who want to increase productivity, value, and control while still benefiting from enterprise-class support SLAs, guaranteed patches, updates and hot-fixes, and legal assurance.

Compared with proprietary alternatives, Red Hat JBoss Middleware delivers enterprise-class stability and performance at significantly lower costs. And compared with JBoss Community projects, JBoss Middleware reduces business and technical risks, increases IT productivity, and speeds time to deployment. 

== Upstream Projects
JBoss redefined the application server back in 2002 when it broke apart the monolithic designs of the past with its modular architecture. Since then we've continued to find new ways to challenge convention and redefine Enterprise Java through community-driven projects. Community projects represent the latest technologies for use in cutting-edge applications and offer best-effort, community support.

== Solutions
JBoss(R) Enterprise Application Platform 6 provides an innovative modular, cloud-ready architecture, powerful management and automation, and world class developer productivity. It is Java(TM) EE 6 certified and features powerful yet flexible management, improved performance and scalability, and many new features to maximize developer productivity. All with Red Hat(R)'s market-leading reputation for certification and support, ensuring your administration and development needs are met as you continue to drive forward into the future and beyond.

== Community Powered Innovation
JBoss(R) Enterprise Application Platform 6 provides an innovative modular, cloud-ready architecture, powerful management and automation, and world class developer productivity. It is Java(TM) EE 6 certified and features powerful yet flexible management, improved performance and scalability, and many new features to maximize developer productivity. All with Red Hat(R)'s market-leading reputation for certification and support, ensuring your administration and development needs are met as you continue to drive forward into the future and beyond.

