:awestruct-layout: technology

== Overview
JBoss(R) Enterprise Application Platform 6 provides an innovative modular, cloud-ready architecture, powerful management and automation, and world class developer productivity. It is Java(TM) EE 6 certified and features powerful yet flexible management, improved performance and scalability, and many new features to maximize developer productivity. All with Red Hat(R)'s market-leading reputation for certification and support, ensuring your administration and development needs are met as you continue to drive forward into the future and beyond.

== Supported Products
JBoss(R) Enterprise Application Platform 6 provides an innovative modular, cloud-ready architecture, powerful management and automation, and world class developer productivity. It is Java(TM) EE 6 certified and features powerful yet flexible management, improved performance and scalability, and many new features to maximize developer productivity. All with Red Hat(R)'s market-leading reputation for certification and support, ensuring your administration and development needs are met as you continue to drive forward into the future and beyond.

== Upstream Projects
JBoss(R) Enterprise Application Platform 6 provides an innovative modular, cloud-ready architecture, powerful management and automation, and world class developer productivity. It is Java(TM) EE 6 certified and features powerful yet flexible management, improved performance and scalability, and many new features to maximize developer productivity. All with Red Hat(R)'s market-leading reputation for certification and support, ensuring your administration and development needs are met as you continue to drive forward into the future and beyond.

== Solutions
JBoss(R) Enterprise Application Platform 6 provides an innovative modular, cloud-ready architecture, powerful management and automation, and world class developer productivity. It is Java(TM) EE 6 certified and features powerful yet flexible management, improved performance and scalability, and many new features to maximize developer productivity. All with Red Hat(R)'s market-leading reputation for certification and support, ensuring your administration and development needs are met as you continue to drive forward into the future and beyond.

== Community Powered Innovation
JBoss(R) Enterprise Application Platform 6 provides an innovative modular, cloud-ready architecture, powerful management and automation, and world class developer productivity. It is Java(TM) EE 6 certified and features powerful yet flexible management, improved performance and scalability, and many new features to maximize developer productivity. All with Red Hat(R)'s market-leading reputation for certification and support, ensuring your administration and development needs are met as you continue to drive forward into the future and beyond.

