:awestruct-layout: technology
:awestruct-status: yellow
:awestruct-issues: [DEVELOPER-195, DEVELOPER-84, DEVELOPER-83, DEVELOPER-85]

== Overview

Red Hat(R) JBoss(R) Middleware is a family of a lightweight, cloud-friendly, enterprise-grade products that help enterprises innovate faster, in a smarter way. That's what we call enlightened innovation.

The ideal middleware portfolio for open hybrid cloud environments, our products and services help you accelerate application development, deployment, and performance, integrate data and applications efficiently, and automate business processes across physical, virtual, mobile, and cloud environments.

== Supported Products

Our supported product portfolio provides enterprise-ready software built from an innovative community of projects. It delivers enterprise-class stability, enterprise-class support SLAs, guaranteed patches, updates and hot-fixes, and legal assurance. Reducing business and technical risks, increasing productivity, and speeding up time to deployment - Red Hat JBoss Middleware provides a solution that works for your enterprise at a lower cost than proprietary alternatives.

== Upstream Projects
JBoss redefined the application server back in 2002 when it broke apart the monolithic designs of the past with its modular architecture. Since then we've continued to find new ways to challenge convention and redefine Enterprise Java through community-driven projects. Community projects represent the latest technologies for use in cutting-edge applications and offer best-effort, community support.

== Solutions
JBoss(R) Enterprise Application Platform 6 provides an innovative modular, cloud-ready architecture, powerful management and automation, and world class developer productivity. It is Java(TM) EE 6 certified and features powerful yet flexible management, improved performance and scalability, and many new features to maximize developer productivity. All with Red Hat(R)'s market-leading reputation for certification and support, ensuring your administration and development needs are met as you continue to drive forward into the future and beyond.

== Community Powered Innovation
JBoss(R) Enterprise Application Platform 6 provides an innovative modular, cloud-ready architecture, powerful management and automation, and world class developer productivity. It is Java(TM) EE 6 certified and features powerful yet flexible management, improved performance and scalability, and many new features to maximize developer productivity. All with Red Hat(R)'s market-leading reputation for certification and support, ensuring your administration and development needs are met as you continue to drive forward into the future and beyond.

