:awestruct-layout: terms-and-conditions
:awestruct-status: green
:awestruct-issues: []
:awestruct-title: Developer Program Terms and Conditions
:awestruct-description: Developer Program Terms and Conditions
:icons: font

== Developer Program Terms & Conditions

We are excited that you are interested in participating in the Red Hat Developer Program ("the Program"). The Program allows you to deploy, free of charge, certain Red Hat Subscriptions for development purposes subject to the terms below. The Red Hat Subscriptions offered to you in this Program are unsupported, intended for development purposes only, are not intended for other purposes such as production environments without an active Red Hat Subscription(s) *_and may not address known security vulnerabilities._*

The following terms apply to you and/or your company if you choose to participate in the Program.

By participating in the Program and accepting these terms, you represent that you will be using the Red Hat Subscriptions(s) for *development purposes only*, and Red Hat is relying on your representation as a condition of our providing you access to the Subscription(s). If you use the Red Hat Subscriptions for any other purposes, you are in violation of Red Hat’s Enterprise Agreement set forth below and are required to pay the applicable subscription fees, in addition to any and all other remedies available to Red Hat under applicable law. Examples of such violations include, but are not limited to, 

* using the services provided under the Program for a production installation,
* offering support services to third parties, or
* complementing or supplementing third party support services with services received under the Program.

Red Hat is providing you with access to one or more Red Hat Subscriptions for development purposes subject to the following conditions: (a) you agree that the terms in the Red Hat’s Enterprise Agreement set forth at http://www.redhat.com/licenses (the "Agreement") govern your usage of the Red Hat Subscriptions and (b) if you use the Red Hat Subscription for any purpose other than development purposes, you agree to pay Red Hat the Subscription Fee(s) for each Unit of Red Hat Subscription pursuant to the Agreement.

PLEASE READ THE AGREEMENT CAREFULLY BEFORE USING THE RED HAT SUBSCRIPTIONS. BY USING RED HAT SUBSCRIPTIONS, YOU SIGNIFY YOUR ASSENT TO AND ACCEPTANCE OF THE AGREEMENT AND ACKNOWLEDGE YOU HAVE READ AND UNDERSTAND THE TERMS. AN INDIVIDUAL ACTING ON BEHALF OF AN ENTITY REPRESENTS THAT HE OR SHE HAS THE AUTHORITY TO ENTER INTO THE AGREEMENT ON BEHALF OF THAT ENTITY. IF YOU DO NOT ACCEPT THE TERMS OF THE AGREEMENT, THEN YOU MUST NOT USE THE RED HAT SUBSCRIPTIONS.

Thank you!
