<?php

/**
 * @file
 * Contains books.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function books_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the books module.
    case 'help.page.books':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('RHDP Books Content Type') . '</p>';
      return $output;

    default:
  }
}
