name: Red Hat JBoss BPM Suite
abbreviated_name: JBoss BPM Suite
product_logo: bpm-suite.png
has_installer: true
current_version: 6.2.0.GA
documentation_minor_version: 6.2
xpaas_url: https://www.openshift.com/developers/jboss-bpms
intro_video: https://vimeo.com/142883902
vimeo_album: http://vimeo.com/album/2982446
youtube_album: https://www.youtube.com/playlist?list=PLf3vm0UK6HKphPQWLX8SPJlPyqDhpZS4U
skip_installation_instructions: true
skip_maven_instructions: true
index:
  desc: |
    A business process and decision management platform that combines business rules management, business process management (BPM), and complex event processing.
buzz_tags:
  - BPM Suite
  - jBPM
  - JBoss BPMS
guides:
  Release_Notes:
  Administration_And_Configuration_Guide:
  Business_Resource_Planner_Guide:
  Development_Guide:
  Getting_Started_Guide:
  Installation_Guide:
  Migration_Guide:
  User_Guide:
default_download_artifact_type: installer
description: 'A powerful combination of business rules management, business process management (BPM), and complex event processing.'
downloads:
  # 6.0.2 is an exclusion to the "no micros through $0 dev program
  6.2.0.GA:
    description: Minor release in the JBoss BPM Suite 6.x series.
    tag_line: One integrated User Interface - Business Central that is central to all business activities, an integrated modeling environment for business users. Includes process modeling, data modeling, user forms design and rules authoring, process simulation to help business users understand the likely behaviors, costs, etc. of business processes before they are deployed in production, business Activity Monitoring (BAM) tools such as Dashboards, Reports, KPI indicators etc. that provide business managers with a complete picture of the state and performance of automated processes and a BPM runtime platform that will reliably handle a wide range of workloads, from small departments to global enterprises.
    release_date: 2015-12-07
    assets:
      installer:
        size: 277mb
      zip:
        artifacts:
          deployable:
            size: 206mb
      zip_planner:
        size: 94mb
        name: Optaplanner
      example:
        size: 4mb
        name: Quickstarts
      zip_supplemental:
        size: 63mb
        name: Supplemental Tools
      release_notes:
      source:
        size: 152mb
  6.1.0.GA:
    description: Minor release in the JBoss BPM Suite 6.x series
    tag_line: Critical enterprise features such as better integration with Camel, highly customizable business central that enables partners and customers to extend the platform, productivity enhancement features, collaborative user interface and enhanced stability of the platform. Includes full support for Business Resource Planner that offers ability to build resource optimized solutions.
    release_date: 2015-04-16
    assets:
      installer:
        size: 177mb
      zip:
        artifacts:
          deployable:
            size: 187mb
      zip_planner:
        size: 89mb
        name: Optaplanner
      example:
        size: 4mb
        name: Quickstarts
      zip_supplemental:
        size: 70mb
        name: Supplemental Tools
      release_notes:
      source:
        size: 194mb
  6.0.2.GA:
    description: Red Hat JBoss BPM Suite 6.0.2 is an incremental bug fix release over the 6.0.1 version.
    tag_line: This release brings in 250+ bug fixes, support for IBM Websphere, certification on RHEL7 and several new quick starts.
    release_date: 2014-06-30
    assets:
      installer:
        size: 294mb
      zip:
        artifacts:
          deployable:
            size: 170mb
      zip_planner:
        size: 53mb
        name: Optaplanner
      example:
        size: 8mb
        name: Quickstarts
      zip_supplemental:
        size: 57mb
        name: Supplemental Tools
      release_notes:
      source:
        size: 150mb
  # 6.0.1 is an exclusion to the "no micros through $0 dev program
  6.0.1.GA:
    release_date: 2014-04-03
    assets:
      installer:
        size: 312mb
      zip:
        artifacts:
          deployable:
            size: 304mb
      maven_repo:
        size: 280mb
        name: Maven Repository
      zip_planner:
        size: 53mb
        name: Optaplanner
      example:
        size: 7.8mb
        name: BPM Example
      zip_supplemental:
        size: 59mb
        name: Supplemental Tools
      release_notes:
      source:
        size: 177mb
upstream_projects:
  - drools
  - guvnor
  - optaplanner
  - jbpm 
featured_items:
  - image_url: http://design.jboss.org/jbossdeveloper/sitedesign/jbossdeveloper_1_0/makerfiles/images/developermaterials_bpmsuite.png
    url: /quickstarts/brms/tasks-bpmsuite
evaluation: https://access.redhat.com/products/red-hat-jboss-bpm-suite/evaluation
