:awestruct-layout: product-get-started

== Overview
==== link:http://jboss.org[Enterprise Application Platform 6.1.0 with Installer]

== Installation

**Instructions for Installation**

Installation prerequisites:

- Install a JDK of your choice.  We recommend ____
- On Microsoft Windows Server, ensure that the JAVA_HOME and PATH environment variables have been      set, otherwise shortcuts will not work.
- On Hewlett-Packard HP-UX, ensure that an unzip utility has been installed.

In Windows or Mac, you can start the installer by double clicking on the JAR file.

In Linux, open a terminal window in the target machine and navigate to where the GUI installer was downloaded.  Launch the GUI installer by executing the following command:

 java -jar jboss-eap-6.1.0-installer.jar

For more details, view the Installation Guide

== Getting Started Materials

**Install the Apache™ Maven Repo** + 
Download a local copy of the maven repository so you can run architypes and quickstarts.

**Install our EAP 6.1.0 Quickstarts** + 
Download our quickstarts to show you how to get up and running quickly with Enterprise Application Platform 6.1.0.

**Try Our Comprehensive Example or Other Quickstarts**




== Demos

== Questions

http://google.com[Question 1] + 
http://google.com[Question 2] + 
http://google.com[Question 3] + 