:awestruct-layout: product-get-started
:awestruct-interpolate: true

== Prerequisites section title
Prerequisites &#38; Required Dependencies Checklist

== Step1 Duration
5 minutes

== Step2 Duration
10 minutes

== Step3 Duration
20 minutes

== Step1 Content
1.  Install the Apache Maven and Java SE Development Kit (JDK), we recommend OpenJDK or
Oracle JDK
2.  Download link:#{site.download_manager_base_url}/download-manager/file/jboss-eap-7.0.0.zip[Red Hat JBoss Enterprise Application Platform 7.0]
3.  Install JBoss EAP
+
For Mac / Windows Development Hosts:
+
a.  Go to the folder you have downloaded JBoss EAP 7.0:
... Right Click on `jboss-eap-7.0.0.zip`
... Select _Extract All_

+
For Linux Development Hosts:
a. Go to the folder where you have downloaded JBoss EAP 7, and Extract the ZIP archive
+
----
unzip jboss-eap-7.0.0.zip
----

*Note:* The directory created by extracting the ZIP archive is the top-level directory for the JBoss EAP installation. This is referred to as `JBOSS_HOME`


== Step2 Content
To verify that JBoss EAP is working correctly you will now start, build, deploy and execute the _helloworld_ quickstart application in
an EAP server :

1. Start JBoss EAP
+
For Windows Development Hosts:
+
a. Go to `JBOSS_HOME` directory
... Go to a subdirectory named `bin`
... Double click on standalone.bat

+
For Mac/Linux Development Hosts:
a. Go to the `JBOSS_HOME` directory and run the following command in a terminal:
+
----
sh bin/standalone.sh
----

3. Download link:#{site.download_manager_base_url}/download-manager/file/jboss-eap-7.0.0-quickstarts.zip[Red Hat JBoss EAP 7.0 quickstarts]
4. Extract the quickstarts
+
For Mac / Windows Development Hosts:
+
a.  Go to the folder you have downloaded JBoss EAP 7.0:
...  Right Click on `jboss-eap-7.0.0-quickstarts.zip`
... Select _Extract All_

+
For Linux Development Hosts:
a. Go to the folder where you have downloaded JBoss EAP 7, and Extract the ZIP archive
+
----
unzip jboss-eap-7.0.0-quickstarts.zip
----
+
5.  Build the _helloworld_ quickstart
a. Got the the folder where you extracted the quickstarts
... Go to the _helloworld_ quickstart folder
... Open a command window and run the following command
+
----
mvn clean package wildfly:deploy
----

This will build, deploy and run the helloworld application inside JBoss
EAP server. To verify that everything worked point a browser to http://localhost:8080/helloworld[], the page should read "Hello World!"

== Step3 Content
Follow the below series to build your first application. You will build some simple examples as well as build a TicketMonster Application using JBoss EAP. The TicketMonster application shows you how to build a modern HTML application that communicates with a Java EE backend using REST. The series walks you through each step of the application development lifecycle, from start to finish.

[width="100%",cols="50%,50%",]
|=======================================================================
|*Step 1:* Learn more about getting started
|https://access.redhat.com/documentation/en/red-hat-jboss-enterprise-application-platform/7.0/getting-started-guide/getting-started-guide[JBoss Enterprise Application Platform Getting Started Guide]

|*Step 2:* Start exploring TicketMonster |link:http://www.jboss.org/ticket-monster/[Tutorial]
|=======================================================================

== More Resources

* link:../learn[See Quickstarts, Videos, and other Learning materials]
* link:../buzz[Read about how other people are using JBoss EAP]
