:awestruct-layout: product-overview
:awestruct-status: green

== Overview

JBoss(R) Enterprise Application Platform 6 provides an innovative modular, cloud-ready architecture, powerful management and automation, and world class developer productivity. It is Java(TM) EE 6 certified and features powerful yet flexible management, improved performance and scalability, and many new features to maximize developer productivity. All with Red Hat(R)'s market-leading reputation for certification and support, ensuring your administration and development needs are met as you continue to drive forward into the future and beyond.

== Resources

- Get started with our comprehensive example, TicketMonster, or through one of our many quickstarts at http://www.jboss.org/jdf/.

== Features1
Accelerate Development
^^^^^^^^^^^^^^^^^^^^^^

Includes everything needed to build, run and manage services for Java EE 6 enterprise applications - from HTML5 mobile to highly transactional applications.

== Icon1
[.fa .fa-code .fa-5x]#&nbsp;#


== Features2
Accelerate Deployment
^^^^^^^^^^^^^^^^^^^^^
Boosts eﬃciency with an extremely low memory footprint and blazingly fast start-up times. Simpliﬁes deployment to virtualized environments with smart resource utilization and port management.

== Icon2
[.fa .fa-dashboard .fa-5x]#&nbsp;#


== Features3
Cloud Ready
^^^^^^^^^^^
Oﬀers a lightweight, eﬃcient and modern architecture based on a services-driven set of components.  Simpliﬁes application deployment into both on-premise and cloud environments.

== Icon3
[.fa .fa-cloud .fa-5x]#&nbsp;#