:awestruct-layout: product-overview
:leveloffset: 1

== Overview

JBoss(R) Enterprise Application Platform 6 provides an innovative modular, cloud-ready architecture, powerful management and automation, and world class developer productivity. It is Java(TM) EE 6 certified and features powerful yet flexible management, improved performance and scalability, and many new features to maximize developer productivity. All with Red Hat(R)'s market-leading reputation for certification and support, ensuring your administration and development needs are met as you continue to drive forward into the future and beyond.

== Features1

=== Accelerate Development

Includes everything needed to build, run and manage services for Java EE 6 enterprise applications - from HTML5 mobile to highly transactional applications.

== Icon1

[.fa .fa-code .fa-5x .fa-fw]#&nbsp;# 

== Features2

=== Accelerate Deployment

Boosts efficiency with an extremely low memory footprint and blazingly fast start-up times. Simpliﬁes deployment to virtualized environments with smart resource utilization and port management.

== Icon2
[.fa .fa-dashboard .fa-5x .fa-fw]#&nbsp;#


== Features3

=== Cloud Ready

Offers a lightweight, efficient and modern architecture based on a services-driven set of components.  Simplifies application deployment into both on-premise and cloud environments.

== Icon3
[.fa .fa-cloud .fa-5x .fa-fw]#&nbsp;#

== Resources

- Get started with our comprehensive example, TicketMonster, or through one of our many quickstarts in link:../developer-materials/[Developer Materials].

== Articles

http://howtojboss.com/2013/10/16/server-side-web-frameworks-the-last-stand/[Server Side Web Frameworks, The Last Stand]::
  I’m a fan of client / server architecture. I believe that... The front end should be limited to the presentation tier the back end should be limited to the logic / data tiers...

http://howtojboss.com/2013/10/02/the-beginning-of-the-end-of-web-containers/[The beginning of the end of web containers?]::
  Is this the beginning of the end of web containers (i.e. servlet containers)? For years, I preferred running Tomcat. It was easy. To install, extract the files. It was ...

http://howtojboss.com/2013/09/19/need-to-meet-business-priorities-accelerate-development/[Need to meet business priorities? Accelerate development.]::
  The business priorities may include increasing enterprise growth, delivering operational results, accelerating innovation, and increasing satisfaction...

