:awestruct-layout: product-overview
:leveloffset: 1

== Overview

JBoss(R) Enterprise Application Platform 6 provides an innovative modular, cloud-ready architecture, powerful management and automation, and world class developer productivity. It is Java(TM) EE 6 certified and features powerful yet flexible management, improved performance and scalability, and many new features to maximize developer productivity. All with Red Hat(R)'s market-leading reputation for certification and support, ensuring your administration and development needs are met as you continue to drive forward into the future and beyond.

== Features1

=== Accelerate Development

Includes everything needed to build, run and manage services for Java EE 6 enterprise applications - from HTML5 mobile to highly transactional applications.

== Icon1

[.fa .fa-code .fa-4x .fa-fw]#&nbsp;# 

== Features2

=== Accelerate Deployment

Boosts efficiency with an extremely low memory footprint and blazingly fast start-up times. Simplifies deployment to virtualized environments with smart resource utilization and port management.

== Icon2
[.fa .fa-dashboard .fa-4x .fa-fw]#&nbsp;#


== Features3

=== Cloud Ready

Offers a lightweight, efficient and modern architecture based on a services-driven set of components.  Simplifies application deployment into both on-premise and cloud environments.

== Icon3
[.fa .fa-cloud .fa-4x .fa-fw]#&nbsp;#
