:awestruct-layout: product-updates
:awestruct-interpolate: true
:leveloffset: 1
:awestruct-description: "Find the latest updates about Red Hat JBoss Enterprise Application Platform"

[[eap-7-beta]]
== JBoss EAP 7 Beta

The result of years of hard work and dedication by the JBoss EAP / WildFly community, JBoss EAP 7 Beta offers a fresh foundation for enterprise Java applications to thrive in a world of CI/CD, DevOps, cloud, containers, and microservices.

The public beta gives you the opportunity to test the product, provide valuable feedback, and jumpstart your projects. link:#{site.base_url}/products/eap/download/[Try out the JBoss EAP 7.0 beta] and let us know what you think!

=== Release Highlights

* *Support for Java EE 7 and Java SE 8* +
Certified Java EE 7 application server and supports Java SE 8. Java EE 7 includes four new specifications and a focus on developer productivity and web-scale applications. In addition to specification support, JBoss EAP 7 also includes enhancements designed to maximize productivity and performance. One example is batch tooling, which enables developers to more easily monitor, create, manage, and configure batch jobs.
 
* *Optimized for container and cloud deployments* +
Built for containers and resource-conscious virtualized or cloud environments such as OpenShift by Red Hat, JBoss EAP 7 features a low-memory footprint for higher density deployments, faster startup, and optimized network port utilization. +
JBoss EAP 7 also offers a newly designed web subsystem, Undertow, which uses the latest non-blocking I/O features of Java to provide improved scalability and performance. Undertow supports the latest web standards such as HTTP/2, HTTP Upgrade, and WebSockets. +

* *Upgrade support featuring interoperability* +
JBoss EAP 7 prioritized straightforward upgrade processes so users can quickly upgrade from older versions of JBoss EAP or Wildfly.  JBoss EAP 7 prioritizes improved protocol version support and tooling, with a focus on interoperability with existing JBoss EAP 5 and 6 environments. For example, the new messaging subsystem is based on the unified messaging technology for Red Hat products, Apache ActiveMQ Artemis. Active MQ Artemis enables customers to pass messages between JBoss EAP 6 and JBoss EAP 7, and preserves the performance, scalability, and reliability of HornetQ from JBoss EAP 6.  

* *Enhanced administration and management* +
JBoss EAP 7 helps extend the productivity benefits of JBoss EAP 6 with several significant administration and management updates. The enhanced management console makes it faster, simpler, and more intuitive for both new and experienced administrators to discover information and execute tasks quickly. JBoss EAP 7 also enhances management command line interface (CLI) functionality by giving administrators the ability to see configuration and logging information, configure subsystems, and manage JBoss EAP servers offline. Also, administrators can perform minimally disruptive maintenance on JBoss EAP 7 servers by using the new server suspend mode to gracefully shut down servers only after completing in-flight transactions.

=== Get started today

*Get started with JBoss EAP 7:*

+++
<iframe width="560" height="315" src="https://www.youtube.com/embed/Cl3SiavsBF4" frameborder="0" allowfullscreen></iframe>
+++


*Get started with JBoss EAP 7 Quickstarts:*

+++
<iframe width="560" height="315" src="https://www.youtube.com/embed/oUWyhl1R4Lk" frameborder="0" allowfullscreen></iframe>
+++


Learn more from our experts via the link:http://developerblog.redhat.com/2016/01/18/jboss-eap-7-beta-is-now-available/[Red Hat Developer Blog!]

*Try it now and join the conversation* +
link:#{site.base_url}/products/eap/download[Download the beta today] and link:https://developer.jboss.org/en/products/eap[join the JBoss EAP forums] to participate in conversations with the JBoss EAP team.


*Helpful Resources* +
link:#{site.base_url}/products/eap/download[JBoss EAP 7 beta download] +
link:https://developer.jboss.org/en/products/eap[JBoss EAP community forum] +
link:https://access.redhat.com/documentation/en/jboss-enterprise-application-platform/[JBoss EAP 7 beta documentation] +
link:http://developerblog.redhat.com/tag/eap7/[JBoss EAP 7 related blogs on Red Hat Developer]
