name: Red Hat Enterprise Linux Atomic Host
abbreviated_name: Atomic Host
documentation_path: Red_Hat_Enterprise_Linux
documentation_minor_version: 7
current_version: 7.1.0.GA
skip_installation_instructions: true
skip_maven_instructions: true
skip_quickstart_link: true
other_product: true
description: A platform optimized for Linux containers 
index:
  desc: |
    Red Hat Atomic Enterprise Platform is an integrated infrastructure platform designed to run, orchestrate and scale multi-container-based applications and services.
guides:
  Release_Notes:
    formats:
      html:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.1_Release_Notes
      html-single:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html-single/7.1_Release_Notes
      epub:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/epub/7.1_Release_Notes/Red_Hat_Enterprise_Linux-7-7.1_Release_Notes-en-US.epub
      pdf:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/pdf/7.1_Release_Notes/Red_Hat_Enterprise_Linux-7-7.1_Release_Notes-en-US.pdf  
  Installation_Guide:
  Package_Manifest:
  Kernel_Crash_Dump_Guide:
  Performance_Tuning_Guide:
downloads:
upstream_projects:
