:awestruct-layout: product-overview
:awestruct-status: yellow
:awestruct-interpolate: true
:leveloffset: 1

== Overview

When developing applications for Red Hat Enterprise Linux®, developers have two major tools chains to utilize.

First, Red Hat Enterprise Linux has a base tool chain that are included with the same support lifecycle.  If you’re building device drivers or need tools that will be supported for 10 years, the Red Hat Enterprise Linux base tool chain will be right for you. With RHEL 7, these include gcc 4.8, Python 2.7, Ruby 2.0, PHP 5.4, Perl 5.16, MariaDB, PostgreSQL 9.2, and Apache 2.4.

Second, for developers who are looking for updated tools, Red Hat® Software Collections and Red Hat Developer Toolset deliver the latest stable versions of dynamic languages, open source databases, web development tools, and other important development resources that can be deployed alongside those included in the Red Hat Enterprise Linux® base tool chain. Red Hat Developer Toolset (for gcc development) and Red Hat Software Collections (for scripting languages, databases, etc.) are available via select Red Hat Enterprise Linux subscriptions, and are updated yearly with two- and three-year life cycles (respectively) to allow rapid innovation without sacrificing stability.

Red Hat Developer Toolset and Red Hat Software Collections (RHSCL) allow you to build and concurrently install multiple versions of the same software components on your system. Packages built using software collections technology do not overwrite system files and can depend on other software collections.  In addition, dockerfiles are available for each Software Collection component for developing in containers, and are identical to the development stacks available on OpenShift.  This means you can develop or deploy on either Red Hat Enterprise Linux or OpenShift.

For details, visit the #{site.base_url}/products/developertoolset/overview/[Red Hat Developer Toolset] and Red Hat Software Collections sections.

