:awestruct-layout: product-overview
:awestruct-status: yellow
:awestruct-interpolate: true
:leveloffset: 1

== Overview

=== Exclusive for Red Hat® Developers community members

*Red Hat Developers members can now link:#{site.download_manager_base_url}/download-manager/file/rhel-server-7.2-x86_64-dvd.iso[download] the no-cost Red Hat Enterprise Linux® Developer Suite subscription for development purposes.* The Red Hat Enterprise Linux Developer Suite subscription includes: +

Through the Red Hat Developers program, the no-cost Red Hat Enterprise Linux Developer Suite provides application developers with the following products and components: +

** *Red Hat Enterprise Linux Server* - An application development entitlement to the world’s leading enterprise Linux platform.
** *Development tools with long-term support* - Each major Red Hat Enterprise Linux release includes a broad set of tools that, like the operating system, are supported for 10 years; including Python, PHP, Ruby, and many more. For Java, both OpenJDK versions 7 (1.7) and 8 (1.8).
** *Development tools with frequent updates* - Numerous programming languages, databases, web servers, and development tools are updated yearly with the most recent, stable versions, and are packaged via link:#{site.base_url}/products/softwarecollections/overview/[Red Hat Software Collections] and link:#{site.base_url}/products/developertoolset/overview/[Red Hat Developer Toolset].
** *Red Hat add-ons* - numerous add-ons are included to help developers create applications that support specific enterprise use cases, including resilient storage, scalable file systems, high-performance networking and many more.
** *System updates* - Updates to the latest versions of Red Hat Enterprise Linux Server plus patches and access to knowledgebase articles are included with the developer subscription.

Red Hat Enterprise Linux Developer Suite includes access to multiple versions of Red Hat Enterprise Linux, including Red Hat Enterprise Linux 5, 6, and 7.

*NOTE:* Red Hat Enterprise Linux Developer Suite subscriptions are for development purposes only; the terms of use are defined in the Red Hat Developers program terms and conditions, and the Red Hat legal agreement for Subscription Services, Appendix 1.

==== Developing container-based applications

Container images and Dockerfiles are available for most Red Hat Software Collections and Red Hat Developer Toolset components. These resources make it easy to build containerized applications using traditional tools. For anyone seeking to create containerized applications for deployment to Red Hat’s ecosystem of container hosts and platforms - we recommend you use the link:#{site.base_url}/products/cdk/overview/[Red Hat Container Development Kit] (CDK) which includes access to Red Hat Enterprise Linux Server, OpenShift Enterprise 3, and a number of other tools via the Red Hat Container Registry.

[.panel.callout.text-center]
*New to Red Hat Enterprise Linux?* +
link:#{site.base_url}/articles/rhel-what-you-need-to-know[Here’s what you need to know.]
