export default [
    {input: 'node_modules/@rhd/dp-category-list/dp-category-list-wc.js', output: { file: 'dist/js/rhd/dp-category-list/dp-category-list-wc.js', format: 'umd', name: 'DPCategoryListWC' }},
    // {input: 'node_modules/@rhd/dp-category-list/dp-category-item-list.js', output: { file: 'dist/js/@rhd/dp-category-list/dp-category-item-list.js', format: 'umd', name: 'DPCategoryItemList' }},
    // {input: 'node_modules/@rhd/dp-category-list/dp-category-item.js', output: { file: 'dist/js/@rhd/dp-category-list/dp-category-item.js', format: 'umd', name: 'DPCategoryItem' }},
    // {input: 'node_modules/@rhd/dp-category-list/dp-category-list.js', output: { file: 'dist/js/@rhd/dp-category-list/dp-category-list.js', format: 'umd', name: 'DPCategoryList' }},
    // {input: 'node_modules/@rhd/dp-category-list/dp-category.js', output: { file: 'dist/js/@rhd/dp-category-list/dp-category.js', format: 'umd', name: 'DPCategory' }},
    // {input: 'node_modules/@rhd/dp-category-list/dp-product-short-teaser.js', output: { file: 'dist/js/@rhd/dp-category-list/dp-product-short-teaser.js', format: 'umd', name: 'DPProductShortTeaser' }},
    {input: 'node_modules/@rhd/dp-search/dp-search.js', output: { file: 'dist/js/rhd/dp-search/dp-search.js', format: 'umd', name: 'DPSearch' }},
    // {input: 'node_modules/@rhd/dp-search/dp-search-active-filters.js', output: { file: 'dist/js/@rhd/dp-search/dp-search-active-filters.js', format: 'umd', name: 'DPSearchActiveFilters' }},
    // {input: 'node_modules/@rhd/dp-search/dp-search-app.js', output: { file: 'dist/js/@rhd/dp-search/dp-search-app.js', format: 'umd', name: 'DPSearchApp' }},
    // {input: 'node_modules/@rhd/dp-search/dp-search-box.js', output: { file: 'dist/js/@rhd/dp-search/dp-search-box.js', format: 'umd', name: 'DPSearchBox' }},
    // {input: 'node_modules/@rhd/dp-search/dp-search-filter-active-item.js', output: { file: 'dist/js/@rhd/dp-search/dp-search-filter-active-item.js', format: 'umd', name: 'DPSearchFilterActiveItem' }},
    // {input: 'node_modules/@rhd/dp-search/dp-search-filter-group.js', output: { file: 'dist/js/@rhd/dp-search/dp-search-filter-group.js', format: 'umd', name: 'DPSearchFilterGroup' }},
    // {input: 'node_modules/@rhd/dp-search/dp-search-filter-item.js', output: { file: 'dist/js/@rhd/dp-search/dp-search-filter-item.js', format: 'umd', name: 'DPSearchFilterItem' }},
    // {input: 'node_modules/@rhd/dp-search/dp-search-filters.js', output: { file: 'dist/js/@rhd/dp-search/dp-search-filters.js', format: 'umd', name: 'DPSearchFilters' }},
    // {input: 'node_modules/@rhd/dp-search/dp-search-modal-filters.js', output: { file: 'dist/js/@rhd/dp-search/dp-search-modal-filters.js', format: 'umd', name: 'DPSearchModalFilters' }},
    {input: 'node_modules/@rhd/dp-search/dp-search-onebox.js', output: { file: 'dist/js/rhd/dp-search/dp-search-onebox.js', format: 'umd', name: 'DPSearchOneBox' }},
    // {input: 'node_modules/@rhd/dp-search/dp-search-query.js', output: { file: 'dist/js/@rhd/dp-search/dp-search-query.js', format: 'umd', name: 'DPSearchQuery' }},
    // {input: 'node_modules/@rhd/dp-search/dp-search-result-count.js', output: { file: 'dist/js/@rhd/dp-search/dp-search-result-count.js', format: 'umd', name: 'DPSearchResultCount' }},
    // {input: 'node_modules/@rhd/dp-search/dp-search-result.js', output: { file: 'dist/js/@rhd/dp-search/dp-search-result.js', format: 'umd', name: 'DPSearchResult' }},
    // {input: 'node_modules/@rhd/dp-search/dp-search-results.js', output: { file: 'dist/js/@rhd/dp-search/dp-search-results.js', format: 'umd', name: 'DPSearchResults' }},
    // {input: 'node_modules/@rhd/dp-search/dp-search-sort-page.js', output: { file: 'dist/js/@rhd/dp-search/dp-search-sort-page.js', format: 'umd', name: 'DPSearchSortPage' }},
    // {input: 'node_modules/@rhd/dp-search/dp-search-url.js', output: { file: 'dist/js/@rhd/dp-search/dp-search-url.js', format: 'umd', name: 'DPSearchURL' }},
    {input: 'node_modules/@rhd/rhdp-downloads/rhdp-downloads.js', output: { file: 'dist/js/rhd/rhdp-downloads/rhdp-downloads.js', format: 'umd', name: 'RHDPDownloads'}},
    // {input: 'node_modules/@rhd/rhdp-downloads/rhdp-downloads-all-item.js', output: { file: 'dist/js/@rhd/rhdp-downloads/rhdp-downloads-all-item.js', format: 'umd', name: 'RHDPDownloadsAllItem' }},
    // {input: 'node_modules/@rhd/rhdp-downloads/rhdp-downloads-all.js', output: { file: 'dist/js/@rhd/rhdp-downloads/rhdp-downloads-all.js', format: 'umd', name: 'RHDPDownloadsAll' }},
    // {input: 'node_modules/@rhd/rhdp-downloads/rhdp-downloads-app.js', output: { file: 'dist/js/@rhd/rhdp-downloads/rhdp-downloads-app.js', format: 'umd', name: 'RHDPDownloadsApp' }},
    // {input: 'node_modules/@rhd/rhdp-downloads/rhdp-downloads-popular-product.js', output: { file: 'dist/js/@rhd/rhdp-downloads/rhdp-downloads-popular-product.js', format: 'umd', name: 'RHDPDownloadsPopularProduct' }},
    // {input: 'node_modules/@rhd/rhdp-downloads/rhdp-downloads-popular-products.js', output: { file: 'dist/js/@rhd/rhdp-downloads/rhdp-downloads-popular-products.js', format: 'umd', name: 'RHDPDownloadsPopularProducts' }},
    // {input: 'node_modules/@rhd/rhdp-downloads/rhdp-downloads-products.js', output: { file: 'dist/js/@rhd/rhdp-downloads/rhdp-downloads-products.js', format: 'umd', name: 'RHDPDownloadsProducts' }},
    {input: 'node_modules/@rhd/rhdp-projects/rhdp-project-wc.js', output: { file: 'dist/js/rhd/rhdp-projects/rhdp-project-wc.js', format: 'umd', name: 'RHDPProjectWC' }},
    // {input: 'node_modules/@rhd/rhdp-projects/rhdp-project-filter-box.js', output: { file: 'dist/js/@rhd/rhdp-projects/rhdp-project-filter-box.js', format: 'umd', name: 'RHDPProjectFilterBox' }},
    // {input: 'node_modules/@rhd/rhdp-projects/rhdp-project-item.js', output: { file: 'dist/js/@rhd/rhdp-projects/rhdp-project-item.js', format: 'umd', name: 'RHDPProjectItem' }},
    // {input: 'node_modules/@rhd/rhdp-projects/rhdp-project-query.js', output: { file: 'dist/js/@rhd/rhdp-projects/rhdp-project-query.js', format: 'umd', name: 'RHDPProjectQuery' }},
    // {input: 'node_modules/@rhd/rhdp-projects/rhdp-project-url.js', output: { file: 'dist/js/@rhd/rhdp-projects/rhdp-project-url.js', format: 'umd', name: 'RHDPProjectURL' }},
    // {input: 'node_modules/@rhd/rhdp-projects/rhdp-projects.js', output: { file: 'dist/js/@rhd/rhdp-projects/rhdp-projects.js', format: 'umd', name: 'RHDPProjects' }},
    {input: 'node_modules/@rhd/rhdp-search/rhdp-search.js', output: { file: 'dist/js/rhd/rhdp-search/rhdp-search.js', format: 'umd', name: 'RHDPSearch' }},
    // {input: 'node_modules/@rhd/rhdp-search/rhdp-search-app.js', output: { file: 'dist/js/@rhd/rhdp-search/rhdp-search-app.js', format: 'umd', name: 'RHDPSearchApp' }},
    // {input: 'node_modules/@rhd/rhdp-search/rhdp-search-box.js', output: { file: 'dist/js/@rhd/rhdp-search/rhdp-search-box.js', format: 'umd', name: 'RHDPSearchBox' }},
    // {input: 'node_modules/@rhd/rhdp-search/rhdp-search-filter-group.js', output: { file: 'dist/js/@rhd/rhdp-search/rhdp-search-filter-group.js', format: 'umd', name: 'RHDPSearchFilterGroup' }},
    // {input: 'node_modules/@rhd/rhdp-search/rhdp-search-filter-item.js', output: { file: 'dist/js/@rhd/rhdp-search/rhdp-search-filter-item.js', format: 'umd', name: 'RHDPSearchFilterItem' }},
    // {input: 'node_modules/@rhd/rhdp-search/rhdp-search-filters.js', output: { file: 'dist/js/@rhd/rhdp-search/rhdp-search-filters.js', format: 'umd', name: 'RHDPSearchFilters' }},
    // {input: 'node_modules/@rhd/rhdp-search/rhdp-search-onebox.js', output: { file: 'dist/js/@rhd/rhdp-search/rhdp-search-onebox.js', format: 'umd', name: 'RHDPSearchOneBox' }},
    // {input: 'node_modules/@rhd/rhdp-search/rhdp-search-query.js', output: { file: 'dist/js/@rhd/rhdp-search/rhdp-search-query.js', format: 'umd', name: 'RHDPSearchQuery' }},
    // {input: 'node_modules/@rhd/rhdp-search/rhdp-search-result-count.js', output: { file: 'dist/js/@rhd/rhdp-search/rhdp-search-result-count.js', format: 'umd', name: 'RHDPSearchResultCount' }},
    // {input: 'node_modules/@rhd/rhdp-search/rhdp-search-result.js', output: { file: 'dist/js/@rhd/rhdp-search/rhdp-search-result.js', format: 'umd', name: 'RHDPSearchResult' }},
    // {input: 'node_modules/@rhd/rhdp-search/rhdp-search-results.js', output: { file: 'dist/js/@rhd/rhdp-search/rhdp-search-results.js', format: 'umd', name: 'RHDPSearchResults' }},
    // {input: 'node_modules/@rhd/rhdp-search/rhdp-search-sort-page.js', output: { file: 'dist/js/@rhd/rhdp-search/rhdp-search-sort-page.js', format: 'umd', name: 'RHDPSearchSortPage' }},
    // {input: 'node_modules/@rhd/rhdp-search/rhdp-search-url.js', output: { file: 'dist/js/@rhd/rhdp-search/rhdp-search-url.js', format: 'umd', name: 'RHDPSearchURL' }},
    {input: 'node_modules/@rhd/dp-alert.js', output: { file: 'dist/js/rhd/dp-alert.js', format: 'umd', name: 'DPAlert' }},
    {input: 'node_modules/@rhd/dp-referrer.js', output: { file: 'dist/js/rhd/dp-referrer.js', format: 'umd', name: 'DPReferrer' }},
    //{input: 'node_modules/@rhd/rhdp-os-download.js', output: { file: 'dist/js/@rhd/rhdp-os-download.js', format: 'umd', name: 'RHDPOSDownload' }},
    {input: 'node_modules/@rhd/rhdp-thankyou-page.js', output: { file: 'dist/js/rhd/rhdp-thankyou-page.js', format: 'umd', name: 'RHDPThankYou'}},
    {input: 'node_modules/@rhd/rhdp-tryitnow.js', output: { file: 'dist/js/rhd/rhdp-tryitnow.js', format: 'umd', name: 'RHDPTryItNow' }}
]
