= Mobile
:awestruct-layout: solution-detail

== Header
Mobility has become a top priority for enterprises  as it offers the promise to drive innovation and streamline operational efficiency. Yet it's also creating a challenge for app developers  as mobile demands faster and more iterative development cycles, great user interface design and mobile experience, a fragmented market of emerging toolkits and frameworks, and integration with existing core systems, sometimes even legacy systems. However, a mobile app, by its nature, is a smaller, simpler software development project that is razor focused on a specific use case, and when done right leads to quick wins, business success, and great developer satisfaction.

Red Hat Mobile Application Platform offers developers an agile approach to developing, integrating, and deploying enterprise mobile applications, whether these are native, hybrid or web apps. Based on open technologies and standard toolkits, the platform can help you innovate fast, integrate securely, and deploy easily in continuous development cycles. It allows you to focus your mobile skills where they add most value and let the platform do the heavy-lifting on app integration, security, deployment, and management.


=== Solution Detail
Expand your development capability to include mobile. Build enterprise-grade mobile applications that securely integrate with backend systems with Red Hat’s Mobile Application Platform. Choose the toolkits, frameworks and development environment to build native mobile apps for iOS, Android and Windows Phone using native SDKs and hybrid apps using Apache Cordova. The platform also supports collaborative app development across multiple teams and projects giving you controlled access to backend developer services that can be easily discovered and reused across multiple projects. Control of security, user access, and backend connectivity is centralized on the platform across all app projects, giving greater visibility and resuability of developer components.  The platform includes an enterprise mobile backend-as-a-service (MBaaS)  offering seamless integration with enterprise systems and applications, including integration with JBoss FUSE. The public cloud or private Platform-as-a-Service (PaaS)-based architecture facilitates agile development and DevOps processes, uses RESTful APIs and microservices, and accelerates time-to-deployment..

[.solution-panel]
* Red Hat Mobile Application Platform embraces collaborative app development across multiple teams and projects and supports development “your way” with Bring-Your-Own-Tools (BYOT). It offers centralized control of security as well as API and Enterprise MBaaS integration plus a choice of cloud deployment options.
* Mobile Hybrid Tools enables you to quickly create link:/mobile/learn/#!query=cordova[Cordova]-based hybrid mobile applications. From this foundation you can customize the application by adding a range of Cordova plug-ins for accessing device hardware. You can also test your Cordova-based hybrid mobile applications without leaving the IDE using CordovaSim, a mobile application simulator.
* Data integration with link:/products/fuse[JBoss Fuse]. link:/products/fuse[Red Hat JBoss Fuse] is a small-footprint, open source Enterprise Service Bus (ESB). It delivers a robust, cost-effective, and open integration platform that lets enterprises easily connect their disparate applications, services, or devices in real time. An integrated enterprise is able to provide better products and services to its customers. A flexible architecture coupled with popular and proven integration tools enables link:/products/fuse[Red Hat JBoss Fuse] to provide integration everywhere.
* Node and Java script
* Connect your new Enterprise Mobile application with your existing back end services.
* Existing service integration such as Salesforce, SAP etc.
* Security Considerations
