= Mobile
:awestruct-layout: solution-detail

== Header
Extend your development capabilities to mobile. Build enterprise-grade mobile applications that securely integrate with backend systems with Red Hat’s Mobile Application Platform.
Choose the toolkits, frameworks and development environment to build native mobile apps for link:/mobile/learn/#!query=iOS[iOS], link:/mobile/learn/#!query=Android[Android] and Windows Phone using native SDKs and link:/mobile/learn/#!query=hybrid[hybrid] apps using link:/mobile/learn/!query=Cordova[Apache Cordova]. The platform includes an enterprise mobile backend-as-a-service (MBaaS)  offering seamless integration with enterprise systems and applications, including integration with link:/products/fuse[JBoss Fuse]. The MBaaS provides a place to write and run Cloud Code - small app services that offload logic or processes from a single mobile app and run them in the cloud. The platform also supports collaborative app development across multiple teams and projects giving you controlled access to backend developer services that can be easily discovered and reused across multiple projects. Control of security, user access, and backend connectivity is centralized on the platform across all app projects, giving greater visibility and reusability of developer components.  The public cloud or private Platform-as-a-Service (PaaS)-based architecture facilitates agile development and DevOps processes, uses RESTful APIs and microservices, and accelerates time-to-deployment..
