= Mobile
:awestruct-layout: solution-detail

== Header
As a developer working locally - you need a solid IDE that brings you tools that do the simple work for you - providing you things like visual editing, type checking, refactoring hints, and inline testing (unit and integration).

As your problem grows, you need solutions that may span teams or responsibilities.  Red Hat’s Enterprise Java products help in this space by helping teams manage dependencies as well as make the development of microservices across teams easier to coordinate and iterate independently.  Whether it is services or even data from different backend or 3rd party systems, Red Hat has proven products to make these challenging problems easier to manage.

Lastly, you need a solution that is going to run the same in production as it is locally and in your CI pipeline.  Not only does Red Hat provide support for all of the products, they also have products that help out with containers, runtimes, and a variety of load testing. Whether it is docker, Open Stack, or OpenJDK - Red Hat’s Enterprise Java products help you as you roll your product out - give you the developer less time in post-mortem and troubleshooting meetings.

=== Solution Detail
Expand your development capability to include mobile. Build enterprise-grade mobile applications that securely integrate with backend systems with Red Hat’s Mobile Application Platform. Choose the toolkits, frameworks and development environment to build native mobile apps for iOS, Android and Windows Phone using native SDKs and hybrid apps using link:/mobile/learn/#!query=cordova[Apache Cordova]. The platform also supports collaborative app development across multiple teams and projects giving you controlled access to backend developer services that can be easily discovered and reused across multiple projects. Control of security, user access, and backend connectivity is centralized on the platform across all app projects, giving greater visibility and resuability of developer components.  The platform includes an enterprise mobile backend-as-a-service (MBaaS)  offering seamless integration with enterprise systems and applications, including integration with JBoss FUSE. The public cloud or private Platform-as-a-Service (PaaS)-based architecture facilitates agile development and link:/solutions/devops/overview[DevOps] processes, uses RESTful APIs and microservices, and accelerates time-to-deployment..


* link:#[Red Hat Mobile Application Platform] embraces collaborative app development across multiple teams and projects and supports development “your way” with Bring-Your-Own-Tools (BYOT). It offers centralized control of security as well as API and Enterprise MBaaS integration plus a choice of cloud deployment options.
* Mobile Hybrid Tools enables you to quickly create link:/mobile/learn/#!query=cordova[Cordova]-based hybrid mobile applications. From this foundation you can customize the application by adding a range of Cordova plug-ins for accessing device hardware. You can also test your Cordova-based hybrid mobile applications without leaving the IDE using CordovaSim, a mobile application simulator.
* Data integration with link:/products/fuse[JBoss Fuse]. link:/products/fuse[Red Hat JBoss Fuse] is a small-footprint, open source Enterprise Service Bus (ESB). It delivers a robust, cost-effective, and open integration platform that lets enterprises easily connect their disparate applications, services, or devices in real time. An integrated enterprise is able to provide better products and services to its customers. A flexible architecture coupled with popular and proven integration tools enables link:/products/fuse[Red Hat JBoss Fuse] to provide integration everywhere.
* Node and Java script
* Connect your new Enterprise Mobile application with your existing back end services.
* Existing service integration such as Salesforce, SAP etc.
* Security Considerations
