<?php
/**
 * @file
 * Metatag integration for the metatag_dc module.
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function metatag_dc_ctools_plugin_api($owner, $api) {
  if ($owner == 'metatag' && $api == 'metatag') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_theme().
 */
function metatag_dc_theme() {
  $info['metatag_dc'] = array(
    'render element' => 'element',
  );

  return $info;
}

/**
 * Theme callback for a Dublin Core meta tag.
 */
function theme_metatag_dc($variables) {
  $element = &$variables['element'];
  $args = array(
    '#name' => 'name',
    '#schema' => 'schema',
    '#value' => 'content',
  );
  element_set_attributes($element, $args);
  unset($element['#value']);
  return theme('html_tag', $variables);
}
