<?php
/**
 * @file
 * Primary hook implementations.
 */

/**
 * Implements hook_menu().
 */
function metatag_importer_menu() {
  $items['admin/config/search/metatags/importer'] = array(
    'title' => 'Importer',
    'description' => 'Migrate settings and data from the Drupal 6 Nodewords module to the Drupal 7 Metatag module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('metatag_importer_form'),
    'access arguments' => array('administer meta tags.'),
    'file' => 'metatag_importer.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}
