name: Red Hat JBoss A-MQ 
abbreviated_name: JBoss A-MQ
tagline: A small footprint, high performance, open source messaging platform
current_version: 6.0.0.GA
documentation_path: JBoss_A-MQ
guides:
  API_Reference:
  Broker_Administration_Tutorials:
  Client_Connectivity_Guide:
  Configuring_Broker_Persistence:
  Connection_Reference:
  Console_Reference:
  Fault_Tolerant_Messaging:
  Glossary:
  Installation_Guide:
  Managing_and_Monitoring_a_Broker:
  Migration_Guide:
  Performance_Metrics_Reference:
  Release_Notes:
  Security_Guide:
  Tuning_Guide:
  Using_Networks_of_Brokers:
  Using_the_Management_Console:
  XML_Configuration_Reference:

