<?php

/**
 * @file
 * Functions to support theming in the RHD theme.
 */

function rhd_theme_suggestions_node_alter(array &$suggestions, array $variables) {
    $node = \Drupal::request()->attributes->get('node');
    if (!is_null($node) && method_exists($node, 'getType')) {
        $new_suggestion = 'node__' . $node->getType();

        if (!in_array($new_suggestion, $suggestions)) {
            $suggestions[] = $new_suggestion;
        }
    }
}
