:awestruct-interpolate: true

// CDK2 get started, where to go next and FAQ/Troubleshooting.

## Where to go next?

* link:https://access.redhat.com/documentation/en/red-hat-enterprise-linux-atomic-host/version-7/getting-started-with-container-development-kit/[Getting Started with Container Development Kit] -- contains detailed information on the components that make up the kit along with instructions on how to interact with containers in the container development environment.

* Container Development Guide (under development) -- Provides guidance for more advanced container development. It illustrates the different ways of creating containers to run with Docker, Kubernetes, Nulecule, Atomic and other container run-time environments.

* link:https://access.redhat.com/documentation/en/red-hat-enterprise-linux-atomic-host/version-7/getting-started-with-containers/[Red Hat Enterprise Linux Atomic Host 7 Getting Started with Containers] -- This document covers working with and deploying containers on both Red Hat Enterprise Linux and Red Hat Enterprise Linux Atomic Host. It also provides information on orchestrating multi-container environments with _kubernetes_.

* link:https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.2_Release_Notes/[Red Hat Enterprise Linux 7.2 Release Notes] -- includes information on recent updates to the link:https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.2_Release_Notes/atomic_host_and_containers.html[container tools included in Red Hat Enterprise Linux and Atomic Host].


## More Resources

### Become a Red Hat developer: developers.redhat.com

Red Hat delivers the resources and ecosystem of experts to help you be more productive and build great solutions.  Register for free at link:http://developers.redhat.com/[developers.redhat.com].

*Follow the Red Hat Developer Blog* +
link:http://developerblog.redhat.com/[]



## Faq section title
[[troubleshooting]]Troubleshooting and FAQ

## Faq section

. *How can I get the Red Hat Container Development Kit?*
+
You can download the Red Hat Container Development Kit from link:#{site.base_url}/[developers.redhat.com]. You will need to register, but registering is free.

. *Do I need a Red Hat Enterprise Linux subscription to run the Red Hat Container Development Kit?*
+
Yes. Since the kit includes a pre-built Red Hat Enterprise Linux virtual machine, you will need a subscription for Red Hat Enterprise Linux. See the next question for information on no-cost subscriptions for developers.

. *As a developer, how can I get a no-cost Red Hat Enterprise Linux subscription?*
+
When you register and download Red Hat Enterprise Linux Server through link:#{site.base_url}/[developers.redhat.com], a no-cost Red Hat Enterprise Linux Developer Suite subscription will be automatically added to your account.

. *How do I tell if there is a container image available that has a newer version of {tthw-langshort}*?
+
*How can I see what other container images are available?*
+
*I can't find the container mentioned in this tutorial, how can I tell if the name changed?*
+
To see what other containers are available in the Red Hat container registry, use one or more of the following searches:
+
[listing,subs="attributes"]
----
# docker search registry.access.redhat.com/rhscl
# docker search registry.access.redhat.com/openshift3
# docker search registry.access.redhat.com/rhel
# docker search registry.access.redhat.com/jboss
----

. *Where can I learn more about delivering applications with Linux containers?*
+
If you haven't already joined the link:http://developers.redhat.com/[Red Hat Developers program], sign up at link:http://developers.redhat.com/[developers.redhat.com]. Membership is free. +
link:https://access.redhat.com/articles/1483053[Recommended Practices for Container Development] and many other container articles are available from the link:https://access.redhat.com/[Red Hat Customer Portal].
+
If you are a Red Hat Technology Partner, visit the link:https://access.redhat.com/articles/1483053[Container Zone] at the link:http://connect.redhat.com/[Red Hat Connect for Technology Partners] web site.
