:awestruct-layout: product-get-started-multipath
:awestruct-interpolate: true

## Before You Begin section
You must have one of the following subscriptions in order to be able to use the CDK for Docker container application development:

* link:https://www.redhat.com/apps/store/developers/rhel_developer_suite.html[Red Hat Enterprise Linux Developer Suite]
* link:https://www.redhat.com/apps/store/developers/rhel_developer_support_professional.html[Red Hat Enterprise Linux Developer Support Professional]
* link:https://www.redhat.com/apps/store/developers/rhel_developer_support_enterprise.html[Red Hat Enterprise Linux Developer Support Enterprise]
* link:https://connect.redhat.com/zones/containers[Red Hat Connect for Technology Partners subscription]

[.callout-light]
*NOTE:* Red Hat may also occasionally provide a promotion which includes a no-charge version of the RHEL Developer Suite in order to test the CDK.

## Path Intro section
Get started building Ruby applications in docker containers on Red Hat Enterprise Linux in under 15 minutes.

## Prerequisites section title
Introduction and Prerequisites

## Prerequisites section
In this tutorial, you will learn how to start building Ruby applications in docker containers on Red Hat Enterprise Linux. In order to be able to build and run containers you will install `docker` on your Red Hat Enterprise Linux 7 system.

[*FIXME Confirm: I think docker is only available on RHEL 7 server. Docker is not available on desktop. I haven't tried workstation. I haven't changed the prerequisites to reflect that yet.*]

You will need a current Red Hat subscription that allows you to download software and updates from Red Hat. If you are interested in purchasing a Red Hat subscription for development, the link:https://www.redhat.com/apps/store/developers/rhel_developer_suite.html[Red Hat Developer Suite] is an affordable choice that includes Red Hat Enterprise Linux Server, Atomic Host, Red Hat Developer Toolset (DTS), and Red Hat Software Collections (RHSCL). For developer support with a guaranteed response time service-level agreement (SLA), Red Hat Developer Workstation Professional or Enterprise subscriptions are available.

If you don’t have a Red Hat Enterprise Linux subscription, you can try it for free. Get started with an evaluation at link:https://access.redhat.com/products/red-hat-enterprise-linux/evaluation[]. Select the _Red Hat Enterprise Linux Developer Workstation_ option to ensure your evaluation will include both RHSCL and DTS. See link:#{site.base_url}/products/rhel/get-started[ _Get Started with Red Hat Enterprise Linux_ ] for an overview of installing Red Hat Enterprise Linux for development.

If you encounter difficulties at any point, see <<troubleshooting,Troubleshooting and FAQ>>.

## Step1 Duration
5 minutes

## Step1 Title
Prepare your system

## Step2 Duration
5 minutes

## Step2 Title
Run your first container

## Step3 Duration
5 minutes

## Step3 Title
Build Hello World in a container

## Step1 Content

In this step, you will configure your system to build and run docker containers. In the process, you will add the necessary software repositories, verify that your system has a current Red Hat subscription, and is able to receive updates from Red Hat.

First, you will add two additional Red Hat software repositories that aren't enabled by default. Your system needs to be already registered with Red Hat. Instructions are provided for both the command line (CLI) and graphical user interface (GUI).

### Using the Red Hat Subscription Manager GUI

Red Hat Subscription Manager can be started from the _System Tools_ group of the _Applications_ menu. Alternatively, you can start it from the command prompt by typing `subscription-manager-gui`. +

Select _Repositories_ from the _System_ menu of the subscription manager. In the list of repositories, check the _Enabled_ column for _rhel-7-server-optional-rpms_ and _rhel-7-server-extras-rpms_. After clicking, it might take several seconds for the check mark to appear in the enabled column. If you are using the desktop or workstation version of Red Hat Enterprise Linux, the repositories will have _desktop_ or _workstation_ in the name instead of _server_. +

### Using subscription-manager from the command line

You can add or remove software repositories from the command line using the `subscription-manager` tool. Start a _Terminal_ window if you don't already have one open. Use `su` to become the root user.  Use `subscription-manager --list` option to to view the available software repositories.

[.code-block]
```
$ su -
# subscription-manager repos --list
```

Enable the two additional repositories. If you are using a desktop or workstation edition of Red Hat Enterprise Linux, change `-server-` to `-desktop-` or `-workstation-` in the following commands:

[.code-block]
```
# subscription-manager repos --enable rhel-7-server-extras-rpms
# subscription-manager repos --enable rhel-7-server-optional-rpms
```

### Install docker and start the docker daemon

In the next step you will:
. update your system with any available software updates
. install _docker_, and a few additional rpms using _yum_
. configure the _docker_ daemon to start at boot time
. start the _docker_ daemon


If you don't have a root _Terminal_ window open, start a _Terminal_ window and become the root user with `su`.

Now download and install any available updates by running `yum update`.  If updates are available, `yum` will list them and ask if it is OK to proceed.

[.code-block]
```
$ su -
# yum update
```

Install `docker` and necessary additional rpms:

[.code-block]
```
# yum install docker device-mapper-libs device-mapper-event-libs
```

Enable the docker daemon to start at boot time and start it now:

[.code-block]
```
# systemctl enable docker.service
# systemctl start docker.service
```

Now verify that the docker daemon is running:

[.code-block]
```
# systemctl status docker.service
```

Your system is now ready to build and run docker formatted containers. If you encounter difficulties at any point, see <<troubleshooting,Troubleshooting and FAQ>>.

## Step2 Content

This step will download and install Ruby using a container from the Red Hat container registry. Installing the Ruby container will make Ruby available for other containers on your system to use. Because containers run in isolated environments, your host system will not be altered by the installation. You must use `docker` commands to use or view the container's content.

The commands shown in this section can be used to download and install other containers, like application containers you build. Containers can specify that they require other containers to be installed, which can happen automatically. For example, you can specify in the `Dockerfile` that is used to describe and build your container that your application requires Ruby. Then, when someone installs your container, their system will automatically download the required Ruby container directly from the Red Hat container registry.

The Ruby container is part of Red Hat Software Collections, which provides the latest development technologies for Red Hat Enterprise Linux. Access to the Red Hat Software Collections (RHSCL) is included with many Red Hat Enterprise Linux (RHEL) subscriptions. For more information about which subscriptions include RHSCL, see link:https://access.redhat.com/solutions/472793[How to use Red Hat Software Collections (RHSCL) or Red Hat Developer Toolset (DTS)].

If you don't have a root _Terminal_ window open, start a _Terminal_ window and become the root user with `su`.

To download and install the Ruby container, use the following command:

`# docker pull registry.access.redhat.com/openshift3/ruby-20-rhel7`

The `docker images` command should show the container image that was installed as well as any others that are on your system.

`# docker images`

Now start a bash shell inside the Ruby container to have a look around. The shell prompt changes, which is an indication that you are typing at the shell inside the container. A `ps -ef` shows the only thing running inside the container is `bash` and `ps`. Type `exit` to leave the container's bash shell.

[.code-block]
```
# docker run -it openshift3/ruby-20-rhel7 /bin/bash
bash-4.2$ which ruby
/opt/rh/ruby200/root/usr/bin/ruby
bash-4.2$ pwd
/opt/app-root/src
bash-4.2$ ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
default      1     0  0 16:27 ?        00:00:00 bash
default     29     1  0 16:28 ?        00:00:00 ps -ef
bash-4.2$ exit
exit
```

The prior `docker run` command created a container to run your command, keep any state, and isolate it from the rest of the system. You can view the list of running containers with `docker ps`. To see all of the containers that have been created, including those that have exited, use `docker ps -a`.

You can restart the container that was created above with `docker start`. Containers are referred to by name. Docker will automatically generate a name if you don't provide one. Once the container has been restarted, `docker attach` will let you interact with the shell running inside of it.  See the following example:
 
[.code-block]
```
# docker ps -a
CONTAINER ID        IMAGE                             COMMAND                CREATED             STATUS                     PORTS               NAMES
a07bdee57770        openshift3/ruby-20-rhel7:latest   "container-entrypoin   2 minutes ago       Exited (0) 2 minutes ago                       pensive_payne       

# docker start pensive_payne
pensive_payne
# docker attach pensive_payne
```

At this point you are connected to the running shell inside the container. When you attach you won't see the command prompt, so hit Enter to get it to print another one.

[.code-block]
```

bash-4.2$ ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
default      1     0  0 16:32 ?        00:00:00 bash
default     28     1  0 16:33 ?        00:00:00 ps -ef
bash-4.2$ exit
```

Since bash was told to `exit`, the container will no longer be running. This can be verified with `docker ps -a`. Containers that are no longer needed can be cleaned up with `docker rm _<container-name>_`.

`docker rm pensive_payne`

To see what other containers are available in the Red Hat container registry, use one or more of the following searches:

[.code-block]
```
# docker search registry.access.redhat.com/openshift3
# docker search registry.access.redhat.com/rhscl
# docker search registry.access.redhat.com/jboss
# docker search registry.access.redhat.com/rhel
```

If you need help, see <<troubleshooting,Troubleshooting and FAQ>>.


## Step3 Content

In this step, you will create a tiny Hello World container that uses Ruby as a web server. Once created, the container can be run on other systems that have `docker` installed.  You will need to create several files in an empty directory using your favorite editor, including a `Dockerfile` that describes the container. You don't need to be running under the root user to create the files, but you will need root privileges to run the `docker` commands.

First, create an empty directory, and then create a file named `Dockerfile` with the following contents, but change the `MAINTAINER` line to have your name and email address:

.Dockerfile
----
FROM openshift3/ruby-20-rhel7

MAINTAINER Shadow Man "shadow-man@redhat.com"

EXPOSE 8000

COPY . /opt/app-root/src

CMD /bin/bash -c 'ruby hello-http.rb'
----

Create the file `hello-http.rb` with the following contents:

.hello-http.rb
----
require 'socket'

port = 8000
STDERR.print "Listening on port #{port}\n"

server = TCPServer.new('0.0.0.0', port)

loop do

  socket = server.accept
  request = socket.gets

  STDERR.puts request

  response = "Hello, Red Hat Developers World!\n"

  socket.print "HTTP/1.1 200 OK\r\n" +
               "Content-Type: text/plain\r\n" +
               "Connection: close\r\n"
  socket.print "\r\n"
  socket.print response

  socket.close
end
----


Now build the container image using `docker build`. You will need to be root using `su` or `sudo` in the directory you created that contains `Dockerfile` and `index.html`.

`# docker build -t _myname_/rubyweb .`


You can see the container image that was created using the following command:

[.code-block]
```
# docker images
```

Now run the container using `docker run`. The Ruby http.server module will create a tiny web server that listens on port 8000 inside the container.  The `run` command will map port 8000 on the host machine to port 8000 inside the container.

`# docker run -d -p 8000:8000 _myname_/rubyweb`

The run command returns a ID for the container that you can ignore.  To check that the container is running, use `docker ps`.  Take note of the name docker assigned to the running container.

[.code-block]
```
# docker ps
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS                              NAMES
c76ab9433737        myname/rubyweb      "container-entrypoin   40 seconds ago      Up 38 seconds       0.0.0.0:8000->8000/tcp, 8080/tcp   serene_pare         
```

Use `curl` to access the Ruby web server:

[.code-block]
```
# curl http://localhost:8000/
Hello, Red Hat Developers World!
```

To view the logs from the running container use `docker logs _<container-name>_`:

`# docker logs serene_pare`

When you are done, stop the running container with the following command using the name obtained from running `docker ps`:

[.code-block]
```
# docker kill serene_pare
```


## Where to go next?

* link:https://access.redhat.com/documentation/en/red-hat-enterprise-linux-atomic-host/version-7/getting-started-with-containers/[Red Hat Enterprise Linux Atomic Host 7 Getting Started with Containers] - This document covers working with and deploying containers on both Red Hat Enterprise Linux and Red Hat Enterprise Linux Atomic Host. It also provides information on orchestrating multi-container environments with _kubernetes_. See <<About 

* link:https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.2_Release_Notes/[Red Hat Enterprise Linux 7.2 Release Notes] - includes information on recent updates to the link:https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.2_Release_Notes/atomic_host_and_containers.html[container tools included in Red Hat Enterprise Linux and Atomic Host].

### About Red Hat Enterprise Linux Atomic Host

Atomic Host is specifically optimized for deploying Linux containers in environments like Infrastructure as a Service (IaaS) clouds. Atomic Host's minimal footprint contains only the software needed to efficiently host containers. Atomic Host isn't intended for software development activities as it doesn't include development tools or a graphical user interface.

During software development it is suggested that you use Red Hat Enterprise Linux, which is suitable for many purposes including desktop and server installations. You can build and run containers on Red Hat Enterprise Linux, see link:https://access.redhat.com/articles/881893[Get Started with Docker Formatted Container Images on Red Hat Systems]. The steps to build a container image that include your application can be automated with a Dockerfile. 

After your application is packaged in a container you should test it on Atomic Host to ensure that it is ready for deployment. In addition to minimized footprint, production environments built for running containers benefit from Atomic Host's enhanced security and atomic update and rollback capability.

Developers who are creating continuous integration/continuous delivery (CI/CD) environments will want to consider containers deployed on Atomic Host. This allows test environments to be quickly created while minimizing system resource requirements.


## More Resources

### Become a Red Hat developer: developers.redhat.com

Red Hat delivers the resources and ecosystem of experts to help you be more productive and build great solutions.  Register for free at link:http://developers.redhat.com/[developers.redhat.com].

*Follow the Red Hat Developer Blog* +
link:http://developerblog.redhat.com/[]



## Faq section title
[[troubleshooting]]Troubleshooting and FAQ

## Faq section
. My system is unable to download updates from Red Hat.
+
Your system must be registered with Red Hat using `subscription-manager register`. You need to have a current Red Hat subscription or an evaluation.

. I don't have a current Red Hat subscription, can I get an evaluation?
+
If you don’t have a Red Hat Enterprise Linux subscription, you can try it for free. Get started with an evaluation at link:https://access.redhat.com/products/red-hat-enterprise-linux/evaluation[]. Select the _Red Hat Enterprise Linux Developer Workstation_ option to ensure your evaluation will include both RHSCL and DTS. See link:#{site.base_url}/products/rhel/get-started[ _Get Started with Red Hat Enterprise Linux_ ] for an overview of installing Red Hat Enterprise Linux for development.
+
. How do I tell there is a container image available that has a newer version of Ruby?
+
How can I see what other container images are available?
+
I can't find the container mentioned in this tutorial, how can I tell if the name changed?
+
To see what other containers are available in the Red Hat container registry, use one or more of the following searches:
+
[.code-block]
```
# docker search registry.access.redhat.com/openshift3
# docker search registry.access.redhat.com/rhscl
# docker search registry.access.redhat.com/rhel
# docker search registry.access.redhat.com/jboss
```
. Can I run and build docker containers on Red Hat Enterprise Linux?
+
Red Hat Enterprise Linux includes docker, but it is not installed by default. See link:https://access.redhat.com/articles/881893#get[Getting Docker on RHEL 7] in the article link:https://access.redhat.com/articles/881893[Get Started with Docker Formatted Container Images on Red Hat Systems].
. Where can I learn more about delivering applications with Linux containers?
+
If you haven't already joined the link:http://developers.redhat.com/[Red Hat Developers program], sign up at link:http://developers.redhat.com/[developers.redhat.com]. Membership is free.+
link:https://access.redhat.com/articles/1483053[Recommended Practices for Container Development] and many other container articles are available from the link:https://access.redhat.com/[Red Hat Customer Portal].+
If you are a Red Hat Technology Partner, visit the link:https://access.redhat.com/articles/1483053[Container Zone] at the link:http://connect.redhat.com/[Red Hat Connect for Technology Partners] web site.
. `yum` is unable to find the `docker` rpm.
+
[*FIXME - Confirm: I think docker is only available for RHEL 7 server*]