:awestruct-layout: product-updates
:awestruct-interpolate: true
:leveloffset: 1
:awestruct-description: "Get updates of the the Red Hat Container Development Kit (CDK)"

=== The Red Hat Container Development Kit 2.2 (CDK 2.2) is now available
September 2016

The following features were added with Red Hat Container Development Kit 2.2:

_Proxy Connections Are Supported both for HTTP and HTTPS_ - The Container Development Environment provided by CDK 2.2 now supports connecting to the Internet through proxy servers — both HTTP and HTTPS configurations. This is available to all services including Openshift Enterprise, Kubernetes, and Docker.

_Unified Vagrantfiles for All Hypervisors_ - Vagrantfiles distributed as a part of the Red Hat Container Tools ZIP file have been unified to work with all supported hypervisors.

_Vagrant-sshfs Plugin Is Now Used by Default JBoss Developer Studio_ - There is no longer a need for separate Vagrantfiles.

_Vagrant-service-manager Plugin Can Install Client Binaries for OpenShift, Docker, and Kubernetes_ - Client binaries for the user’s host system, which can be used to interact with services running inside the Container Development Environment, can now be installed using the Vagrant-service-manager' plugin.

=== The Red Hat Container Development Kit 2.1 (CDK 2.1)
June 2016

The new features offered by Red Hat Container Development Kit 2.1 include.

_OpenShift Enterprise 3.2_ - OpenShift Enterprise provided by the Container Development Environment has been upgraded to version 3.2. Red Hat Container Development Kit 2.1 offers a simple way to set up the OpenShift Enterprise Platform as a Service (PaaS), which extends the functionality of the Docker service and the Kubernetes container orchestration tool.

_Hyper-V Tech Preview Added_ - A Container Development Kit Vagrant box is now available for the Hyper-V hypervisor on Microsoft Windows.

_Reduced Size of Vagrant Boxes_ - The size of the Vagrant Boxes has been reduced by approximately 150 MB compared to Container Development Kit 2.0.

_Persistent Volumes for Storing Data between Restarts_ - Users can now use persistent volumes in order to preserve data between restarts of pods, OpenShift, or even the whole virtual machine that provides the container development environment.

_OpenShift Registry Available on Host System_ - Users can now use the internal container-image registry provided by OpenShift as a stand-alone registry for docker-formatted container images on the host workstation.

=== The Red Hat Container Development Kit 2 (CDK 2) is now available for beta testing!
December 2015

The beta release of the Red Hat Container Development Kit 2 enables developers to take advantage of pre-configured images and tools to accelerate the development of container-based applications that can be deployed across Red Hat’s portfolio of container hosts and platforms - including OpenShift Enterprise 3 - from the comfort of your own laptop.

New components in CDK 2 include:

* Support for the Nulecule specification.  What is Nulecule?  Nulecule defines a pattern and model for packaging complex multi-container applications, referencing all their dependencies, including orchestration metadata in a container image for building, deploying, monitoring, and active management.
* Atomic App - Red Hat’s reference implementation of the Nulecule Specification. It can be used to accelerate the development of container-based applications. Atomic App itself is packaged and is included as a container.
* Image Factory (imagefactory-v2c) - a tool to accelerate the importing and conversion of disk images (e.g. virtual machine images) into Docker base images - complete with appropriate metadata.
* Vagrant plug-in for Eclipse Docker Tooling - allows users to connect the Eclipse Docker tooling to the Docker daemon running in your CDK VM.

Hypervisor support includes Vagrantfiles for KVM, VirtualBox, and now with CDK 2, VMware.

Red Hat Software Collections are available as container images for use with the Red Hat Container Development Kit via the Red Hat Registry.  Red Hat Software Collections are inclusive of the latest stable versions of web development tools, dynamic languages, and open source databases.

Create your own private container registry with available tools.

See the link:#{site.base_url}/products/cdk/get-started[Get Started] to make your way into Docker containers.

=== Red Hat introduces CDK for easy Docker app development
March 2015

The initial version of CDK was the first to set up a Docker container development environment for Windows, MacOS, and Linux.  Supported hypervisors were Virtualbox and KVM.  Given the latest enhancements, developers are encouraged to use the CDK 2 beta (above).
