:awestruct-layout: product-overview
:awestruct-status: yellow
:awestruct-interpolate: true
:leveloffset: 1
:awestruct-description: "Introduction to Red Hat Developer Toolset (DTS) for C/C++ developers"
:title: Red Hat Developer Toolset

== Overview

Red Hat Developer Toolset delivers the latest stable versions of essential C and C++ and supporting development tools to enhance developer productivity and improve deployment times. Available via most Red Hat Enterprise Linux subscriptions, Red Hat Developer Toolset makes it possible to compile once and deploy to multiple versions of Red Hat Enterprise Linux. Components include Eclipse, GCC, GDB, Git, SystemTap, OProfile, and more.

*Red Hat Developer Toolset has these major features:*

* A full development toolset of GCC (C, C++, and Fortran), Eclipse IDE, GDB, SystemTap, Valgrind, OProfile, and much more.  
* Updated yearly - available for both Red Hat Enterprise Linux 6 and 7.
* Includes Red Hat developer support - each annual update is supported for 2 years.
* Upwards compatible compiling:  compile on Red Hat Enterprise Linux 6, deploy on either Red Hat Enterprise Linux 6 or 7.
* Red Hat Developer Toolset also delivers the latest stable tools faster to help developers more quickly create, diagnose, and debug applications in development.

When installed, Red Hat Developer Toolset does not replace the default system tools included with Red Hat Enterprise Linux 6 or 7. Instead, a parallel set of newer tools is provided for optional use by developers. The default compiler and debugger, for example, remain those in the base Red Hat Enterprise Linux system.

Read the https://access.redhat.com/sites/default/files/pages/attachments/rhel_developer_toolset_techbrief_11982507-inc0194651_v1_1014mm_a4_web_0.pdf[feature brief] for Red Hat Developer Toolset.
