:awestruct-layout: product-updates
:awestruct-interpolate: true
:leveloffset: 1
:awestruct-description: "Get updates of the Red Hat Developer Toolset (DTS) for C/C++ developers"

= Red Hat Developer Toolset 6

Red Hat Developer Toolset 6 is now available with updated versions of the GNU Compiler Collection, the Eclipse IDE, and number of updates to toolchain components and performance tools such as Dynist and SystemTap. Red Hat Developer Toolset delivers the latest stable versions of the C, C++, and Fortran compilers and supporting development tools to enhance developer productivity and improve deployment times.


== New Developer Toolset 6 platform coverage includes:
* Red Hat Enterprise Linux for Power (both BE and LE)
* Red Hat Enterprise Linux for z Systems
* Red Hat Enterprise Linux Server for ARM Developer Preview.


== New Developer Toolset 6 features are:
* GNU Compiler Collection (GCC) 6.2.1
* GNU Project Debugger (GDB) 7.12
* Eclipse 4.6.1 (now a separately installable item)
* Git 2.9.3
* binutils 2.27
* elfutils 0.167
* Valgrind 3.12
* Dyninst 9.2.0
* strace 4.12
* SystemTap 3.0


*NOTE:  There was no Developer Toolset 5. We skipped this number so that the Developer Toolset version number would match the GCC version number.*


= Red Hat Developer Toolset 4.1

Red Hat Developer Toolset 4.1 is now available with updated versions of the GNU Compiler Collection, the Eclipse IDE, and number of updates to toolchain components and performance tools such as Dynist and SystemTap. Red Hat Developer Toolset delivers the latest stable versions of the C, C++, and Fortran compilers and supporting development tools to enhance developer productivity and improve deployment times.


=== Release highlights

* *GNU Compiler Collection (GCC) 5.3* +
Developers now have the latest stable version of GCC, 5.3, for application development on Red Hat Enterprise Linux 6 and 7. C, C++, and Fortran developers can take advantage of the latest GCC compiler features while utilizing a fully supported version of the GCC suite.

* *Eclipse 4.5.2 with C/{cpp} Development Tooling* +
Eclipse is updated to version 4.5.2, the Mars.2 release. Eclipse is an open development platform comprised of extensible frameworks, tools and runtimes for building, deploying, and managing software across the development lifecycle. Using various included plug-ins, it can be used to develop applications in Java, C, C++, Python, Fortran and other programming languages.

* *GNU Project Debugger (GDB) 7.11, Dynist 9.1, SystemTap 2.9, and more* +
With version 4.1 of the Developer Tools, Red Hat Enterprise Linux developers have the latest stable versions of C/C++ debugging and performance analysis tools available as supported packages. Other updates include valgrind 3.11, binutils 2.25, and elfutils 0.166

For a complete list of what is included, see the link:https://access.redhat.com/documentation/en-US/Red_Hat_Developer_Toolset/4-Beta/html-single/4.1_Release_Notes/index.html[Release Notes] and link:https://access.redhat.com/documentation/en-US/Red_Hat_Developer_Toolset/4-Beta/html-single/User_Guide/index.html[User Guide] +.


=== Container images available

For building, debugging, and analyzing container-based applications, Red Hat Developer Toolset 4.1 components are also provided as docker-formatted container images from the Red Hat Container Registry. Container images are available with the C, C++, or Fortran compilers and the debugging/analysis tools: dyninst, gdb, oprofile, systemtap, and valgrind.

For more information, see link:https://access.redhat.com/documentation/en-US/Red_Hat_Developer_Toolset/4-Beta/html/User_Guide/sect-Red_Hat_Developer_Toolset-Container-Images.html[Using Red Hat Developer Toolset Container Images].


