:awestruct-layout: solution-adoption
:awestruct-interpolate: true
:page-drupal_type: rhd_solution_overview

=== [[accelerate]]Accelerate
==== [[accelerate-development]]Accelerate Development
Don't let a complex, inflexible, proprietary application infrastructure hinder your developers' productivity. Create applications faster. Deploy them across on-premise, mobile, and cloud environments. And increase application performance.

With Red Hat Enterprise Java Solutions, you have everything you need to build, run, and manage services for Java EE6 enterprise applications.  Whether you are building an HTML5 mobile product, a highly transactional, distributed application - or anything in between - Red Hat Enterprise Java Solutions have you covered.

[[developer-studio]]Developer IDEs-such as link:http://www.jboss.org/products/devstudio/overview/[JBoss Developer Studio] help developers visualize, refactor, and test their code locally.

[[eap]]JBoss Enterprise Application Platorm (EAP) is a Java EE 6 application server, providing developers not only with all of the necessary plumbing to quickly build enterprise products, but also a light and fast enough platform to run on their laptops allowing rapid development and testing.

[[feedhenry]]The RedHat FeedHenry 3 Mobile Application Platform brings agility, visibility and efficiency to enterprise mobility. This Mobile App Platform embraces collaborative product development across multiple teams and projects and supports development "your way" with  Bring-Your-Own-Tools (BYOT). All of this designed to help you buid your products faster and meet the needs of your mobile customers.

[[xpaas]]JBoss xPaaS services provide the powerful capabilities of JBoss Middleware as cloud based services on OpenShift.

Developers can build applications, integrate with other systems, orchestrate using rules and processes, and then deploy across hybrid environments.
[[openshift]]OpenShift 3 is built around a core of application containers powered by Docker, with orchestration and management provided by Kubernetes, on a foundation of Atomic and Enterprise Linux. Origin Milestone 5 (M5) is the upstream community project that brings it all together along with extensions, to accelerate application development and deployment.

===== Get Started
|=======
|Get Started with link:http://www.jboss.org/products/devstudio/get-started/#!project=devstudio[JBoss Developer Studio]
|Watch the link:http://www.jboss.org/video/vimeo/95462201[Architecture Overview of JBoss Enterprise Application Platform]
|Get Started with link:http://www.jboss.org/products/eap/get-started/#!project=eap[JBoss Enterprise Application Platform]
|Get Started with link:http://www.jboss.org/video/vimeo/44390131[JBoss EAP6 on OpenShift with JBoss Developer Studio]
|Introduction to link:http://www.feedhenry.com/developer/[FeedHenry]
|=======

==== [[simplify-deployment]]Simplify Deployment
[[cloud]][[hybrid]]To deploy seamlessly across on-premise, private-cloud, and public-cloud environments, an application must allow for multiple deployment options from the same code base.

Red Hat JBoss Enterprise Application Platform for xPaaS extends Java&trade; EE application platform capabilities to OpenShift by Red Hat's Platform-as-a-Service (PaaS) solutions to let you do just that. Don't start over from scratch or compromise on enterprise performance. Deploy or move your applications to the cloud quickly, with the simplicity of PaaS.

===== Get Started
|=======
|Introduction to link:https://www.openshift.com/xpaas[xPaas]
|Introduction to link:http://www.openshift.org/#v3[OpenShift]
|=======

==== [[accelerate-performance]] Accelerate Product Performance
[[performance]][[jdg]]As transactions from your popular applications grow, data can be hard to access in a timely manner. You could spend more money on additional database licenses or an army of database administrators. Or, you could use Red Hat JBoss Data Grid, which lets you:
Achieve 3-times-faster application performance.
Effortlessly process huge volumes of data.
Scale for high-transaction throughput.
Concentrate on coding web applications instead of solving scaling problems.

[[thermostat]][[testing]]The best time to figure out how to increase product performance is before you need it.  link:http://icedtea.classpath.org/wiki/Thermostat[Thermostat], part of link:https://access.redhat.com/documentation/en-US/Red_Hat_Developer_Toolset/1/html/Software_Collections_Guide/[Red Hat Software Collections], is an instrumentation tool for the Hotspot JVM, with support for monitoring multiple JVM instances on multiple hosts, optionally in a cloud environment.  Using Thermostat, you can find the bottlenecks in your product and tune it for performance.

[[openjdk]][[shenandoah]]To drive product performance, we need an enterprise class VM to run them on.  As our products grow and we scale to large systems, we need a performant garbage collector to avoid 'Stop the World'.  Shenandoah is Red Hat's ultra high performance garbage collector for OpenJDK.

===== Get Started
|=======
|Watch a link:#{site.base_url}/video/vimeo/95291413[JBoss Data Grid Overview]
|Learn more about link:#{site.base_url}/video/vimeo/28201194[Leveraging JBoss Data Grid as a local cache]
|Learn more on link:https://developer.jboss.org/wiki/SharingHTTPSessionsWithInfinispan[Sharing HTTPS Sessions using JBoss Data Grid]
|Get Started with link:http://icedtea.classpath.org/wiki/Thermostat/UserGuide[Thermostat]
|Get Started with link:http://openjdk.java.net/[OpenJDK]
|Learn More about link:http://planet.jboss.org/post/rhel_openjdk_performance_tuning[Tuning OpenJDK]
|Learn More about link:http://jaxenter.com/red-hat-lifts-lid-on-high-performance-garbage-collector-107419.html[Shenandoah]
|Read the link:http://openjdk.java.net/jeps/189[JEP for Shenandoah]
|=======


'''

=== [[integrate]]Integrate
==== [[patterns]]Pattern Based Integrations
Systems integrations is a challenge for all enterprise systems. How do we connect our new applications with our old; how do we connect different teams to create cumulative products; how do we manage all of this?

No reason to reinvent the world.  There are well known and defined link:http://www.enterpriseintegrationpatterns.com/[Enterprise Integration Patterns].  As developers, we need tools that make using these patterns easy and predictable so we can continue delivering business value.

Using Apache Camel and JBoss Fuse, you will be able to quickly, easily, and confidently integrate your legacy systems.

===== Get Started
|=======
|Getting Started with link:http://ait2.iit.uni-miskolc.hu/oktatas/lib/exe/fetch.php?id=tanszek%3Aoktatas%3Ainformacios_rendszerek_integralasa%3Ainformatikai_rendszerek_epitese&cache=cache&media=tanszek:oktatas:informacios_rendszerek_integralasa:camelinaction.pdf[Apache Camel - free eBook]
| Watch link:http://www.jboss.org/video/vimeo/77941255[Getting Started with JBoss Fuse Works]
|Watch link:http://www.jboss.org/video/vimeo/84674508[Loan Broker Demo]
|Get started with an link:https://github.com/FuseByExample/HelloCamel[Apache Camel OSGi example]
|Get Started with link:https://www.jboss.org/products/fuse/resources/#demos[Fuse Demos]
|=======

==== [[connectors]]Multiple Connectors
Most enterprise systems are not simple or easy to integrate.  You have some mainframe systems, some batch systems, maybe even some systems in different technology stacks.  Not to mention the newer systems with a whole variety of integration points and third party systems.  How to integrate all of those easily and securely?  Use the deep set of connectors in JBoss Fuse to help you.

A Fuse Connector provides easy integration of your applications inside the Enterprise as well as externally by providing a uniform endpoint interface and acting as connectors to all other systems.

===== Get Started
|======
|Learn about link:#{site.base_url}/products/fuse/connectors/[Available Connectors]
|Get Started with the link:http://wei-meilin.blogspot.tw/2014/11/jboss-fuse-connecting-to-twitter-and.html[Twitter Connector Example]
|======

==== [[data]]Connecting & Securing Disparate Data
Data is always a challenge.  Whether it is just different teams iterating at different cadences with different data needs or different systems with a need for a master data set that doesn’t exist - or anything in between - JBoss Data Services has you covered.  Do you find yourself writing code to process those mainframe data reports, look up the data in your database, and combine with a query to a rest service?  All of that code is fragile - any number of data changes and you are broke.  Why suffer when you can introduce a simple abstraction tier - without code - to manage this for you?

JBoss Data Virtualization is a data integration solution that sits in front of multiple data sources and allows them to be treated as a single source, delivering the right data, in the required form, at the right time to any application and/or user.  Additionally, developers can build powerful transformations and relationships in their IDE using common metadata and semantics.  Once those models are ready for delivery, you can apply role based data access, security and auditing policies regardless of data source types like a data firewall.

===== Get Started
|======
|Learn more about link:https://planet.jboss.org/post/data_virtualization_primer_the_concepts[Data Virtualization Concepts]
|Get Started with link:https://github.com/teiid/teiid-quickstarts/tree/master/webservices-as-a-datasource[Services as a Datasource]
|Learn more about link:https://planet.jboss.org/post/moving_to_data_services_for_microservices[Moving Data to MicroServices]
|======

'''

=== [[automate]]Automate
==== [[business-rules]]Business Rule Management
Business rules management (BRM) technologies have emerged as a powerful approach to building agile business solutions, fostering true collaboration between business and IT stakeholders. Instead of having these business rules written in code that has a longer lifecycle for change and a different skillset, it would be ideal to have these rules outside of the code base in a platform that allowed IT and business collaboration, without exposing risk from untesting scenarios.

A platform that integrates process and decision management, coupled with simple tools for both business experts and developers, makes it easy for project stakeholders to collaborate.

JBoss BRM provides a suite that is supports collaboration between developers and business stake holders, allowing a safe environment for rapid adjustment of business critical rules.

===== Get Started
|======
|Get Started with link:https://github.com/eschabell/brms-coolstore-demo[BRMS Cool Store Demo]
|Start Learning with link:http://bpmworkshop-onthe.rhcloud.com/workshops.html#/[Online BRMS Workshop]
|Advance your rules with link:http://www.schabell.org/search/label/Tips%26Tricks[Business Rules Tips and Tricks]
|======

==== [[complex-event]]Complex Event Processing
Managing and responding to events is critical to business functionality.  Get a payment to process?  Well process it.  Schedule a package for delivery?  Well, find a truck for it.

But then reality hits.  What if you receive two payments from different locations in the world in a small window - is it fraud detection?  What if the package you are shipping is temperature sensitive, it is the middle of summer, and not only is there construction but there is a major accident on a critical highway?

Complex events are the reality of the world and the handling of them separates the leaders from the rest of the pack.

Complex event processing (CEP) searches for these event patterns and executes business rules that make active decisions in response to those events.

Using event-based logic delivers in-the-moment decision-making and adds business value.

===== Get Started
|======
|Get Started with link:https://github.com/jboss-developer/jboss-brms-quickstarts/tree/6.1.x/helloworld-cep[Hello World CEP Example]
|Learn with use cases with link:#{site.base_url}/video/vimeo/30743896[CEP with JBoss]
|======

==== [[bpm]]Business Process Management
Change is the new constant and agile business applications are key to remaining competitive. Let the people who understand the business make and change the rules — without involving IT.

Business process management (BPM) has emerged as a powerful approach to building agile business solutions, fostering true collaboration between business and IT stakeholders.  Whether you are modeling your call center flow or the build out of your inventory check system, BPM is there for you.

A platform that integrates this business process and decision management, coupled with simple tools for both business experts and developers to work and validate makes it easy for project stakeholders to collaborate.

===== Get Started
|======
|Get Started with link:http://planet.jboss.org/post/modern_bpm_data_integration_with_jboss_bpm_travel_agency_demo[Travel Agency Demo with BPM, code and videos]
|Start Learning with link:http://bpmworkshop-onthe.rhcloud.com/workshops.html#/[Online BPM Workshop]
|Keep Learning with link:http://www.schabell.org/2014/07/redhat-jboss-bpmsuite-product-demos-6.0.2-updated.html[More BPM code examples]
|======

==== [[bam]]Business Activity Management
Enterprises run on business processes.  Once these business processes are deployed, organizations need to monitor how they are impacting their business. Business Activity Monitoring (BAM) is a term commonly used for monitoring BPM and other systems generating business events and data within an enterprise. Red Hat JBoss BPM Suite includes BAM capabilities that focus on the graphical presentation of business and process metrics along with the ability to flexibly draw data from a variety of sources.

It is not unusual for Red Hat JBoss BPM Suite developers to get started with BAM using data drawn from the BPM execution engine. However, when monitoring the impact of business processes, access to data via JDBC data sources and flat files, can be tremendously valuable and is a capability built into Red Hat JBoss BPM Suite business activity monitoring.

===== Get Started
|======
|Get Started with a sample link:https://github.com/eschabell/bpms-bam-dashboard[BAM Dashboard]
|Learn More about link:http://www.schabell.org/2014/03/redhat-jboss-bpmsuite-change-bam-permissions.html[Setting BAM Permissions]
|Learn More about how link:https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_BPM_Suite/6.0/html/Getting_Started_Guide/chap-BAM.html[BPM and BAM work together]
|======
