:awestruct-layout: solution-get-started

Delivering world class enterprise products can be challenging. As our product grows over years, the number of users along with data growth creates performance challenges. As products grow, they need deeper, richer data along with connections throughout the enterprise and partners. Teams grow and we have various business services being delivered by different groups that we need to coordinate. We also need to be able to more dynamically deliver decisions and react to changing events.

Development teams are looking to build better applications, learn, and adapt as quickly as possible. Red Hat’s vision and offerings are designed with that in mind. Red Hat provides consistent, repeatable, predictable solutions that remove the noise from developing products and allow teams to build, validate, and learn quicker.

You will find tools to help you be productive including OpenJDK, performance tools such as Thermostat, JBoss EAP, OpenShift cloud-based deployments, data grid, Apache HTTP and Tomcat, integration solutions, messaging, business rules engines, workflow and BPM solutions, and of course a developer IDE. (Note: I lost formatting in this ticket - this paragraph is currently on the Enterprise Java Overview page, if you'd like to reference that for links etc.

Red Hat Enterprise Java Solutions have industry standard, open source, supported products to help you with these challenges and allow you to focus on the more interesting, creative work.

<<IMAGE HERE>>

== First Section
=== Accelerate
Accelerate Development

Simplify Deployment - on premise and in the cloud

Accelerate product performance

== Second Section
=== Integrate
Pattern Based Integrations

Multiple Connectors

Connecting, securing, and insulating disparate datasets

== Third Section
=== Automate
Business Rule Management

Complex Event Processing

Business Process Management

Business Activity Monitoring

