= Enterprise Java
:awestruct-layout: solution-detail

== Header
Don’t let the weight of the enterprise slow down your product delivery.

We live in a connected, software based world. As we try and bring valuable products to our end users, the weight of the ‘enterprise’ can inadvertently get in the way. Challenges between which frameworks to use, which libraries are safe, how do we use a consistent set of tools to avoid ‘it works on my laptop.’

Learn how Red Hat provides products that helps the enterprise accelerate, integrate, and automate the delivery of the products they build.

For enterprise engineers who must rapidly build new mission-critical products while maintaining legacy solutions to ensure their organization's success, Red Hat enables enterprises to innovate faster, in a smarter way. That's what we call enlightened innovation.

== Left Section
=== Accelerate
Whether you are looking to make your current applications respond quicker or you are looking be able to deliver products more quickly, Red Hat Enterprise Java products like the JBoss Enterprise Application Platform and JBoss Data Grid can easily assist without getting in the way.

link:/enterprise-java/get-started/accelerate[Learn more on how Red Hat Enterprise Java solutions can help you accelerate product delivery]

== Middle Section
=== Integrate 
Looking to integrate with legacy back-end systems or across third party platforms? JBoss Fuse along with JBoss A-MQ can help simplify the connectivity, discovery, and orchestration challenges that enterprise developers face. JBoss Data Virtualization makes managing the integration of your disparate data sources simple.

link:/enterprise-java/get-started/integrate[Learn more on how Red Hat Enterprise Java solutions can help you with integration challenges]

== Right Section
=== Automate
Business processes can change frequently, leading to ‘the code’ being the bottleneck. Developers building products that hinge on changing business rules - like sales promotions or escalation procedures for events - can simplify their world while satisfying the need to move faster by automating those business rules using JBoss BRMS and JBoss jBPM.

link:/enterprise-java/get-started/automate[Learn more on how Red Hat Enterprise Java solutions can help you automate business processes]


