= Enterprise Java
:awestruct-layout: solution-detail

== Header
Development teams are looking to build better applications, learn, and adapt as quickly as possible. Red Hat's vision and offerings are designed with that in mind. Red Hat can provide with consistent, repeatable, predictable solutions that remove the noise from developing products and allow teams to build, validate, and learn quicker.


You will find tools to help you be productive including link:http://openjdk.java.net/[OpenJDK], performance tools such as link:http://icedtea.classpath.org/thermostat/[Thermostat], link:/products/eap[JBoss EAP], link:/products/openshift[OpenShift] cloud-based deployments, link:/products/data-grid/[data grid], link:/products/webserver[Apache HTTP and Tomcat], link:/products/fuse[integration solutions], link:/products/amq[messaging], link:/products/brms[business rules engines], link:/products/bpmsuite[workflow and BPM] solutions, and of course a developer link:/products/devstudio[IDE].

== Left Section
=== Accelerate
Don't let a complex, inflexible, proprietary application infrastructure hinder your developers' productivity. Create applications faster. Deploy them across on-premise, mobile, and cloud environments. And increase application performance.

link:/enterprise-java/get-started/accelerate[Learn more ...]

== Middle Section
=== Integrate 
Integration within and beyond the datacenter doesn't have to be complex or expensive. Lightweight, easy-to-use, embeddable, cloud-ready integration helps integrate all enterprise assets, everywhere.

link:/enterprise-java/get-started/integrate[Learn more ...]

== Right Section
=== Automate
Business process management (BPM) and business rules management (BRM) technologies have emerged as a powerful approach to building agile applications.  Abstracting business logic, coupled with simple tools makes it easy for project stakeholders to collaborate.

link:/enterprise-java/get-started/automate[Learn more ...]


