<?php

/**
 * @file
 * Contains rhd_microsite.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function rhd_microsite_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the rhd_microsite module.
    case 'help.page.rhd_microsite':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('RHDP rhd_microsite Content Type') . '</p>';
      return $output;

    default:
  }
}
