<?php

/**
* @file
* Contains rhd_admin.module.
*
*/
/**
 * Implements hook_form_alter().
 */
function rhd_admin_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  /* @var Drupal\Core\Entity\FieldableEntityInterface $entity */
  $formObject = $form_state->getFormObject();
  if ($formObject instanceof \Drupal\Core\Entity\EntityFormInterface) {
    $entity = $formObject->getEntity();
    if ($entity->getEntityTypeId() === 'node') {
      $form['#attached']['library'][] = 'rhd_admin/admin';
    }
  }
}

/**
 * Implements hook_library_info_alter().
 */
function rhd_admin_page_attachments_alter(array &$attachments) {
  // Do not attach admin helper stylesheet if design=1 appears in the request.
  if (\Drupal::currentUser()->hasPermission('view any unpublished content')) {

    // Provide to 5-sso.js for [data-audience] content rendering.
    $attachments['#attached']['drupalSettings']['rhd_admin']['disable-audience-selection-display'] = true;

    if (!\Drupal::request()->get('design')) {
      $attachments['#attached']['library'][] = 'rhd_admin/theme';
    }

  }
}

/**
 * Implements hook_preprocess_assembly().
 */
function rhd_admin_preprocess_assembly(&$variables) {
  $assembly = $variables['elements']['#assembly'];
  // Add class for assembly status.
  if (!$assembly->isPublished()) {
    $variables['attributes']['class'][] = "entity--status-label entity--unpublished";
  }

  if ($assembly->hasField('field_audience_selection')
    && !$assembly->get('field_audience_selection')->isEmpty()) {
     $variables['attributes']['class'][] = "entity--status-label entity--audience";
  }
}

