:awestruct-layout: product-overview
:awestruct-status: yellow
:awestruct-interpolate: true
:leveloffset: 1

== Overview

Red Hat JBoss Operations Network, a key component of the Red Hat JBoss managed offerings, provides built-in management and monitoring capabilities to effectively administer all of your Red Hat JBoss application environments, helping you improve operational efficiency, reduce costs, and ensure a positive experience for your end users.

== Detail

=== MIDDLEWARE MONITORING AND MANAGEMENT

*Gain greater efficiency with a single point of control*

Managing middleware can be costly and challenging. Applications and services need to be deployed and updated quickly. Administrators need to standardize software configurations and efficiently manage across development, test, and product environments.
Red Hat® JBoss® Operations Network provides built-in management and monitoring capabilities to effectively administer all of your JBoss application environments. This improves operational efficiency, reduces costs, and ensures a positive experience for your end users.

=== BENEFITS

*What you can do with Red Hat JBoss Operations Network*

* Reduce application downtime and proactively address issues before they impact customers.
* Ensure application service levels are being met for performance and availability.
* Support IT governance objectives with enterprise-grade configuration management and runtime service-oriented architecture (SOA) governance.
* Reduce costs and increase return on investment (ROI).

*Simplify provisioning and application deployment*

JBoss Operations Network lets you provision and deploy JBoss solutions faster by standardizing deployments across all of your development, testing, and production environments. Manage change by maintaining an audit trail of your deployments and upgrades.

Using the JBoss Operations Network console or the command-line interface, you can:

* Remotely deploy JBoss servers, apps, and services across groups of managed platforms or servers.
* Manage multiple versions of your application content, maintain a history of all your deployments, and roll back changes if needed.
* Monitor and deploy JBoss patches and updates from the Red Hat Customer Portal, and be notified when a new patch is available.

*Get enterprise-grade configuration management*

With JBoss Operations Network, you can:

* Automatically discover and maintain an inventory of your application platforms, servers, and services.
* Store, manage, and easily update JBoss server and applications configurations to standardize deployments. 
* Detect configuration changes and configuration drift, correlate changes with application performance history, and roll back configuration changes as needed.
* Automate and schedule execution of operations for managed resources and resource groups.
* Use runtime SOA governance for your enterprise service bus (ESB) running on Red Hat JBoss Fuse Service Works.

*Identify issues with performance and availability monitoring*

JBoss Operations Network provides advanced, comprehensive monitoring of performance and availability of applications and services to help you identify and address issues before they impact your customers and your business. You can:

* Get real-time and historical views of performance and availability.
* Ensure application service levels by measuring performance against automatically calculated baselines.
* Define conditional alerts based on predefined thresholds. 
* Send notifications via email to individual users or groups, or via Simple Network Management Protocol (SNMP) to third-party event management consoles. 
* Automate operations or execute server scripts to correct faults in response to an alert.

