source 'http://rubygems.org'
#gem "blinkr", :path => "/Users/ian/Desktop/blinkr"
gem 'blinkr', git: 'http://github.com/RubyGemTSL/blinkr', branch: 'failhard_option'
gem 'builder', '~> 3.2', '>= 3.2.3'