:awestruct-layout: product-get-started-old
:awestruct-interpolate: true

== Extra section

A great way to experience OpenShift Enterprise is to get started with the online hosted version - OpenShift Online. To use OpenShift Online and take advantage of the power and elasticity of the Cloud, you only need to do the following:

1. Sign up for OpenShift Online - https://www.openshift.com/app/account/new. 
2. Create an "Application" in OpenShift Online (with the web console, command-line tools, or your IDE)
3. Code the application in your favorite environment, or use one of the available Quickstarts.
4. Push the application code to OpenShift Online (using Git)

    // Create the app based on an existing GitHub repository,
    // And it all gets set up in the cloud
    rhc create-app twt python-3.3 mongodb-2.4 --from-code git://github.com/openshift/openshift-twt-mongo-demo.git

    // Need to make a change? A local Git repository is checked out into ./twt
    cd twt

    // .... change some code ...
   git commit -a -m "My first change"
   git push origin master

   // And now your changes are live online


That's all there is to it. Simple, right? If you want to learn more about bringing tha power of OpenShift Online into your business, you can learn more here - https://www.openshift.com/products/enterprise 
