:awestruct-layout: product-overview
:awestruct-status: green
:awestruct-interpolate: true
:leveloffset: 1

== Overview

Red Hat Enterprise Linux Atomic Host is a secure, lightweight and minimized footprint operating system that is optimized to run Linux containers. A member of the Red Hat Enterprise Linux family, Red Hat Enterprise Linux Atomic Host couples the flexible, lightweight and modular capabilities of Linux Containers with the reliability and security of Red Hat Enterprise Linux in a reduced image size. Learn more about Red Hat Enterprise Linux Atomic Host.

By combining the flexible, modular capabilities of Linux containers with the reliability and security of Red Hat Enterprise Linux, customers can securely and efficiently deploy and update containers across traditional and public, private, and hybrid cloud infrastructures. Explore the technical specifications, features, and benefits of containerization with Red Hat.

Learn about containers in the #{site.base_url}/containers/[Containers] solution section.

== Detail

=== OPTIMIZED FOR CONTAINERS

Deploy a secure, integrated host platform that is designed to run container images with optimizations for scalability, density, and performance.

=== ATOMIC UPDATING AND ROLLBACK

A new, simplified update mechanism for host OS lets you download and deploy updated versions in a single step. With built-in retention of a previous version of the host OS, you can easily rollback to an earlier state.

=== BUILDING AND RUNNING OF CONTAINERS

Build and run image-based containers using the docker service, accessible through the Extras channel as part of a Red Hat Enterprise Linux Server subscription.

=== SECURITY

Secure and isolate applications with SELinux in containers, reducing potential attack surfaces and ensuring that if a container process goes down or is compromised, other applications and the host remain safe and functional.

=== ORCHESTRATION

Build composite applications by orchestrating multiple containers as microservices across multiple host instances using the Kubernetes orchestration framework.

=== SUPPORT FOR SUPER PRIVILEGED CONTAINERS

Easily configure super privileged containers through the CLI, granting trusted access to the host system and other containers for the applications that need it.

=== ABILITY TO RUN RED HAT ENTERPRISE LINUX PLATFORM IMAGES

Deploy applications that have been developed, tested and certified for Red Hat Enterprise Linux 6 and Red Hat Enterprise Linux 7 in a container on Red Hat Enterprise Linux Atomic Host.

=== FLEXIBILITY TO DEPLOY ACROSS THE OPEN HYBRID CLOUD

Deploy Red Hat Enterprise Linux 7 Atomic Host to physical, virtual and public and private cloud environments, including Amazon Web Services and Google Compute Engine.

