<?php

/**
 * @file
 * Contains console_export_test.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_preprocess_HOOK().
 */
function author_preprocess_node(&$variables) {
  $node = $variables['node'];
  $view_mode = $variables['view_mode'];
  if ($node->getType() === 'author' && $view_mode == 'teaser') {
    $variables['content']['social_icons'] = [];
    $social_fields = [
      'field_twitter',
      'field_youtube',
      'field_linkedin',
      'field_github',
      'field_facebook',
    ];
    foreach ($social_fields as $field) {
      $value = $node->get($field)->getValue();
      if ($value && count($value) && isset($value[0]['uri'])) {
        $value = reset($value)['uri'];
        $icon = str_replace('field_', '', $field);

        // special overrides
        if ($value == 'facebook') {
          $icon = 'facebook-square';
        }

        $variables['content']['social_icons'][] = [
          'value' => ['#markup' => $value],
          'icon' => ['#markup' => $icon]
        ];
        unset($variables['content'][$field]);
      }
    }
  }
}
