name: Red Hat JBoss Developer Studio
abbreviated_name: JBoss Developer Studio
forum_url: https://community.jboss.org/en/jbossdevstudio
current_version: 7.1.0.GA
intro_video: https://vimeo.com/95444954
featured_videos:
 - http://vimeo.com/92554627
 - http://vimeo.com/82204444
 - http://vimeo.com/81565404
 - http://vimeo.com/70822309
 - http://vimeo.com/67480300
guides:
  CDI_Tools_Reference_Guide:
  Getting_Started_Guide:
  Hibernate_Tools_Reference_Guide:
  Installation_Guide:
  JBoss_Portlet_Tools_User_Guide:
  JBoss_RESTful_Web_Services_User_Guide:
  JBoss_SOAP_Web_Services_User_Guide:
  JMX_Tools_Reference_Guide:
  JSF_Tools_Reference_Guide:
  JSF_Tools_Tutorial:
  Maven_Tools_Reference_Guide:
  Migration_Guide:
  Release_Notes_7.1.0:
  Seam_Developer_Tools_Reference_Guide:
  Seam_Tools_Tutorial:
  User_Guide:
  Visual_Web_Tools_Reference_Guide:
default_download_artifact_type: jar_universal
downloads:
  7.1.0.GA:
    release_date: 2013-12-16
    description: An Eclipse-based IDE that gives you everything you need to build rich web and enterprise Java applications.
    assets:
      jar_universal:
        size: 613mb
        name: Jar (Universal Binary with EAP)
        type: jar
      standalone_universal:
        artifacts:
          standalone_jar:
            size: 487mb
            type: jar
          standalone_zip_central:
            size: 410mb
          standalone_zip_update:
            size: 719mb
      source:
        size: 6mb
#  7.0.0.GA:
#    release_date: 2013-07-23
#    description: An Eclipse-based IDE that gives you everything you need to build rich web and enterprise Java applications.
#    assets:
#      jar_universal:
#        size: 591mb
#        name: Jar (Universal Binary with EAP)
#      standalone_universal:
#        artifacts:
#          standalone_jar:
#            size: 481mb
#          standalone_zip_update:
#            size: 697mb
#      release_notes:
#      source:
#        size: 6mb
#  6.0.1.GA:
#    release_date: 2013-04-04
#    description: An Eclipse-based IDE that gives you everything you need to build rich web and enterprise Java applications.
#    assets:
#      jar_universal:
#        size: 566mb
#        name: Jar (Universal Binary with EAP)
#      jar_standalone:
#        size: 455mb
#        name: Jar (Standalone Universal Binary)
#      release_notes:
#      source:
#        size: 111mb
#  6.0.0.GA:
#    release_date: 2012-12-07
#    description: An Eclipse-based IDE that gives you everything you need to build rich web and enterprise Java applications.
#    assets:
#      jar_universal:
#        size: 564mb
#        name: Jar (Universal Binary with EAP)
#      jar_standalone:
#        size: 454mb
#        name: Jar (Standalone Universal Binary)
#      release_notes:
#      source:
#        size: 3mb
#  5.0.0.GA:
#    release_date: 2012-06-21
#    description: An Eclipse-based IDE that gives you everything you need to build rich web and enterprise Java applications.
#    assets:
#      jar_universal:
#        size: 495mb
#        name: Jar (Universal Binary with EAP)
#      jar_standalone:
#        size: 385mb
#        name: Jar (Standalone Universal Binary)
#      release_notes:
#      source:
#        size: 111mb
upstream_projects:
  - jbosstools

