:awestruct-layout: solution-adoption
:awestruct-interpolate: true

[discrete]
=== [[culture]]Culture
Cultural shifts are as important as any other aspect of DevOps.  A successful transformation starts with a culture that breaks down traditional development/operations silos, promotes communication between everyone involved in delivering applications, and emphasizes constant process and product improvement.

[discrete]
==== Mindset
The most important goal of software development is getting good ideas delivered into users hands as quickly as possible.  In order to achieve this goals, teams responsible for activities such as build, test, deploy, provisioning, administering software need to maintain a mindset that embraces collaboration and transparency.

[discrete]
==== Collaboration
In traditional IT, the priorities and goals of development and operations teams are often misaligned, causing a wall of confusion. Developers want to move quickly from idea, to code, to production. Operations wants predictable production deployments to remain stable. Developers need rapid change and operations needs stability (and hence a desire for minimal change).

Misaligned goals lead to typical enterprise slowdowns. Add the typical finger pointing between various stakeholders, each protecting the success they are responsible for. This wall between development and operations is cultural and a byproduct of their misaligned goals. It’s also aggravated by the lack of good available tools and processes. To aggravate things further, for many teams, the development and test environments are different from production.

In addition, add the friction between development and operations because of monolithic application development and deployment patterns. It’s harder to perform accurate root cause analysis in monolithic application code which also increases mistrust and fighting between development and operations. As a result of all of these factors, many organizations end up with paralysis, unable to make forward progress.

The key to avoiding this paralysis is understanding the consequences and embracing newer methods and tools.

[discrete]
==== Transparency
Combining siloed teams helps eliminate the pursuit of different—and often conflicting—goals and metrics. Sharing ideas and improvements, no matter where they originate, creates a vital feedback loop for the entire app delivery process.  Standardized tooling to accurately report builds, tests, deployments, changes aid in improving cultural transparency.

|=======
|link:https://blog.openshift.com/what-is-devops-really/[What is DevOps Really?]
|link:https://blog.openshift.com/your-devops-journey-starts-with-business/[Your DevOps Journey Starts With Business]
|link:http://www.redhat.com/en/about/events/transforming-organizational-culture-through-devops-and-paas[Transforming organizational culture through DevOps and PaaS]
|link:http://developerblog.redhat.com/2013/12/10/red-hat-begins-devops-journey/[Red Hat IT Begins Its DevOps Journey]
|link:http://www.businessinsider.com/red-hat-ceo-it-is-in-fight-for-its-life-2015-2[Red Hat CEO: Today's IT department is in a fight for its life]
|Learn more about DevOps culture at link:https://developerblog.redhat.com/category/devops/[developerblog.redhat.com].
|=======

'''

[discrete]
=== [[automation]]Automation

[discrete]
==== [[continuous-integration]]Continuous Integration
The time between the introduction of a software defect and its detection can have a dramatic effect on the elimination of that defect: find the defect soon after its introduction, with the relevant changes fresh in the developer’s mind, and it will be easy to eliminate — find it later, after the details of the change have faded, and the solution can be elusive.

Continuous Integration facilitates the early detection and eradication of software defects: defects that may otherwise go undetected for days, weeks, or months after they were created. Detecting and resolving these problems early in the development process can translate into fewer bugs and shorter timelines.

A continuous integration server, such as Jenkins, Travis, buildbot, Bamboo or Wercker, monitors changes in the repository and identifies the need for an integration build/test and orchestrates the process.

[[integration-testing]]Testing Automation—such as link:http://www.arquillian.org[Arquillian], link:https://beaker-project.org/[Beaker], or link:http://autotest.github.io/[Autotest] for applications or Selenium for web apps—to execute integration and end-to-end tests on the build application, again providing test reports as it does so.

The continuous integration server parses the test reports and provides feedback to the developer. At this point, the developer either implements any necessary defect fixes or continues with the application development.

[discrete]
===== Get Started
|=======
|Get Started with link:https://developers.openshift.com/en/managing-continuous-integration.html[Jenkins on OpenShift]
|Get Started with link:https://hub.openshift.com/quickstarts/26-travis-ci[Travis and OpenShift]
|Introduction to link:http://arquillian.org/guides/getting_started/[Arquillian]
|=======


[discrete]
==== [[continuous-delivery]]Continuous Delivery
[[configuration-as-code]][[server-provisioning]]An environment provisioning tool—such as link:https://access.redhat.com/documentation/en-US/Red_Hat_Network_Satellite/5.3/html/Reference_Guide/ch-cobbler.html[Cobbler], link:http://docs.ansible.com/index.html[Ansible], link:https://access.redhat.com/articles/1138393[Puppet], or link:https://learn.chef.io/learn-the-basics/rhel/[Chef] to create the environments in which to test the software against one or more versions of an operating system.

|=======
|link:https://www.redhat.com/en/about/events/expediting-devops-and-continuous-delivery-paas[Expediting DevOps and continuous delivery with PaaS]
|link:https://www.redhat.com/en/about/events/continuous-delivery-docker-containers-and-java-ee[Continuous delivery with docker containers and Java EE]
|link:https://www.redhat.com/en/about/events/establishing-continuous-delivery-pipeline-faster-integration[Establishing a continuous delivery pipeline for faster integration]
|[[container-orchestration]]link:http://www.projectatomic.io[Deploy and Manage Your Docker Containers.]
|link:http://www.redhat.com/en/about/blog/red-hat-and-google-collaborate-kubernetes-manage-docker-containers-scale[Red Hat and Google Collaborate on Kubernetes to Manage Docker Containers at Scale]
|link:https://access.redhat.com/articles/1198103[Get Started Orchestrating Containers with Kubernetes]
|=======

'''

[discrete]
=== [[tools]]Tools and Infrastructure

[discrete]
==== Code
Red Hat provides support for multiple versions of C, C++, Java, JavaScript, Node, Python, Ruby and many more languages.

Check out the versions of link:https://access.redhat.com/products/Red_Hat_Enterprise_Linux/Developer/#dev-page=5[Python], link:https://access.redhat.com/products/Red_Hat_Enterprise_Linux/Developer/#dev-page=5[Ruby], link:https://access.redhat.com/articles/1299013[Java] and link:https://access.redhat.com/products/Red_Hat_Enterprise_Linux/Developer/#dev-page=5[JavaScript] available within link:#{site.base_url}/products/softwarecollections[Red Hat Software Collections].

Seamless integration with link:#{site.base_url}/products/openshift[OpenShift] allows you to quickly get up and running with your codebase.

[discrete]
==== Build Tools
Build automation should be advanced enough to eliminate human intervention entirely in the process. To achieve this the build needs to be complete, so that the end result is an artifact that could be installed into a virgin environment and run.. Various approaches can be adopted in migrating to the target build time; for example, the code may offer the option to modularize the build so that only a partial build may be needed for most commits. Then full builds may be run less frequently, maybe nightly or weekly depending on how long they take to execute.

The build manager—such as link:http://ant.apache.org[Apache Ant], link:http://maven.apache.org[Apache Maven] to create the application (providing test reports as it does so).

|=======
|Get Started with link:#[JBoss Enterprise Maven Repository]
|=======


[discrete]
==== [[containers]]Containers
Deploy a secure, integrated host platform that is designed to run container images with optimizations for scalability, density, and performance.

Build and run image-based containers using the docker service, accessible through the link:https://access.redhat.com/solutions/265523[Extras] channel as part of a link:#{site.base_url}/products/rhel[Red Hat Enterprise Linux] subscription.

|=======
|link:https://www.redhat.com/en/insights/containers[Transform application delivery with containers]
|link:http://developerblog.redhat.com/2015/03/11/introducing-the-rhel-container-for-rhel-atomic-host/[Learn more about RHEL Atomic] or watch the link:https://www.youtube.com/watch?v=64SigEZyMHw[video].
|link:https://access.redhat.com/articles/881893[Get Started with Docker Formatted Container Images on Red Hat Systems]
|link:http://www.projectatomic.io[Deploy and Manage Your Docker Containers.]
|link:http://www.redhat.com/en/about/blog/red-hat-and-google-collaborate-kubernetes-manage-docker-containers-scale[Red Hat and Google Collaborate on Kubernetes to Manage Docker Containers at Scale]
|link:https://access.redhat.com/articles/1198103[Get Started Orchestrating Containers with Kubernetes]
|=======

[discrete]
==== [[source-control]]Source Control
While not a new concept, it’s essential that all project source code and build components are maintained in a single repository. The repository must contain not just the source code, but all the assets needed to build, deploy, and test the software; this may include test scripts, property/configuration files, database schema, install scripts, and third-party libraries. Red Hat can provide you with supported versions of git and svn

|=======
|Get Started with link:https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Developer_Guide/collaboration.git.html[Git]
|Get Started with link:https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Developer_Guide/collaborating.svn.html[Subversion]
|=======

