= DevOps
:awestruct-layout: solution-detail


== Header
The DevOps movement is about reducing your time to market. Red Hat believes that the combination of cultural changes, process automation and tools can help you achieve this goal. Find all the tools you'll need to embrace the DevOps movement including link:/devops/get-started/#source-control[source control], link:/devops/get-started/#build-tools[build tools], link:/devops/get-started/#integration-testing[system integration testing], link:/devops/get-started/#continuous-integration[continuous delivery], link:/devops/get-started/#containers[containers], link:/devops/get-started/#configuration-as-code[configuration as code], link:/devops/get-started/#server-provisioning[server provisioning], microservices and link:/devops/get-started/container-orchestration[container orchestration].

You'll also find how Red Hat's own culture and processes have been automated while on our DevOps journey. The approach is focused on making it easy to develop, test, deploy, integrate, scale and manage applications. We'll also be sharing insights on culture changes as Red Hat continues on its own DevOps journey.


== Left Section
=== Culture
At its core, DevOps is about culture. DevOps aims at improving communication, collaboration and transparency between developers, operations and their clients.

link:/devops/get-started/#culture[Learn more on culture...]


== Middle Section
=== Automation
Learn how treating infrastructure as code and continuous delivery can help you deliver software to production on demand.

link:/devops/get-started/#automation[Learn more on automation ...]


== Right Section
=== Tools
Discover everything from developer tooling, source control, and build tools to help create your application.

link:/devlops/get-started/#tools[Learn more on tools...]




