:awestruct-layout: product-download

== Upstream

https://softwarecollections.org/[softwarecollections.org]

Visit the https://softwarecollections.org/[softwarecollections.org] and contribute.


== Alternate

Red Hat Software Collections and Red Hat Developer Toolset are available via a Red Hat Enterprise Linux developer subscription.

=== Getting a Red Hat Enterprise Linux developer subscription

Developers have multiple options when seeking to obtain a Red Hat Enterprise Linux developer subscription - see the details http://developers.redhat.com/products/rhel/download/[here]. In summary, there are three sure-fire ways to get started:

* Join the Red Hat Developers program to get $0 Red Hat Enterprise Linux Developer Suite subscription which includes Red Hat Enterprise Linux server and more.

* Purchase one of several Red Hat Enterprise Linux Developer Subscriptions where you can have a choice of developer support options.

* If you’re a Red Hat technology partner (e.g. an ISV), get free subscriptions by joining Red Hat Connect for Technology Partners. Once there, register your company and join the “Zone” for Red Hat Enterprise Linux or Containers.


*Reminder:* Red Hat Enterprise Linux Developer subscriptions intended for development purposes only, and are not intended for other purposes such as production environments.