:awestruct-layout: product-updates
:awestruct-interpolate: true
:leveloffset: 1
:awestruct-description: "Get Red Hat Software Collections (RHSCL) updates for programming languages, databases, web servers, and more"

== Red Hat Software Collections 2.3 Beta

Red Hat Software Collections 2.3 Beta is now available with new and update software collections. With Red Hat Software Collections (RHSCL), developers have access to the latest development technologies on Red Hat Enterprise Linux.


=== New additions to Red Hat Software Collections 2.3 Beta include

* *Open source databases*
** New MySQL 5.7  
** New Redis 3.2
** Updates to MongoDB 3.2
* *Open source languages*
** New Perl 5.24
** New PHP 7.0
** Updates to PHP 5.6
** Updates to Python 3.5
** Updates to Ruby 2.3
* New Git 2.9
* New Thermostat 1.6, a JVM monitoring tool.
* Repackaged Eclipse Neon (4.6.1), once part of the Red Hat Developer Toolset collection is now its own separate collection.



== Red Hat Software Collections 2.2

Red Hat Software Collections 2.2 is now available with new and update software collections. With Red Hat Software Collections (RHSCL), developers have access to the latest development technologies on Red Hat Enterprise Linux. 

=== New additions

* *Open source databases*
** MariaDB 10.1
** MongoDB 3.2
** Postgres 9.5
* *Open source languages, development frameworks, and tools*
** Node.js v4.4.2
** Python 3.5
** Ruby 2.3
** Rails 4.2
** Maven 3.3



== Using Red Hat Software Collections for container development

Most RHSCL collections are available as docker-formatted container images from the Red Hat Container Registry. This makes it easy to build and deploy applications in containers that use RHSCL components. See the release notes for a full list of new and updated collections.

In addition, Dockerfiles used to build the RHSCL container images are available as RHSCL rpm on RHEL 7. These source Dockerfiles can be used for customizing or rebuilding containers with RHSCL components.



