:awestruct-layout: product-get-started-fuse
:awestruct-interpolate: true

:jbdsis-standalone-installer-download-url: https://developers.redhat.com/download-manager/file/devstudio-integration-stack-10.0.0.GA-standalone-installer.jar
:fuse-on-karaf-download-url: https://developers.redhat.com/download-manager/file/jboss-fuse-karaf-6.3.0.redhat-187.zip
:eap-download-url: https://developers.redhat.com/download-manager/file/jboss-eap-6.4.0.GA-installer.jar
:fuse-on-eap-download-url: https://developers.redhat.com/download-manager/content/origin/files/sha256/84/847cd3a03bc3ae41b1b997b2bae34dadaa8a8fee4b45dd70de8b53bb32f953dd/fuse-eap-installer-6.3.0.redhat-187.jar

## Fuse Runtime

=== Prerequisites
Before you start, make sure you have installed the following software:

* Java SE Development Kit (JDK) version 1.8.x (Java 8) - we recommend Oracle JDK or OpenJDK
* https://maven.apache.org/download.cgi[Apache Maven]

[[fuse-karaf-install-runtime]]
=== Install and configure the JBoss Fuse Karaf runtime
video::183851396[vimeo]

. Download the {fuse-on-karaf-download-url}[JBoss Fuse Karaf] runtime package.
. Unpack the downloaded `.zip` file to a convenient location on your file system, `_FuseInstall_`.
. Add a user to the Fuse runtime.
Open the `_FuseInstall_/etc/users.properties` file in a text editor and look for the line starting with `\#admin=admin...`.
Delete the `#` character at the start of the line and customize the username, `USERNAME`, and password, `PASSWORD` in the user entry:
+
----
USERNAME=PASSWORD,admin,manager,viewer,Operator, Maintainer, Deployer, Auditor, Administrator, SuperUser
----
+
Save the `users.properties` file.

=== Set up your development environment
video::183852576[vimeo]

. Download the {jbdsis-standalone-installer-download-url}[Red Hat JBoss Developer Studio Integration Stack 10.0.0.GA Stand-Alone Installer].
. Run the installer
.. For Mac / Windows Development Hosts:
... Go to the folder you have downloaded the installer and either:
.... Right-click on the installer jar
.... Select *Open With->Jar Launcher*
... Or double-click on the jar to start the installer (on Windows).
.. For Linux Development Hosts:
... Go to the folder where you have downloaded the installer and execute it with
+
----
java -jar devstudio-integration-stack-10.0.0.GA-standalone-installer.jar
----
.	During installation:
.. Accept the terms and conditions
.. Choose your preferred installation path
.. Select the Java 8 JVM
.. At the *Select Platforms and Servers* step, configure the runtime server by clicking *Add* and browsing to the location of the `_FuseInstall_` directory (see <<fuse-karaf-install-runtime>>)
.. Select *JBoss Fuse Development* as additional features
. Developer environment will start up.
When the *Searching for runtimes* dialog appears, click *OK* to create the JBoss Fuse runtime.
. Accept any additional dependencies and license agreements.

=== Build your first Fuse application

With your tooling and runtime installed, you're ready to start your first project.
We'll get you started with a http://www.enterpriseintegrationpatterns.com/ContentBasedRouter.html[Camel Content Based Router (CBR)] pattern.

The CBR quickstart watches a directory for incoming orders and dispatches them to outgoing directories based on the customer country contained in the order XML.
We will import the quick start into your workspace and then build it from scratch so you see how it works.

==== Create a New Project

First, we need to create a new Fuse Project:

. Select *File->New->Fuse Integration Project*.
. Call it `fuse-camel-cbr`. Click *Next*.
. Select your Fuse 6.3 server as the *Target Runtime*. Click *Next*.
. Select *Use a predefined template*.
. Select the *JBoss Fuse->Beginner->Content Based Router* template.
. Ensure that *Blueprint DSL* is selected.
. Click *Finish*.

==== Deploy the Project to the Server

. In the *Servers* view, if your server isn’t already started - select your runtime server and click the green arrow to start it.
. Right-click on the server after it is started and select *Add and Remove* from the context menu.
. In the *Add and Remove* dialog, select your `fuse-camel-cbr` project and click the *Add >* button.
. Click *Finish*.
. You can check that everything is ok by issuing the command in the *Shell* tab: `osgi:list`
. Your bundle should be present at the end of the list - for example, something like:
+
----
[ 302] [Active         ] [Created         ] [           ] [   80] Fuse CBR Quickstart (1.0.0.SNAPSHOT)
----

==== Test the Project
As soon as the Camel route has been started, it will create a directory, `work/cbr/input`, in your JBoss Fuse installation.

Now you can test your Camel route and see it in action.

Copy the files you find in this quickstart's `src/main/fabric8/data` directory to the newly created `work/cbr/input` directory.
You can do this in your system file browser (outside of Eclipse) or the *Remote Systems* view (inside Eclipse - *Window->Show View->Other*, and then *Remote Systems->Remote Systems*).
You can click and drag files from the *Project Explorer* into a directory in the *Remote Systems* view to trigger the Camel route processing.

Wait a few moments and you will find the same files organized by country under the `work/cbr/output` directory:

* `order1.xml` in `work/cbr/output/others`
* `order2.xml` and `order4.xml` in `work/cbr/output/uk`
* `order3.xml` and `order5.xml` in `work/cbr/output/us`

Note that if you use the *Remote Systems* view, you may need to manually refresh the runtime directory to see folders and files as they are added and removed.
Select the directory to refresh in the tree and hit F5 or select the *Refresh¨ button on the view toolbar.

Use `log:display` in the Fuse shell to check out the business logging.

You can also use the JMX Navigator to see your deployed Camel project and interact with the exposed Camel endpoints that way. See the documentation for details.

==== Undeploy the Project

To stop and undeploy the bundle in the Fuse server:

. In the *Servers* view, select your running runtime server.
. Right-click on the server and select *Add and Remove* from the context menu.
. In the *Add and Remove* dialog, select your `fuse-camel-cbr` project and click the *Remove >* button.
. Click *Finish*.
. You can check that everything is ok by issuing the command in the Fuse console: `osgi:list`
. Your bundle should no longer be present at the end of the list.

=== Next Steps

You now know how to:

* Create one of the available Fuse project templates in your workspace.
* Deploy a project into a running Fuse server.
* Test a simple project.
* Undeploy the project from the server.

Where do you go from here?

|===
|Demonstration Description | Material

| What is JBoss Fuse?
| https://github.com/jboss-fuse/quickstarts/tree/master/cbr[Demo source], https://vimeo.com/130279093[Video]

| Tooling
| https://vimeo.com/131199128[Tooling Usability Improvements], https://vimeo.com/130987010[Debugger Support], https://vimeo.com/131250890[Transformation Tooling], https://www.youtube.com/watch?v=iY4PF4TyFTI[Installing SAP Tooling], https://www.youtube.com/watch?v=2IeqsoOhycY[Using SAP Tooling]

| What is Apache Camel? What are Enterprise Integration Patterns (EIP)?
| https://vimeo.com/130280300[Video about connectors], https://vimeo.com/130281513[Video about EIPS], https://github.com/jboss-fuse/quickstarts/tree/master/eip[Demo source]

| Managing JBoss Fuse with Fuse Fabric
| https://vimeo.com/130283717[Video]

| Step by step build the Home Loan Application with Microservices Architecture
| https://vimeo.com/130284677[Video 1 Service with Simple EIP], https://vimeo.com/130285316[Video 2 Persisting to Database]

| Business requirements change. Extend the home loan application. New SaaS applications? No problem..
| https://vimeo.com/130286282[Video 3 Integrating with SaaS], https://vimeo.com/130286646[Video 4 Composing services]

| Business expanding. Extend the home loan application to partners, suppliers.
| https://vimeo.com/130286799[Video 5 Exposing Restful Web service]

| Innovate further. Try, experiment, test, deploy.
| https://vimeo.com/130286968[Video 6 Testing and Debugging], https://vimeo.com/130287082[Video 7 Deploy and manage in Fabric]

| Alternate running environment (or container)
| link:https://vimeo.com/146080419[Video 7 Running integration on Jboss EAP]
|===

## EAP Runtime

=== Prerequisites
Before you start, make sure you have installed the following software:

* Java SE Development Kit (JDK) version 1.8.x (Java 8) - we recommend Oracle JDK or OpenJDK
* https://maven.apache.org/download.cgi[Apache Maven]

[[fuse-eap-install-runtime]]
=== Install and configure the JBoss Fuse on JBoss EAP runtime

. Download the {eap-download-url}[JBoss EAP] runtime package.
. Run the JBoss EAP installer, as follows:
+
----
java -jar jboss-eap-6.4.0-installer.jar
----
. During installation:
.. Accept the terms and conditions
.. Choose your preferred installation path, `_EAPInstall_`, for the JBoss EAP runtime
.. Create an administrative user and make a careful note of these administrative user credentials for later
.. You can accept the default settings on the remaining screens
. Download the {fuse-on-eap-download-url}[Fuse on EAP] runtime package.
. Open a command prompt and change directory to `_EAPInstall_`.
. From the `_EAPInstall_` directory, run the Fuse on EAP installer, as follows:
+
----
java -jar <TEMP_LOCATION>/fuse-eap-installer-6.3.0.redhat-187.jar
----

=== Set up your development environment

The following steps will install a local version of JBoss Developer Studio 10.0.0 (the Eclipse Mars edition) along with the Fuse tooling.

. Download the {jbdsis-standalone-installer-download-url}[Red Hat JBoss Developer Studio Integration Stack 10.0.0.GA Stand-Alone Installer].
. Go to the folder where you have downloaded the installer and execute it with
+
----
java -jar devstudio-integration-stack-10.0.0.GA-standalone-installer.jar
----
.	During installation:
.. Accept the terms and conditions
.. Choose your preferred installation path
.. Select the Java 8 JVM
.. At the *Select Platforms and Servers* step, configure the runtime server by clicking *Add* and browsing to the location of the `_EAPInstall_` directory (see <<fuse-eap-install-runtime>>)
.. Select *JBoss Fuse Development* as additional features
. Developer environment will start up.
When the *Searching for runtimes* dialog appears, click *OK* to create the JBoss EAP runtime.
. Accept any additional dependencies and license agreements.

=== Build your first Fuse on EAP application
With your tooling and runtime installed, you're ready to start your first project. We'll get you started with a Spring-based Camel route on EAP.

==== Create a New Project
First, we need to create a new Fuse Project.

. Select *File->New->Fuse Integration Project*.
. Call it `eap-camel`. Click *Next*.
. Select your `Red Hat JBoss EAP 6.4 Runtime` server as the *Target Runtime*. Click *Next*.
. Select *Use a predefined template*.
. Select the *Fuse on EAP->Medium->Spring on EAP* template.
. Click *Finish*.

==== Deploy the Project to the Server

. In the *Servers* view (bottom left corner of the Fuse Integration perspective), if your server isn’t already started - select your runtime server and click the green arrow to start it.
. After the server has started, switch back to the *Servers* view, right-click on the server and select *Add and Remove* from the context menu.
. In the *Add and Remove* dialog, select your `eap-camel` project and click the *Add >* button.
. Click *Finish*.

==== Test the Project
As soon as the Camel route has been started, it will be available via a web address on your EAP server: http://localhost:8080/eap-camel?name=Kermit

You can view it in your favorite browser or directly in Eclipse through the Internal Web Browser (*Window->Show View->Other*, and then *General->Internal Web Browser*).

You should see in the console at that web address: “Hello Kermit”

==== Undeploy the Project

To stop and undeploy the bundle in the Fuse server:

. In the *Servers* view, select your running runtime server.
. Right-click on the server and select *Add and Remove* from the context menu.
. In the *Add and Remove* dialog, select your `eap-camel` project and click the *Remove >* button.
. Click *Finish*.

=== Next Steps

You now know how to:

* Create one of the available Fuse project templates in your workspace.
* Deploy a project into a running Fuse on EAP server.
* Test a simple project.
* Undeploy the project from the server.
