:awestruct-layout: product-get-started-fuse
:awestruct-interpolate: true

:jbdsis-standalone-installer-download-url: https://devstudio.redhat.com/9.0/stable/updates/integration-stack/devstudio-integration-stack-9.0.2.GA-standalone-installer.jar
:fuse-on-karaf-download-url: https://access.redhat.com/jbossnetwork/restricted/listSoftware.html?product=jboss.fuse&downloadType=distributions
:installation-on-eap-link: https://access.redhat.com/documentation/en/red-hat-jboss-fuse/6.3/paged/installation-on-jboss-eap

## Fuse Runtime

=== Prerequisites
To build JBoss Fuse applications, you need https://maven.apache.org/[Apache Maven]. If you do not already have it installed, follow the instructions on the https://maven.apache.org/download.cgi[Apache Maven Download] page.

=== Install and configure your development environment
The following steps will install a local version of JBoss Developer Studio 9.1.0 (the Eclipse Mars edition) along with the Fuse tooling.

. Install the Java SE Development Kit (JDK), we recommend Oracle JDK or OpenJDK. (Must be Java 8 compatible.)
. Download the {jbdsis-standalone-installer-download-url}[Red Hat JBoss Developer Studio Integration Stack 9.0.2.GA Stand-Alone Installer].
. Run the installer
.. For Mac / Windows Development Hosts:
... Go to the folder you have downloaded the installer and either:
.... Right-click on the installer jar
.... Select *Open With->Jar Launcher*
... Or double-click on the jar to start the installer (on Windows).
.. For Linux Development Hosts:
... Go to the folder where you have downloaded the installer and execute it with
.... java -jar [installer].jar +
Note: This will execute the installation wizard.
. In the wizard, ensure that you select your JDK, not the JRE chosen by default.
. Also in the wizard, on the *Select Additional Features to Install* page, ensure you select *JBoss Fuse Development*
. Start Developer Studio.
.  Configure Maven:
.. In JBoss Developer Studio, click *Window->Preferences*
.. Type `maven` in the filter text box to view options related to Maven.
.. In the results, expand *JBoss Tools* and click *JBoss Maven Integration*
..  Click the *Configure Maven Repositories* button.
..  Click *Add Repository* and then click the downward facing arrow in the *Profile ID:* field to view the available Maven repositories.
.. Select *redhat-ga-repository* from the drop-down list profile and then click *OK*.
.. In the *Maven Repositories* dialog, click *Finish*.
.. When prompted to confirm the updates to your `settings.xml` file, click *Yes*.

=== Define a JBoss Fuse Server
Now that you have Developer Studio and Fuse Tools installed, you can install a reference to your installed Fuse runtime to explore via the tooling.

. Download the Red Hat JBoss Fuse on Karaf Installer.
.. Browse to the {fuse-on-karaf-download-url}[JBoss Fuse Software Downloads] page on the Red Hat Customer Portal and, when prompted, login to your customer account.
.. Select the version 6.3.0 from the *Version* dropdown menu and click the Download link for the *Red Hat JBoss Fuse 6.3.0 on Karaf Installer* package.
. To install the Fuse runtime, unpack the downloaded `.zip` file into a convenient location on your file system.
This is the Fuse runtime installation directory, `_FuseInstall_`.
. Add a user to the Fuse runtime. Open the `_FuseInstall_/etc/users.properties` file in a text editor and look for the following entry:
+
----
#admin=admin,admin,manager,viewer,Operator, Maintainer, Deployer, Auditor, Administrator, SuperUser
----
+
Delete the `#` character at the start of the line and customize the username, `<USERNAME>`, and password, `<PASSWORD>` in the entry:
+
----
<USERNAME>=<PASSWORD>,admin,manager,viewer,Operator, Maintainer, Deployer, Auditor, Administrator, SuperUser
----
+
Save the `users.properties` file.
. Start Developer Studio.
. Find the *Servers* view in the JBoss (default) perspective.
. Click the *No servers are available. Click this link to create a new server* link.
. In the *New Server* wizard, choose *JBoss Fuse->JBoss Fuse 6.3 Server*. Click Next.
. On the *JBoss Fuse Runtime* page, type the directory where your JBoss Fuse 6.3 server was installed or click *Browse* and find the directory in the *File* dialog.
. Click *Next*.
. Update the user name and password you set up during the server installation process.
. Click *Finish*.
. On the *Servers* tab, select your new server and click on the green start button to start the Fuse Server.
. If you get a Warning about *Remote Host Identification*, click *Yes*.

You will see text pop up on the *Console* tab as the server starts and a new *Shell* tab will appear. This is a hosted version of the Fuse console that you can use in Eclipse.

To get an idea of all the capabilities that come pre-loaded in your server, you can type `osgi:list` at the console prompt.

=== Your First Project

With your tooling and runtime installed, you're ready to start your first project.
We'll get you started with a http://www.enterpriseintegrationpatterns.com/ContentBasedRouter.html[Camel Content Based Router (CBR)] pattern.

The CBR quickstart watches a directory for incoming orders and dispatches them to outgoing directories based on the customer country contained in the order XML.
We will import the quick start into your workspace and then build it from scratch so you see how it works.

=== Create a New Project

First, we need to create a new Fuse Project:

. Create New Fuse Integration Project.
. Call it `fuse-camel-cbr`. Click *Next*.
. Select your Fuse 6.3 server as the *Target Runtime*. Click *Next*.
. Select *Use a predefined template*.
. Select the *JBoss Fuse->Beginner->Content Based Router* template.
. Ensure that *Blueprint DSL* is selected.
. Click *Finish*.

=== Deploy the Project to the Server

. In the *Servers* view, if your server isn’t already started - select your runtime server and click the green arrow to start it.
. Right-click on the server after it is started and select *Add and Remove* from the context menu.
. In the *Add and Remove* dialog, select your `fuse-camel-cbr` project and click the *Add >* button.
. Click *Finish*.
. You can check that everything is ok by issuing the command in the *Shell* tab: `osgi:list`
. Your bundle should be present at the end of the list - for example, something like:
+
----
[ 302] [Active         ] [Created         ] [           ] [   80] Fuse CBR Quickstart (1.0.0.SNAPSHOT)
----

=== Test the Project
As soon as the Camel route has been started, it will create a directory work/cbr/input in your JBoss Fuse installation.

Now you can test your Camel route and see it in action.

Copy the files you find in this quickstart's `src/main/fabric8/data` directory to the newly created `work/cbr/input` directory.
You can do this in your system file browser (outside of Eclipse) or the *Remote Systems* view (inside Eclipse - *Window->Show View->Other*, and then *Remote Systems->Remote Systems*).
You can click and drag files from the *Project Explorer* into a directory in the *Remote Systems* view to trigger the Camel route processing.

Wait a few moments and you will find the same files organized by country under the `work/cbr/output` directory:

* `order1.xml` in `work/cbr/output/others`
* `order2.xml` and `order4.xml` in `work/cbr/output/uk`
* `order3.xml` and `order5.xml` in `work/cbr/output/us`

Note that if you use the *Remote Systems* view, you may need to manually refresh the runtime directory to see folders and files as they are added and removed.
Select the directory to refresh in the tree and hit F5 or select the *Refresh¨ button on the view toolbar.

Use `log:display` in the Fuse shell to check out the business logging.

You can also use the JMX Navigator to see your deployed Camel project and interact with the exposed Camel endpoints that way. See the documentation for details.

=== Undeploy the Project

To stop and undeploy the bundle in the Fuse server:

. In the *Servers* view, select your running runtime server.
. Right-click on the server and select *Add and Remove* from the context menu.
. In the *Add and Remove* dialog, select your `fuse-camel-cbr` project and click the *Remove >* button.
. Click *Finish*.
. You can check that everything is ok by issuing the command in the Fuse console: `osgi:list`
. Your bundle should no longer be present at the end of the list.

=== Next Steps

You now know how to:

* Create one of the available Fuse project templates in your workspace.
* Deploy a project into a running Fuse server.
* Test a simple project.
* Undeploy the project from the server.


## EAP Runtime

=== Prerequisites
To build JBoss Fuse applications, you need https://maven.apache.org/[Apache Maven]. If you do not already have it installed, follow the instructions on the https://maven.apache.org/download.cgi[Apache Maven Download] page.

Make sure you have your JBoss Fuse on EAP runtime already installed and set up. See {installation-on-eap-link}/[Installation on JBoss EAP] for details.

=== Install and configure your development environment

The following steps will install a local version of JBoss Developer Studio 9.1.0 (the Eclipse Mars edition) along with the Fuse tooling.

. Install the Java SE Development Kit (JDK), we recommend Oracle JDK or OpenJDK. (Must be Java 8 compatible.)
. Download the {jbdsis-standalone-installer-download-url}[Red Hat JBoss Developer Studio Integration Stack 9.0.2.GA Stand-Alone Installer].
. Run the installer
.. For Mac / Windows Development Hosts:
... Go to the folder you have downloaded the installer and either:
.... Right-click on the installer jar
.... Select *Open With->Jar Launcher*
... Or double-click on the jar to start the installer (on Windows).
.. For Linux Development Hosts:
... Go to the folder where you have downloaded the installer and execute it with
.... java -jar [installer].jar +
Note: This will execute the installation wizard.
. In the wizard, ensure that you select your JDK, not the JRE chosen by default.
. Also in the wizard, on the *Select Additional Features to Install* page, ensure you select *JBoss Fuse Development*
. Start Developer Studio.
.  Configure Maven:
.. In JBoss Developer Studio, click *Window->Preferences*
.. Type `maven` in the filter text box to view options related to Maven.
.. In the results, expand *JBoss Tools* and click *JBoss Maven Integration*
..  Click the *Configure Maven Repositories* button.
..  Click *Add Repository* and then click the downward facing arrow in the *Profile ID:* field to view the available Maven repositories.
.. Select *redhat-ga-repository* from the drop-down list profile and then click *OK*.
.. In the *Maven Repositories* dialog, click *Finish*.
.. When prompted to confirm the updates to your `settings.xml` file, click *Yes*.

=== Define a JBoss EAP Server
Now that you have Developer Studio and Fuse Tools installed, you can install a reference to your installed Fuse on EAP runtime to explore via the tooling.

. Start Developer Studio.
. Find the *Servers* view in the JBoss (default) perspective.
. Click the *No servers are available. Click this link to create a new server* link.
. In the *New Server* wizard, choose *Red Hat JBoss Middleware->Red Hat JBoss Enterprise Application Platform 6.1+*. Click *Next*.
. On the *Create a new Server Adapter* page, accept the default settings. Click *Next*.
. On the *JBoss Runtime* page, type the directory where your JBoss Fuse on EAP server was installed or click *Browse* and find the directory in the *File* dialog.
. Click *Next*.
. Update the user name and password you set up during the server installation process.
. Click *Finish*.
. On the *Servers* tab, select your new server and click on the green start button to start the EAP Server.

=== Your First Project
With your tooling and runtime installed, you're ready to start your first project. We'll get you started with a Spring-based Camel route on EAP.

=== Create a New Project
First, we need to create a new Fuse Project.

. Select *File->New->Fuse Integration Project*.
. Call it `eap-camel`. Click *Next*.
. Select your Fuse on EAP server as the *Target Runtime*. Click *Next*.
. Select *Use a predefined template*.
. Select the *Fuse on EAP->Medium->Spring on EAP* template.
. Click *Finish*.

=== Deploy the Project to the Server

. In the *Servers* view, if your server isn’t already started - select your runtime server and click the green arrow to start it.
. Right-click on the server after it is started and select *Add and Remove* from the context menu.
. In the *Add and Remove* dialog, select your `eap-camel` project and click the *Add >* button.
. Click *Finish*.

=== Test the Project
As soon as the Camel route has been started, it will be available via a web address on your EAP server: http://localhost:8080/eap-camel?name=Kermit

You can view it in your favorite browser or directly in Eclipse through the Internal Web Browser (*Window->Show View->Other*, and then *General->Internal Web Browser*).

You should see in the console at that web address: “Hello Kermit”

=== Undeploy the Project

To stop and undeploy the bundle in the Fuse server:

. In the *Servers* view, select your running runtime server.
. Right-click on the server and select *Add and Remove* from the context menu.
. In the *Add and Remove* dialog, select your `eap-camel` project and click the *Remove >* button.
. Click *Finish*.

=== Next Steps

You now know how to:

* Create one of the available Fuse project templates in your workspace.
* Deploy a project into a running Fuse on EAP server.
* Test a simple project.
* Undeploy the project from the server.
