:awestruct-layout: product-get-started
:awestruct-interpolate: true

== Prerequisites section title
Install the Java SE Development Kit (JDK), we recommend OpenJDK or Oracle JDK 1.8 or above

== Step1 Duration
5 minutes

== Step2 Duration
5 minutes

== Step3 Duration
15 minutes

== Step1 Title
Install & Configure JBoss Fuse Runtime

== Step2 Title
Set Up Dev Environment

== Step3 Title
Build your first Fuse application


== Step1 Content
1. Download  https://developers.redhat.com/download-manager/file/jboss-fuse-karaf-6.3.0.redhat-187.zip[JBoss Fuse].
2. Unzip JBoss Fuse to any directory in your machine.
3. Change your present working directory(pwd) to this installed folder of JBoss Fuse.
... Open and edit *users.properties* located under *etc* folder in the installation folder 
... Go to the last line Remove the "#" before admin=admin... , this will specified an administrator role user with ID: admin and Password: admin 


video::183851396[vimeo]


== Step2 Content

1.	Download  {jbdsis-standalone-installer-download-url}[Red Hat JBoss Developer Studio one step installer for Fuse]
2.	Run Red Hat JBoss Developer Studio installer
.. For MAC/Linux:
... Go to the folder where you have downloaded Red Hat JBoss Developer Studio, and execute the installer
+
`java -jar devstudio-integration-stack-9.x.x-SNAPSHOT-standalone-installer.jar`
+
*Note:* This will execute the Red Hat JBoss Developer Studio installation wizard.
+
..	For Windows:
+
...	Right Click on devstudio-integration-stack-9.0.2-SNAPSHOT-standalone-installer.jar
...	Select *Open With >Jar Launcher*
+
3.	During installation
..	Accept the terms and condition.
..	Choose your prefered installation path.
..  Select Java 8 JVM
..  Configure runtime server by pointing to the installation directory from Step One.
..	Select *JBoss Fuse Development* as addition features.

4. Developer evironment will start, accept any additional dependencies and license agreements.

video::183852576[vimeo]


== Step3 Content
With your tooling and runtime installed, you’re ready to start your first project. We’ll get you started with a Camel Content Based Router (CBR) pattern and a simple example included with the Fuse server you downloaded and installed.

The CBR quick start watches a directory for incoming orders and dispatches them to outgoing directories based on the customer country contained in the order XML. We will import the quick start into your workspace and then build it from scratch so you see how it works.

. First, to create the project, right click on Project explorer and choose New -> *Fuse Integration Project*
. Name the project and choose *Fuse 6.3* as runtime environement
. Create with existing template *Content Base Routing*
. To point the tool to our runtime server. In the Servers view, add a new Fuse 6.3 Server and select the *jboss-fuse-6.3.0.redhat-xxx*
. Back to the Servers view, select your runtime server and click the green arrow to start it, this now will start your runtime Fuse server.
. To deploy your project to the runtime server. Right-click on the server after it is started and select *Add and Remove…* from the context menu.
. In the “Add and Remove…” dialog, select your project and click the Add > button and Click *Finish*.
. You can check that everything is ok by issuing the command in the Shell tab: osgi:list
. Your bundle should be present at the end of the list (something like “Fuse CBR Quickstart”).

#### Testing the Project
Drag the xml files locate under your project folder */src/main/data* to the input endpoint located in *JMX view* under Server *Connections -> Endpoints*

Wait a few moments and you will find the same files organized by country under the work/cbr/output directory:

* order1.xml in work/cbr/output/others
* order2.xml and order4.xml in work/cbr/output/uk
* order3.xml and order5.xml in work/cbr/output/us

In Terminal view use log:tail in the Fuse shell to check out the business logging.

#### Undeploying the Project
To stop and undeploy the bundle in the Fuse server:

. In the Servers view, select your running runtime server.
. Right-click on the server and select “Add and Remove…” from the context menu.
. In the “Add and Remove…” dialog, select your beginner-camel-cbr project and click the Remove > button.
. Click Finish.
. You can check that everything is ok by issuing the command in the Fuse console: osgi:list
. Your bundle should no longer be present at the end of the list.

video::183852936[vimeo]

### Next Steps
You now know how to:

* Deploy a project into a running Fuse server.
* Test a simple project in two different ways.
* Undeploy the project from the server.
* And create your own Fuse project from scratch with a running Camel route.

Where do you go from here?

|===
|Demonstration Description | Material

| What is JBoss Fuse?
| https://github.com/jboss-fuse/quickstarts/tree/master/cbr[Demo source], https://vimeo.com/130279093[Video]

| Tooling
| https://vimeo.com/131199128[Tooling Usability Improvements], https://vimeo.com/130987010[Debugger Support], https://vimeo.com/131250890[Transformation Tooling], https://www.youtube.com/watch?v=iY4PF4TyFTI[Installing SAP Tooling], https://www.youtube.com/watch?v=2IeqsoOhycY[Using SAP Tooling], Installation video (TBD)

| What is Apache Camel? What are Enterprise Integration Patterns (EIP)?
| https://vimeo.com/130280300[Video about connectors], https://vimeo.com/130281513[Video about EIPS], https://github.com/jboss-fuse/quickstarts/tree/master/eip[Demo source]

| Managing JBoss Fuse with Fuse Fabric
| https://vimeo.com/130283717[Video]

| Step by step build the Home Loan Application with Microservices Architecture
| https://vimeo.com/130284677[Video 1 Service with Simple EIP], https://vimeo.com/130285316[Video 2 Persisting to Database]

| Business requirements change. Extend the home loan application. New SaaS applications? No problem..
| https://vimeo.com/130286282[Video 3 Integrating with SaaS], https://vimeo.com/130286646[Video 4 Composing services]

| Business expanding. Extend the home loan application to partners, suppliers.
| https://vimeo.com/130286799[Video 5 Exposing Restful Web service]

| Innovate further. Try, experiment, test, deploy.
| https://vimeo.com/130286968[Video 6 Testing and Debugging], https://vimeo.com/130287082[Video 7 Deploy and manage in Fabric]

| Alternate running environment (or container)
| link:https://vimeo.com/146080419[Video 7 Running integration on Jboss EAP]
|===

