:awestruct-layout: product-overview
:awestruct-status: green

== Overview

JBoss Fuse is an open source Enterprise Service Bus (ESB) with an elastic footprint that supports integration beyond the data center. The lack of license fees and the ability to deploy JBoss Fuse in several different configurations advances intelligent integration to all facets of your business – on premise or in the Cloud.

JBoss Fuse combines core Enterprise Service Bus capabilities (based on Apache Camel, Apache CXF, Apache ActiveMQ), Apache Karaf and Fuse Fabric in a single integrated distribution.

image::/images/products/fuse/esbtofuse[]

Core messaging is provided by Apache ActiveMQ, services framework (SOAP, XML/HTTP, RESTful HTTP) is provided by Apache CXF and integration framework is provided by Apache Camel. Apache Karaf provides a lightweight OSGI-based runtime container. Fuse IDE is available along with JBDS to provide an easy-to-use integration development environment.

We encourage you to download JBoss Fuse, and see for yourself if it meets your needs. 

== Resources

- https://www.jboss.org/products/fuse/fusebyexample.html[FuseByExample] is a set of examples created by Fuse consultants based on their experience with customers.

== Articles

http://www.ossmentor.com/2014/02/devnation-by-and-for-developers.html[DevNation - By and For Developers]::
  AN OPEN SOURCE CONFERENCE, BY AND FOR DEVELOPERS ACROSS THE GLOBE April 13 - 16, 2014 | San Francisco, CA | USA...

http://www.ossmentor.com/2014/02/red-hat-summit-2014-agenda.html[Red Hat Summit 2014 Agenda]::
  In technology, and in life, we are always moving forward. There is no time to stand still. We must constantly evolve.   From a hobbyist's dream to a foundation...

http://www.ossmentor.com/2014/02/fuse-service-works-v6-is-ga.html[Fuse Service Works v6 is GA!]::
  We are very happy to announce the general availability of JBoss Fuse Service Works (FSW) v6.  It is documented and available for download on the customer support portal...