kramdown:
  :input: 'QuickStartParser'
generation:
  :in_processes: <%= ENV['AWE_PROC_COUNT'] || Parallel.processor_count %>
asciidoctor:
  :attributes:
    sectanchors: ''
slim|html:
  :format: :html
slim:
  :attr_list_delims:
    '(': ')'
    '[': ']'
download_manager_file_base_url: //developers.redhat.com/download-manager/file/
download_manager_base_url: https://developers.redhat.com
product_documentation_base_url: https://access.redhat.com/site/documentation/en-US/
product_forum_base_url: https://developer.jboss.org/en/products/
vimeo_client_id: 2589d6592dfd44bfec54f22edf766aedaf0fd5d7
vimeo_access_token: 1ad6583e71e183c3075a88d46ebb0675
change_frequency: daily
keycloak_account_url: https://developers.redhat.com/auth/realms/rhd/account/
keycloak_auth_url: https://developers.redhat.com/auth/
searchisko_warnings: _site/searchisko_warnings.json
application_name: Red Hat Developers
application_version: 1
under_development: false

deploy_base: &deploy
  host: rhd@filemgmt.jboss.org
  cdn_host: rhd@filemgmt.jboss.org
  cdn_path: /static_htdocs/rhd
  uncommitted: true

profile_base: &profile
  cdn_http_base: &cdn_http_base //static.jboss.org/rhd
  cdn_out_dir: &cdn_out_dir _tmp
  cdn_version: &cdn_version true
  log_faraday: true
  push_to_searchisko: true
  minify: &minify true
  robots:
    disallow: true
  deploy:
    <<: *deploy
  scss:
    :style: :compressed
    # Nice big hack:
    :cdn_http_base: *cdn_http_base
    :cdn_out_dir: *cdn_out_dir
    :minify: *minify
    :cdn_version: *cdn_version
  authenticate_google_books_api: true
  build_threads: 40
  # HACK!! Hacking around vimeo rate limit for now by using a local cache
  cache_type: :local

profiles:
  development: &development
    dcp_base_url: http://dcp.stage.jboss.org/
    dcp_base_protocol_relative_url: //dcp.stage.jboss.org/
    keycloak_account_url: https://developers.stage.redhat.com/auth/realms/rhd/account/
    keycloak_auth_url: https://developers.stage.redhat.com/auth/
    download_manager_file_base_url: //developers.stage.redhat.com/download-manager/file/
    download_manager_base_url: https://developers.stage.redhat.com
    log_faraday: true
    push_to_searchisko: false
    metrics: false
    client_side_error_logging: false
    authenticate_google_books_api: false
    build_threads: 0
    cache_type: :local
    broker: https://broker.stage.redhat.com/partner/drc/userMapping?redirect=

  docker: &docker
    <<: *development
    base_url: http://docker:4242/
    dcp_base_url: http://searchisko:8080/
<% if (ENV.key?('ACCESSIBLE_SLAVE_IP') && !ENV['ACCESSIBLE_SLAVE_IP'].empty?) %>
    dcp_base_protocol_relative_url: "//<%= ENV['ACCESSIBLE_SLAVE_IP'] %>:<%= ENV['SEARCHISKO_HOST_PORT'] %>/"
<% else %>
    dcp_base_protocol_relative_url: "//<%= 'docker' %>:<%= ENV['SEARCHISKO_HOST_PORT'] %>/"
<% end %>
    push_to_searchisko: true
    broker: https://broker.stage.redhat.com/partner/drc/userMapping?redirect=

  drupal_dev:
    <<: *docker
    base_url: http://docker/
    dcp_base_protocol_relative_url: //docker:<%= ENV['SEARCHISKO_HOST_PORT'] %>/
    drupal_base_url: http://drupal/

  drupal_pull_request:
    <<: *docker
    base_url: http://stumpjumper.lab4.eng.bos.redhat.com:<%= ENV['DRUPAL_HOST_PORT'] %>/
    dcp_base_protocol_relative_url: //stumpjumper.lab4.eng.bos.redhat.com:<%= ENV['SEARCHISKO_HOST_PORT'] %>/
    drupal_base_url: http://drupal/

  drupal_staging:
    <<: *profile
    base_url: http://developer-drupal.web.stage.ext.phx2.redhat.com/
    drupal_base_url: http://developer-drupal.web.stage.ext.phx2.redhat.com/
    download_manager_file_base_url: //developers.stage.redhat.com/download-manager/file/
    download_manager_base_url: https://developers.stage.redhat.com
    dcp_base_url: http://dcp.stage.jboss.org/
    dcp_base_protocol_relative_url: //dcp.stage.jboss.org/
    keycloak_account_url: https://developers.stage.redhat.com/auth/realms/rhd/account/
    keycloak_auth_url: https://developers.stage.redhat.com/auth/
    metrics: true
    client_side_error_logging: true
    dtm_code: //assets.adobedtm.com/2b327a0a54b320bf1bcdb5fa39a2b896027067d9/satelliteLib-9ec3c34e9d660fa2fcb85ced512c3a48dc09c0c5-staging.js
    deploy:
      <<: *deploy
      path: /stg_htdocs/it-rhd-stg-main

  drupal_production:
    <<: *profile
    base_url: http://developer-drupal.web.prod.ext.phx2.redhat.com/
    final_base_url: http://developers.redhat.com/
    drupal_base_url: http://developer-drupal.web.prod.ext.phx2.redhat.com/
    dcp_base_protocol_relative_url: //dcp2.jboss.org/
    dcp_base_url: http://dcp2.jboss.org/
    require_tag: true
    metrics: true
    client_side_error_logging: true
    disqus: jdf
    dtm_mode: //assets.adobedtm.com/2b327a0a54b320bf1bcdb5fa39a2b896027067d9/satelliteLib-9ec3c34e9d660fa2fcb85ced512c3a48dc09c0c5.js
    cache_type: :local
    robots:
      disallow: false
    deploy:
      <<: *deploy
      path: /www_htdocs/it-rhd
    broker: https://broker.redhat.com/partner/drc/userMapping?redirect=

  development_cdn:
    <<: *development
    cdn_http_base: &dev_cdn_http_base http://localhost:4242/cdn
    cdn_out_dir: &dev_cdn_out_dir _site
    cdn_version: &dev_cdn_version false
    scss:
      # Nice big hack:
      :cdn_http_base: *dev_cdn_http_base
      :cdn_out_dir: *dev_cdn_out_dir
      :cdn_version: *dev_cdn_version

  # Docker staging configuration (PR and Nightly)
  staging_docker:
    <<: *profile
    dcp_base_url: http://dcp.stage.jboss.org/
    dcp_base_protocol_relative_url: //dcp.stage.jboss.org/
#    dcp_base_url: http://searchisko:8080/
#    dcp_base_protocol_relative_url: //<%= ENV['ACCESSIBLE_SLAVE_IP'] %>:<%= ENV['SEARCHISKO_HOST_PORT'] %>/
    keycloak_account_url: https://developers.stage.redhat.com/auth/realms/rhd/account/
    keycloak_auth_url: https://developers.stage.redhat.com/auth/
    download_manager_file_base_url: //developers.stage.redhat.com/download-manager/file/
    download_manager_base_url: https://developers.stage.redhat.com

    cache_type: :local
    metrics: true
    client_side_error_logging: true
    broker: https://broker.stage.redhat.com/partner/drc/userMapping?redirect=
    deploy:
      <<: *deploy
      path: /stg_htdocs/it-rhd-stg

  # Pull Request configuration (Not with Docker)
  staging:
    <<: *profile
    dcp_base_protocol_relative_url: //<%= ENV['STAGE_SEARCHISKO_HOST'] %>:<%= ENV['STAGE_SEARCHISKO_PORT'] %>/
    dcp_base_url: http://<%= ENV['STAGE_SEARCHISKO_HOST'] %>:<%= ENV['STAGE_SEARCHISKO_PORT'] %>/
    keycloak_account_url: https://developers.stage.redhat.com/auth/realms/rhd/account/
    keycloak_auth_url: https://developers.stage.redhat.com/auth/
    download_manager_file_base_url: //developers.stage.redhat.com/download-manager/file/
    download_manager_base_url: https://developers.stage.redhat.com
    metrics: false
    client_side_error_logging: true
    broker: https://broker.stage.redhat.com/partner/drc/userMapping?redirect=
    deploy:
      <<: *deploy
      path: /stg_htdocs/it-rhd-stg

  # Main staging configuration (on IT's Infr)
  staging_main_it: &staging_main_it
    <<: *profile
    base_url: http://developers.stage.redhat.com/
    download_manager_file_base_url: //developers.stage.redhat.com/download-manager/file/
    download_manager_base_url: https://developers.stage.redhat.com
    dcp_base_url: http://dcp.stage.jboss.org/
    dcp_base_protocol_relative_url: //dcp.stage.jboss.org/
    keycloak_account_url: https://developers.stage.redhat.com/auth/realms/rhd/account/
    keycloak_auth_url: https://developers.stage.redhat.com/auth/
    metrics: true
    client_side_error_logging: true
    build_threads: 1
    dtm_code: //assets.adobedtm.com/2b327a0a54b320bf1bcdb5fa39a2b896027067d9/satelliteLib-9ec3c34e9d660fa2fcb85ced512c3a48dc09c0c5-staging.js
    broker: https://broker.stage.redhat.com/partner/drc/userMapping?redirect=
    deploy:
      <<: *deploy
      path: /stg_htdocs/it-rhd-stg-main

  # Octopus integration configuration
  octopus:
    <<: *staging_main_it
    base_url: http://developers-pr.stage.redhat.com/integration/octopus/
    deploy:
      <<: *deploy
      path: /stg_htdocs/it-rhd-stg/integration/octopus

  production:
    <<: *profile
    base_url: http://developers.redhat.com/
    dcp_base_protocol_relative_url: //dcp2.jboss.org/
    dcp_base_url: http://dcp2.jboss.org/
    require_tag: true
    metrics: true
    client_side_error_logging: true
    disqus: jdf
    dtm_mode: //assets.adobedtm.com/2b327a0a54b320bf1bcdb5fa39a2b896027067d9/satelliteLib-9ec3c34e9d660fa2fcb85ced512c3a48dc09c0c5.js
    broker: https://broker.redhat.com/partner/drc/userMapping?redirect=

    robots:
      disallow: false
    deploy:
      <<: *deploy
      path: /www_htdocs/it-rhd
