kramdown:
  :input: 'QuickStartParser'
asciidoctor:
  :attributes:
    sectanchors: ''
download_manager_file_base_url: //www.stage.jboss.org/download-manager/file/
product_documentation_base_url: https://access.redhat.com/site/documentation/en-US/
product_forum_base_url: https://developer.jboss.org/en/products/
vimeo_client_id: 2589d6592dfd44bfec54f22edf766aedaf0fd5d7
vimeo_access_token: 1ad6583e71e183c3075a88d46ebb0675
change_frequency: daily
keycloak_account_url: https://developers.redhat.com/auth/realms/rhd/account/
keycloak_auth_url: https://developers.redhat.com/auth/
searchisko_warnings: _site/searchisko_warnings.json
application_name: Red Hat Developers
application_version: 1
experiment_id: U10jDQ5OSNyz_vAuuUdggg

deploy_base: &deploy
  host: rhd@filemgmt.jboss.org
  cdn_host: rhd@filemgmt.jboss.org
  cdn_path: /static_htdocs/rhd
  uncommitted: true

profile_base: &profile
  cdn_http_base: &cdn_http_base //static.jboss.org/rhd
  cdn_out_dir: &cdn_out_dir _tmp
  cdn_version: &cdn_version true
  log_faraday: true
  push_to_searchisko: true
  minify: &minify true 
  robots: 
    disallow: true
  deploy:
    <<: *deploy
  scss:
    :style: :compressed
    # Nice big hack:
    :cdn_http_base: *cdn_http_base
    :cdn_out_dir: *cdn_out_dir
    :minify: *minify
    :cdn_version: *cdn_version
  authenticate_google_books_api: true
  build_threads: 40
  cache_type: :external

profiles:
  development: &development
    dcp_base_url: http://dcpbeta-searchisko.rhcloud.com/
    dcp_base_protocol_relative_url: //dcpbeta-searchisko.rhcloud.com/
    log_faraday: true
    push_to_searchisko: false
    metrics: false
    authenticate_google_books_api: false
    build_threads: 0
    cache_type: :local

  docker: &docker
    <<: *development
    base_url: http://docker:<%= ENV['AWESTRUCT_HOST_PORT'] %>/
    dcp_base_url: http://searchisko:8080/
    dcp_base_protocol_relative_url: //docker:<%= ENV['SEARCHISKO_HOST_PORT'] %>/

  drupal:
    <<: *docker
    base_url: http://<%= ENV['DRUPAL_HOST_IP'] %>:<%= ENV['DRUPAL_HOST_PORT'] %>/
    drupal_base_url: http://drupal/
  
  development_cdn: 
    <<: *development
    cdn_http_base: &dev_cdn_http_base http://localhost:4242/cdn
    cdn_out_dir: &dev_cdn_out_dir _site
    cdn_version: &dev_cdn_version false
    scss:
      # Nice big hack:
      :cdn_http_base: *dev_cdn_http_base
      :cdn_out_dir: *dev_cdn_out_dir
      :cdn_version: *dev_cdn_version
  
  # Pull Request configuration
  staging: 
    <<: *profile
    download_manager_file_base_url: //www.stage.jboss.org/download-manager/file/
    dcp_base_protocol_relative_url: //dcpbeta-searchisko.rhcloud.com/
    dcp_base_url: http://dcpbeta-searchisko.rhcloud.com/
    metrics: true
    deploy:
      <<: *deploy
      path: /stg_htdocs/rhd-stg
  
  # Main staging configuration
  staging_main: 
    <<: *profile
    download_manager_file_base_url: //www.stage.jboss.org/download-manager/file/
    dcp_base_protocol_relative_url: //dcp-stg.jboss.org/
    dcp_base_url: http://dcp-stg.jboss.org/
    keycloak_account_url: https://developers.stage.redhat.com/auth/realms/rhd/account/
    keycloak_auth_url: https://developers.stage.redhat.com/auth/
    metrics: true
    deploy:
      <<: *deploy
      path: /stg_htdocs/rhd-stg-main
  
  production:
    <<: *profile
    base_url: http://developers.redhat.com/
    dcp_base_protocol_relative_url: //dcpbeta-searchisko.rhcloud.com/
    dcp_base_url: http://dcpbeta-searchisko.rhcloud.com/
    require_tag: true
    metrics: true
    disqus: jdf
    robots:
      disallow: true
    deploy:
      <<: *deploy
      path: /www_htdocs/rhd

