:awestruct-layout: product-index
:linkattrs:

== Developer Studio

JBoss(R) Developer Studio provides superior support for your entire development lifecycle . It includes a broad set of tooling capabilities and support for multiple programming models and frameworks.

== Frameworks

TODO

== EAP

JBoss(R) Enterprise Application Platform 6 provides an innovative modular, cloud-ready architecture, powerful management and automation, and world class developer productivity. 

== Web Server

JBoss(R) Enterprise Application Platform 6 provides an innovative modular, cloud-ready architecture, powerful management and automation, and world class developer productivity. 

== Data Grid

Red Hat JBoss Data Grid is an intelligent, distributed caching solution that boosts application performance, provides greater deployment flexibility, and minimizes the overhead of standing up new applications.

== Portal

Red Hat JBoss Portal is a lean portal solution for building high-impact, self-service application

== Fuse Service Works

Red Hat JBoss Fuse Service Works is a service design, development and integration platform enabling organizations to transition to open hybrid cloud. 

== Data Virtualization

Red Hat JBoss Data Virtualization (formerly known as Red Hat JBoss Enterprise Data Services Platform) is useful for any organization struggling to gain operational and analytical insights from data dispersed and locked up in various business units, applications, and technology silos.

== Fuse

Red Hat JBoss Fuse is a small footprint Enterprise Service Bus (ESB) that lets you build, deploy and integrate applications and services.

== A-MQ

Red Hat JBoss A-MQ is a small footprint, high-performance, robust messaging platform that enables real-time integration between applications, services and devices. 

== BRMS

Red Hat JBoss Enterprise BRMS is a business process and decision management platform that combines Drools Expert, Drools Guvnor, Drools Fusion and JBoss jBPM in a single integrated distribution.

== Operations Network

Red Hat JBoss Operations Network provides enterprise-grade management capabilities across all of your JBoss development, test and production environments. 

