= Red Hat Products 
:awestruct-layout: product-index
:linkattrs:
:awestruct-status: green
:awestruct-description: Product and development information about Red Hat products


== Enterprise Linux

* Speeds application delivery across physical, virtual, and cloud environments using lightweight, portable containers. 
* IT efficiency on a stable foundation known for its mission-critical reliability and military-grade security.

== Satellite

The easiest way to manage Red Hat® Enterprise Linux®, keeping your systems running efficiently, properly secured, and compliant with various standards.

== OpenStack

Red Hat Enterprise Linux OpenStack Platform delivers an integrated foundation to create, deploy, and scale a secure and reliable public or private OpenStack cloud.

== EAP

Host your apps in an innovative, modular, cloud-ready architecture with powerful management, automation and developer productivity.

== Web Server

Red Hat Satellite server is an easy-to-use, advanced life-cycle management platform for your Red Hat Enterprise Linux infrastructure. Providing the tools to efficiently deploy, update, monitor, and manage systems, Red Hat Satellite helps reduce repetitive and time-consuming tasks.

== Data Grid

An in-memory data grid to accelerate application performance by offering fast, distributed data access, elastic scalability, and independence from the traditional data tier.

== Portal

A framework for the development of collaborative, highly integrated websites and self-service applications that create compelling user experiences.

== Developer Studio

A certified, Eclipse-based integrated development environment (IDE) for developing, testing, and deploying rich web applications, mobile web apps, transactional enterprise apps, and service-oriented architecture (SOA)-based integration apps and services.

== Operations Network

A key component of our middleware's managed solutions, providing a single point of control to deploy, manage, and monitor your middleware products, applications, and services.

== Fuse

A small-footprint enterprise service bus (ESB) that lets you build, deploy and integrate applications and services.

== A-MQ

A small-footprint, high-performance, robust messaging platform that enables real-time integration between applications, services and devices.

== Data Virtualization

A data virtualization tool useful for any organization struggling to gain operational and analytical insights from data dispersed and locked up in various business units, applications, and technology silos.  (Formerly known as JBoss Enterprise Data Services Platform).

== FSW

An SOA integration suite that lets you build, deploy, integrate, and present applications and services.

== BRMS

A rule-based programming platform built on Drools Expert, Drools Guvnor and Drools Fusion that allows users to capture rules that can be easily modified as the business changes without impacting static applications.

== BPM Suite

A business process and decision management platform that combines business rules management, business process management (BPM), and complex event processing.

== Cloud Infrastructure

A single-subscription offering that lets you build and manage an open, private Infrastructure-as-a-Service (IaaS) cloud and ease your way into a highly scalable, public-cloud-like infrastructure based on OpenStack®.

== CloudForms

A comprehensive IaaS cloud management platform that improves your virtual and cloud infrastructures with advanced capacity planning and resource management features.

== OpenStack Platform

Secure, scalable platform for building public and private clouds.

== OpenShift

An open, hybrid Platform-as-a-Service (PaaS) that lets developers quickly develop, host, scale, and deliver apps in the cloud.

== Certificate System

An enterprise software system that gives you a scalable, secure framework to establish and maintain trusted identities and keep communications private.

== Directory Server

An operating system-independent, network-based registry that lets administrators centrally store user identity and application information.

== Storage Server

Combines reliable Red Hat software with x86 commodity hardware, eliminating the need for high-cost proprietary storage systems.
