= JBoss Products 
:awestruct-layout: product-index
:linkattrs:
:awestruct-status: green
:awestruct-issues: [DEVELOPER-44]

== Developer Studio

A development environment that provides superior support for your entire development lifecycle. It includes a broad set of tooling capabilities and support for multiple programming models and frameworks.

////
== Frameworks

TODO
////

== EAP

An application platform for hosting your apps that provides an innovative modular, cloud-ready architecture, powerful management and automation, and world class developer productivity. 

== Web Server

A web server that combines Apache Web Server and Apache Tomcat to provide a single solution for large-scale websites and lightweight Java web applications.

== Data Grid

An in-memory data grid to accelerate application performance by offering fast, distributed data access, elastic scalability, and independence from the traditional data tier.

== Portal

A powerful, lean portal solution for building high-impact, self-service applications and leveraging maximum value from your existing systems.

== Fuse Service Works

A service design, development and integration platform enabling organizations to transition to open hybrid cloud. 

== Data Virtualization

A data virtualization tool useful for any organization struggling to gain operational and analytical insights from data dispersed and locked up in various business units, applications, and technology silos. (formerly known as Red Hat JBoss Enterprise Data Services Platform)

== Fuse

A small footprint Enterprise Service Bus (ESB) that lets you build, deploy and integrate applications and services.

== A-MQ

A small footprint, high-performance, robust messaging platform that enables real-time integration between applications, services and devices. 

== BRMS

A business process and decision management platform that combines Drools Expert, Drools Guvnor, Drools Fusion and JBoss jBPM in a single integrated distribution.

== BPM Suite

A platform for Business Process Management (BPM). It enables enterprise business and IT users to document, simulate, manage, automate and monitor business processes and policies. It is designed to empower business and IT users to collaborate more effectively, so business applications can be changed more easily and quickly.

== Operations Network

Provides enterprise-grade management capabilities across all of your JBoss development, test and production environments. 

