:awestruct-layout: product-index
:linkattrs:

[discrete]
== Developer Studio

A development environment that provides superior support for your entire development lifecycle. It includes a broad set of tooling capabilities and support for multiple programming models and frameworks.

////
== Frameworks

TODO
////

[discrete]
== EAP

An application platform for hosting your apps that provides an innovative modular, cloud-ready architecture, powerful management and automation, and world class developer productivity. 

[discrete]
== Web Server

A web server that combines Apache Web Server and Apache Tomcat to provide a single solution for large-scale websites and lightweight Java web applications.

[discrete]
== Data Grid

An intelligent, distributed caching solution that boosts application performance, provides greater deployment flexibility, and minimizes the overhead of standing up new applications.

[discrete]
== Portal

A lean portal solution for building high-impact, self-service application

[discrete]
== Fuse Service Works

A service design, development and integration platform enabling organizations to transition to open hybrid cloud. 

[discrete]
== Data Virtualization

A data virtualization tool useful for any organization struggling to gain operational and analytical insights from data dispersed and locked up in various business units, applications, and technology silos. (formerly known as Red Hat JBoss Enterprise Data Services Platform)

[discrete]
== Fuse

A small footprint Enterprise Service Bus (ESB) that lets you build, deploy and integrate applications and services.

[discrete]
== A-MQ

A small footprint, high-performance, robust messaging platform that enables real-time integration between applications, services and devices. 

[discrete]
== BRMS

A business process and decision management platform that combines Drools Expert, Drools Guvnor, Drools Fusion and JBoss jBPM in a single integrated distribution.

[discrete]
== Operations Network

Provides enterprise-grade management capabilities across all of your JBoss development, test and production environments. 

