:awestruct-layout: product-index
:linkattrs:

== Developer Studio

[features]#Features http://www.openshift.com[Openshift] http://www.jboss.org[Visual Editor] http://www.jboss.org[Hot Deployments]#

JBoss(R) Developer Studio provides superior support for your entire development lifecycle . It includes a broad set of tooling capabilities and support for multiple programming models and frameworks.

== Frameworks

[features]#Features TODO#

TODO

== EAP

[features]#Features http://www.jboss.org[Java EE 6] http://www.jboss.org[Cloud Ready] http://www.jboss.org[INCREASED EFFICIENCY]#

JBoss(R) Enterprise Application Platform 6 provides an innovative modular, cloud-ready architecture, powerful management and automation, and world class developer productivity. 

== Web Server

[features]#Features http://www.jboss.org[Java EE 6] http://www.jboss.org[Cloud Ready] http://www.jboss.org[INCREASED EFFICIENCY]#

JBoss(R) Enterprise Application Platform 6 provides an innovative modular, cloud-ready architecture, powerful management and automation, and world class developer productivity. 

== Data Grid

[features]#Features http://www.jboss.org[CROSS DATACENTER REPLICATION] http://www.jboss.org[MULTIPLE APIS TO ACCESS YOUR DATA, YOUR WAY] http://www.jboss.org[FLEXIBILITY FOR OPEN HYBRID CLOUD ENVIRONMENTS]#

Red Hat JBoss Data Grid is an intelligent, distributed caching solution that boosts application performance, provides greater deployment flexibility, and minimizes the overhead of standing up new applications.

== Portal

[features]#Features http://www.jboss.org[SOCIAL MEDIA INTEGRATION] http://www.jboss.org[MOBILE WEBSITES] http://www.jboss.org[PUBLIC NAVIGATION APIS]#

Red Hat JBoss Portal is a lean portal solution for building high-impact, self-service application

== Fuse Service Works

[features]#Features http://www.jboss.org[Pattern based development] http://www.jboss.org[High-performance messaging] http://www.jboss.org[web Service/REST]#

Red Hat JBoss Fuse Service Works is a service design, development and integration platform enabling organizations to transition to open hybrid cloud. 

== Data Virtualization

[features]#Features http://www.jboss.org[NEW BIG DATA AND CLOUD INTEGRATION] http://www.jboss.org[NEW BUSINESS DASHBOARD] http://www.jboss.org[ENHANCED DEVELOPER PRODUCTIVITY]#

Red Hat JBoss Data Virtualization (formerly known as Red Hat JBoss Enterprise Data Services Platform) is useful for any organization struggling to gain operational and analytical insights from data dispersed and locked up in various business units, applications, and technology silos.

== Fuse

[features]#Features http://www.jboss.org[Dynamic Configuration] http://www.jboss.org[Security Framework] http://www.jboss.org[Enterprise integration router]#

Red Hat JBoss Fuse is a small footprint Enterprise Service Bus (ESB) that lets you build, deploy and integrate applications and services.

== A-MQ

[features]#Features http://www.jboss.org[Cross-language client] http://www.jboss.org[Multi-protocol support] http://www.jboss.org[Support for large messages]#

Red Hat JBoss A-MQ is a small footprint, high-performance, robust messaging platform that enables real-time integration between applications, services and devices. 

== BRMS

[features]#Features http://www.jboss.org[BUSINESS RULES] http://www.jboss.org[BUSINESS PROCESS MANAGEMENT] http://www.jboss.org[COMPLEX EVENT PROCESSING]#

Red Hat JBoss Enterprise BRMS is a business process and decision management platform that combines Drools Expert, Drools Guvnor, Drools Fusion and JBoss jBPM in a single integrated distribution.

== Operations Network

[features]#Features TODO#

Red Hat JBoss Operations Network provides enterprise-grade management capabilities across all of your JBoss development, test and production environments. 

