name: Red Hat JBoss Web Server
abbreviated_name: JBoss Web Server
documentation_path: JBoss_Enterprise_Web_Server
documentation_minor_version: 2
current_version: 2.0.0.GA
guides:
  Release_Notes:
  Hibernate_Core_Guide:
  HTTP_Connectors_Load_Balancing_Guide:
  Installation_Guide:
downloads:
#  2.0.1.GA:
#    release_date: 2013-07-03
#    description: Combines market-leading open source technologies with enterprise capabilities to provide a single solution for large-scale websites and light-weight Java web applications.
#    assets:
#      source:
#        size: 33mb
#      zip-SPARC64:
#        size: 26mb
#        name: Zip (Solaris 10 & 11 Distribution 64bit)
#      zip-solaris64:
#        size: 26mb
#        name: Zip (Solaris 10 & 11 Distribution 64bit)
#      zip-solaris32:
#        size: 26mb
#        name: Zip (Solaris 10 & 11 Distribution 32bit)
#      zip-windows64:
#        size: 25mb
#        name: Zip (Windows Distribution 64bit)
#      zip-windows32:
#        size: 25mb
#        name: Zip (Windows Distribution 32bit)
#      zip-rhel64:
#        size: 13mb
#        name: Zip (RHEL 6 Distribution 64bit)
#      zip-rhel32:
#        size: 13mb
#        name: Zip (RHEL 6 Distribution 32bit)
#      zip-rhel64:
#        size: 13mb
#        name: Zip (RHEL 5 Distribution 64bit)
#      zip-rhel32:
#        size: 13mb
#        name: Zip (RHEL 5 Distribution 32bit)
#  2.0.0.GA:
#    release_date: 2012-11-07
#    description: Combines market-leading open source technologies with enterprise capabilities to provide a single solution for large-scale websites and light-weight Java web applications.
#    assets:
#      source:
#        size: 31mb
#      zip-solaris64:
#        size: 26mb
#        name: Zip (Solaris 10 & 11 Distribution 64bit)
#      zip-solaris32:
#        size: 26mb
#        name: Zip (Solaris 10 & 11 Distribution 32bit)
#      zip-windows64:
#        size: 25mb
#        name: Zip (Windows Distribution 64bit)
#      zip-windows32:
#        size: 24mb
#        name: Zip (Windows Distribution 32bit)
#      zip-rhel64:
#        size: 13mb
#        name: Zip (RHEL 6 Distribution 64bit)
#      zip-rhel32:
#        size: 13mb
#        name: Zip (RHEL 6 Distribution 32bit)
#      zip-rhel64:
#        size: 14mb
#        name: Zip (RHEL 5 Distribution 64bit)
#      zip-rhel32:
#        size: 14mb
#        name: Zip (RHEL 5 Distribution 32bit)
upstream_projects:

