<?php

/**
 * @file
 * Contains rhd_assemblies.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Component\Utility\Html;
use Drupal\node\Entity\Node;
use Drupal\rhd_assemblies\Service\DownloadManagerApi;

/**
 * Implements hook_help().
 */
function rhd_assemblies_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the rhd_assemblies module.
    case 'help.page.rhd_assemblies':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom assemblies for RHD') . '</p>';
      return $output;

    default:
  }
}

function rhd_assemblies_theme_registry_alter(&$theme_registry) {
  $path = drupal_get_path('module', 'rhd_assemblies');

  // Assembly types with a default template
  // defined in this module
  $types = [
    'blog_posts',
  ];

  foreach ($types as $type) {
    if (isset($theme_registry['assembly']) && !isset($theme_registry['assembly__' . $type])) {
      $theme_registry['assembly__' . $type] = $theme_registry['assembly'];
      $theme_registry['assembly__' . $type]['template'] = 'assembly--' . str_replace('_', '-', $type);
      $theme_registry['assembly__' . $type]['theme_path'] = $path;
      $theme_registry['assembly__' . $type]['path'] = $path . '/templates';
    }
  }
}

function rhd_assemblies_theme($existing, $type, $theme, $path) {
  $theme = [];
  $theme['wordpress_post_teaser'] = [
    'template' => 'wordpress-post-teaser',
    'variables' => [
      'post' => NULL,
      'media' => NULL,
      'categories' => NULL,
      'date' => NULL,
    ],
  ];
  $theme['wordpress_post_tile'] = [
    'template' => 'wordpress-post-tile',
    'variables' => [
      'post' => NULL,
      'media' => NULL,
    ],
  ];
  return $theme;
}

function rhd_assemblies_entity_presave(EntityInterface $entity) {
  if ($entity->getEntityTypeId() == 'assembly' && in_array($entity->bundle(), ['node_reference', 'wordpress_post_reference'])) {
    if ($entity->bundle() == 'node_reference') {
      $field = $entity->get('field_node_reference')->getValue();
      $node_id = reset($field)['target_id'];
      $node = Node::load($node_id);
      $title = $node->label();
      $entity->set('name', $title);
    }

    if ($entity->bundle() == 'wordpress_post_reference') {
      $field = $entity->get('field_post_reference')->getValue();
      $title = reset($field)['title'];
      $entity->set('name', $title);
    }
  }
}

/**
 * Implements hook_preprocess_assembly().
 */
function rhd_assemblies_preprocess_assembly(&$variables) {
  // Make assembly ID match pattern used for on page navigation.
  $parent = $variables['elements']['#parent'];
  if ($parent) {
    $id = $variables['elements']['#assembly']->id();
    $css_id = Html::cleanCssIdentifier('assembly-' . $parent['field_name'] . '-' . $id);
    $variables['attributes']->offsetSet('id', $css_id);
  }

  $assembly = $variables['assembly'];

  // Product Download List assemblies.
  if (isset($assembly) && $assembly->bundle() == 'product_download_list') {
    $product_id = $assembly->get('field_product')->getValue()[0]['target_id'];
    $product = Node::load($product_id);

    if (isset($product->field_product_machine_name)) {
      $download_manager_api = \Drupal::service('rhd_assemblies.download_manager_api');
      $product_downloads = $download_manager_api->getContentById(
        $product->get('field_product_machine_name')->value
      );

      foreach ($product_downloads[0]->productVersions as $key => $version) {
        $versions[$key] = $version;

        foreach ($version->files as $file_key => $file) {
          $versions[$key]->files[$file_key]->fileSize = format_size($file->fileSize);
        }
      }

      $variables['versions'] = $versions;
    }
  }
}
