import DPSearchActiveFilters from './dp-search-active-filters';
import DPSearchApp from './dp-search-app';
import DPSearchBox from './dp-search-box';
import DPSearchFilterActiveItem from './dp-search-filter-active-item';
import DPSearchFilterGroup from './dp-search-filter-group';
import DPSearchFilterItem from './dp-search-filter-item';
import DPSearchFilters from './dp-search-filters';
import DPSearchModalFilters from './dp-search-modal-filters';
import DPSearchOneBox from './dp-search-onebox';
import DPSearchQuery from './dp-search-query';
import DPSearchResultCount from './dp-search-result-count';
import DPSearchResult from './dp-search-result';
import DPSearchResults from './dp-search-results';
import DPSearchSortPage from './dp-search-sort-page';
import DPSearchURL from './dp-search-url';

new DPSearchActiveFilters();
new DPSearchApp();
new DPSearchBox();
new DPSearchFilterActiveItem();
new DPSearchFilterGroup();
new DPSearchFilterItem();
new DPSearchFilters();
new DPSearchModalFilters();
new DPSearchOneBox();
new DPSearchQuery();
new DPSearchResultCount();
new DPSearchResult();
new DPSearchResults();
new DPSearchSortPage();
new DPSearchURL();
