name: Red Hat JBoss Fuse
abbreviated_name: JBoss Fuse
tagline: A small footprint, flexible, open source ESB
current_version: 6.0.0.GA
downloads:
  6.0.0.GA:
    release_date: 2013-04-10
    description: Our small footprint Enterprise Service Bus (ESB) that can be moved into production with a Red Hat subscription.
    assets:
      zip-full:
        size: 568mb
        name: Zip (Full Install)
      zip-medium:
        size: 202mb
        name: Zip (Medium Install)
      ide-macosx:
        size: 209mb
        name: Fuse IDE (MacOS X)
      ide-win32:
        size: 210mb
        name: Fuse IDE (Windows 32bit)
      ide-win32_64:
        size: 210mb
        name: Fuse IDE (Windows 64bit)
      ide-linux:
        size: 210mb
        name: Fuse IDE (Linux 32bit)
      ide-linux_64:
        size: 210mb
        name: Fuse IDE (Linux 64bit)
documentation_path: JBoss_Fuse
guides:
  API_Reference:
  Cloud_Computing_with_Fabric:
  Configuring_and_Running_JBoss_Fuse:
  Configuring_Web_Service_Endpoints:
  Console_Reference:
  Deploying_into_the_Container:
  Developing_Apache_CXF_Interceptors:
  Developing_Applications_Using_JAX-WS:
  Developing_RESTful_Web_Services:
  EIP_Component_Reference:
  EIP_Transaction_Guide:
  Getting_Started:
  Glossary:
  Implementing_Enterprise_Integration_Patterns:
  Installation_Guide:
  Installing_the_Fuse_Developer_Tools:
  Managing_OSGi_Dependencies:
  Migration_Guide:
  Performance_Metrics_Reference:
  Product_Introduction:
  Programming_EIP_Components:
  Release_Notes:
   formats:
      html: 
        url: https://access.redhat.com/site/documentation/en-US/JBoss_Fuse/6.0/html/Release_Notes/files/front.html 
      html-single:
        url: https://access.redhat.com/site/documentation/en-US/JBoss_Fuse/6.0/html-single/Release_Notes/index.html
      pdf:
        url: https://access.redhat.com/site/documentation/en-US/JBoss_Fuse/6.0/pdf/Release_Notes/JBoss_Fuse-6.0-Release_Notes-en-US.pdf
      epub: 
        url: https://access.redhat.com/site/documentation/en-US/JBoss_Fuse/6.0/epub/Release_Notes/JBoss_Fuse-6.0-Release_Notes-en-US.epub
  Routing_Expression_and_Predicate_Languages:
  Tutorials:
  Using_Java_Business_Integration:
  Using_the_Apache_CXF_Binding_Component:
  Using_the_File_Binding_Component:
  Using_the_Fuse_Developer_Tools:
  Using_the_JMS_Binding_Component:
  Using_the_Management_Console:
  Using_the_Web_Services_Bindings_and_Transports:
  Web_Services_and_Routing_with_Camel_CXF:
  Web_Services_Security_Guide:
  Writing_WSDL_Contracts:
  XML_Configuration_Reference:

