:awestruct-layout: product-overview

== Overview

Red Hat JBoss BRMS is a business process and decision management platform that combines:

- Drools Expert,
- Drools Guvnor,
- Drools Fusion and
- JBoss jBPM in a single integrated distribution.

Rule and process definitions are stored and managed via the included repository and can be accessed via the authoring tools or through REST and WebDAV APIs.  Included also are the runtime engines for automating rule & process execution, either embedded directly in Java applications or deployable on JBoss EAP.

DOWNLOAD JBoss BRMS and explore the tools for authoring business rules and BPMN2 process flows, provided as both standalone web applications and plug-ins for JBoss Developer Studio.  

== Resources

- http://www.schabell.org/2013/01/jboss-brms-customer-evaluation-demo-update.html[Customer Evaluation Demo]
- http://www.schabell.org/2013/01/jboss-brms-rewards-demo-update.html[Employee Rewards Demo]
- https://access.redhat.com/site/documentation/JBoss_Enterprise_BRMS_Platform/[JBoss BRMS Documentation]

