:awestruct-layout: product-resources

== Overview
Below are materials for the Red Hat JBoss Business Rules Management System (BRMS) . These resources will get you up and running with this product, to run a demo, kick start a Proof of Concept (PoC), or just to let you explore the use cases that these products can cover.

== More Resources

http://www.jboss.org[What is a Rules Engine?]::
  Have an application with many business rules or quickly evolving business logic?  Learn how using a rule engine will keep your code clean and streamlined.

http://www.jboss.org[What is Business Process Management?]::
  Learn how adding workflow with automated, human and timed tasks can simplify your development process.

http://www.jboss.org[What is Complex Event Processing?]::
  Get an introduction into complex event processing.

http://www.jboss.org[Red Hat JBoss Middleware Webinar — Are You Ready to Rumble with JBoss Integration & BPM]::
  There will be an interesting webinar on July 23, 2013 that will take you on a tour of integration and business process management. This will feature ...
http://www.jboss.org[Red Hat JBoss Middleware Webinar — Are You Ready to Rumble with JBoss Integration & BPM]::
  There will be an interesting webinar on July 23, 2013 that will take you on a tour of integration and business process management. This will feature ...

