<?php
/**
 * @file
 * Primary hook implementations for Metatag:Facebook.
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function metatag_facebook_ctools_plugin_api($owner, $api) {
  if ($owner == 'metatag' && $api == 'metatag') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_preprocess_html().
 */
function metatag_facebook_preprocess_html(&$variables) {
  $variables['rdf_namespaces'] .= "\n  xmlns:fb=\"http://ogp.me/ns/fb#\"";
}

/*
fb:admins
fb:app_id
*/
