name: Red Hat JBoss BRMS
abbreviated_name: JBoss BRMS
product_logo: brms.png
has_installer: true
current_version: 6.1.0.GA
documentation_minor_version: 6.1
intro_video: https://vimeo.com/95600665
vimeo_album: http://vimeo.com/album/2982444
youtube_album: https://www.youtube.com/playlist?list=PLf3vm0UK6HKr0DPn1NaTmB-DY5WGeMtfN
skip_installation_instructions: true
skip_maven_instructions: true
index:
  desc: |
    A robust business rules management system (BRMS) that gives business decision makers the ability to quickly create and change business rules.
guides: 
  Getting_Started_Guide:
  Release_Notes:
  User_Guide:
  Business_Resource_Planner_Guide:
    formats:
      html:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_BPM_Suite/6.1/html/Business_Resource_Planner_Guide/index.html
      html-single:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_BPM_Suite/6.1/html-single/Business_Resource_Planner_Guide/index.html
      epub:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_BPM_Suite/6.1/epub/Business_Resource_Planner_Guide/Red_Hat_JBoss_BPM_Suite-6.1-Business_Resource_Planner_Guide-en-US.epub
      pdf:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_BPM_Suite/6.1/pdf/Business_Resource_Planner_Guide/Red_Hat_JBoss_BPM_Suite-6.1-Business_Resource_Planner_Guide-en-US.pdf  
default_download_artifact_type: installer
description: 'A rule-based programming platform built on Drools Expert, Drools Guvnor, and Drools Fusion that allows users to capture rules that can be easily modified as the business changes without impacting static applications.'
downloads:
  # 6.0.2 is an exclusion to the "no micros through $0 dev program
  6.1.0.GA:
    description: Red Hat JBoss BRMS 6.0.2 is an incremental bug fix release over the 6.0.1 version.
    tag_line: Built in centralized decision server, collaborative user interface, expanded platform certifications and enhanced stability of the platform. Includes full support for Business Resource Planner that offers ability to build resource optimized solutions.
    release_date: 2015-04-16
    assets:
      installer:
        size: 156mb
      zip:
        artifacts:
          deployable:
            size: 163mb
      zip_planner:
        size: 89mb
        name: Optaplanner
      example:
        size: 4mb
        name: Quickstarts
      zip_supplemental:
        size: 71mb
        name: Supplemental Tools
      release_notes:
      source:
        size: 194mb
  6.0.2.GA:
    description: Red Hat JBoss BRMS 6.0.2 is an incremental bug fix release over the 6.0.1 version.
    tag_line: This release brings in 250+ bug fixes, support for IBM Websphere, certification on RHEL7 and several new quick starts.
    release_date: 2014-06-30
    assets:
      installer:
        size: 265mb
      zip:
        artifacts:
          deployable:
            size: 140mb
      maven_repo:
        size: 142mb
        name: Maven Repository
        filename: bpms-brms-6.0.2.GA-redhat-5-maven-repository.zip
      zip_planner:
        size: 53mb
        name: Optaplanner
        filename: jboss-bpmsuite-6.0.2.GA-zip_planner.zip
      release_notes:
      source:
        size: 150mb
        filename: jboss-bpmsuite-6.0.2.GA-source.zip
  # 6.0.1 is an exclusion to the "no micros through $0 dev program
  6.0.1.GA:
    release_date: 2014-04-03
    description: A business process and decision management platform that combines Drools Expert, Drools Guvnor, Drools Fusion and JBoss jBPM in a single integrated distribution.
    assets:
      installer:
        size: 272mb
      zip:
        artifacts:
          deployable:
            size: 221mb
      maven_repo:
        size: 280mb
        name: Maven Repository
        filename: jboss-bpmsuite-6.0.1.GA-maven_repo.zip
      zip_planner:
        size: 55mb
        name: Optaplanner
        filename: jboss-bpmsuite-6.0.1.GA-zip_planner.zip
      release_notes:
      source:
        size: 177mb
        filename: jboss-bpmsuite-6.0.1.GA-source.zip
  6.0.0.GA:
    release_date: 2014-02-05
    description: A business process and decision management platform that combines Drools Expert, Drools Guvnor, Drools Fusion and JBoss jBPM in a single integrated distribution.
    assets:
      installer:
        size: 258mb
      zip:
        artifacts:
          deployable:
            size: 174mb
      zip_planner:
        size: 55mb
        name: Optaplanner
      release_notes:
      source:
        size: 154mb
        filename: jboss-bpmsuite-6.0.1.GA-source.zip 
upstream_projects:
  - optaplanner
  - drools
  - guvnor
#  - uberfire
featured_items:
  - image_url: http://design.jboss.org/jbossdeveloper/sitedesign/jbossdeveloper_1_0/makerfiles/images/developermaterials_brms.png
    url: /quickstarts/brms/helloworld-brms
evaluation: https://access.redhat.com/products/red-hat-jboss-brms/evaluation
