:awestruct-layout: product-overview
:leveloffset: 1

== Overview

Red Hat JBoss BPM Suite is the JBoss platform for Business Process Management (BPM). It enables enterprise business and IT users to document, simulate, manage, automate and monitor business processes and policies. It is designed to empower business and IT users to collaborate more effectively, so business applications can be changed more easily and quickly.


== Features1

=== Business Process Management

Create, test, deploy and monitor BPMN2-based business processes to optimize enterprise workflows and automate critical processes.

== Icon1

[.fa .fa-random .fa-5x .fa-fw]#&nbsp;#


== Features2

=== Complex Event and Rule Processing

Includes all the business rules and event processing capabilities of Red Hat JBoss BRMS.

== Icon2
[.fa .fa-bell-o .fa-5x .fa-fw]#&nbsp;#


== Features3

=== Business Activity Monitoring

Easily create real-time dashboards to monitor key performance indicators for running processes and activities.

== Icon3

[.fa .fa-tachometer .fa-5x .fa-fw]#&nbsp;#

== Detail

JBoss BPM Suite combines all the decision management and event processing capabilities of Red Hat JBoss BRMS with the
advanced BPM tools and runtime from the jBPM project, to create a single, integrated platform for business process and decision management.

Download JBoss BPM Suite and explore the tools for authoring, BPMN2 process flows and business rules, provided as both
standalone web applications and plug-ins for JBoss Developer Studio.

=== JBoss Business Resource Planner
JBoss Business Resource Planner is a lightweight, embeddable planning engine. It helps organizations that provide products
or services with a limited set of constrained resources (employees, assets, time and money). Business Resource Planner
enables developers to solve constraint satisfaction problems efficiently, optimizing resource usage to do more business with fewer resources.

== Resources

http://howtojboss.com/2014/04/09/red-hat-jboss-brms-bpm-suite-demo-projects-updated-for-6-0-1-ga-product/[Red Hat JBoss BRMS & BPM Suite Demo Projects Updated for 6.0.1.GA Product]::
  Last week when the latest JBoss BRMS & JBoss BPM Suite products released version 6.0.1.GA we highlighted the new maven
  repository artifacts and how you can make use of them.

http://howtojboss.com/2014/04/07/red-hat-jboss-brms-online-workshop-building-the-cool-store-lab-5-create-guided-rules/[Red Hat JBoss BRMS – Online Workshop Building The Cool Store (Lab 5 Create Guided Rules)]::
  We are back with this weeks episode in the JBoss Business Rules Management System (BRMS) & Business Process Management (BPM) Suite online workshop series.

http://howtojboss.com/2014/04/04/red-hat-jboss-brms-jboss-bpm-suite-6-0-1-maven-repository-pom-configuration/[Red Hat JBoss BRMS and JBoss BPM Suite 6.0.1 Maven Repository POM Configuration]::
  The new JBoss BRMS & JBoss BPM Suite was released yesterday bringing a lot of new improvements, fixes, and features.
