:awestruct-layout: product-overview
:leveloffset: 1

== Overview

Red Hat JBoss BPM Suite is the JBoss platform for Business Process Management (BPM). It enables enterprise business and IT users to document, simulate, manage, automate and monitor business processes and policies. It is designed to empower business and IT users to collaborate more effectively, so business applications can be changed more easily and quickly.


== Features1

=== Business Process Management

Create, test, deploy and monitor BPMN2-based business processes to optimize enterprise workflows and automate critical processes.

== Icon1

[.fa .fa-random .fa-5x .fa-fw]#&nbsp;#


== Features2

=== Complex Event and Rule Processing

Includes all the business rules and event processing capabilities of Red Hat JBoss BRMS.

== Icon2
[.fa .fa-bell-o .fa-5x .fa-fw]#&nbsp;#


== Features3

=== Business Activity Monitoring

Easily create real-time dashboards to monitor key performance indicators for running processes and activities.

== Icon3

[.fa .fa-tachometer .fa-5x .fa-fw]#&nbsp;#

== Detail

JBoss BPM Suite combines all the decision management and event processing capabilities of Red Hat JBoss BRMS with the
advanced BPM tools and runtime from the jBPM project, to create a single, integrated platform for business process and decision management.

Download JBoss BPM Suite and explore the tools for authoring, BPMN2 process flows and business rules, provided as both
standalone web applications and plug-ins for JBoss Developer Studio.

=== JBoss Business Resource Planner
JBoss Business Resource Planner is a lightweight, embeddable planning engine. It helps organizations that provide products
or services with a limited set of constrained resources (employees, assets, time and money). Business Resource Planner
enables developers to solve constraint satisfaction problems efficiently, optimizing resource usage to do more business with fewer resources.

== Resources

http://www.schabell.org/2014/07/redhat-jboss-bpmsuite-product-demos-6.0.2-updated.html[Red Hat JBoss BPM Suite Product Demos]::
  With the release of the JBoss BPM Suite version 6.0.2.GA product we wanted to get all the demos updated and out to you for evaluation as fast as possible.

http://www.schabell.org/2014/06/real-life-bpmpaas-jboss-bpmsuite-customer-evaluation-demo.html[Red Hat JBoss BPM PaaS Demo]::
This was developed and have put together some automated cartridge installation projects that kick start you with pre-loaded demo projects.

http://www.schabell.org/search/label/Tips%26Tricks[Red Hat JBoss BPM Tips and Tricks]::
This weeks tips and tricks article will help you to keep your current JBoss BPM Suite and JBoss Business Rules Management System (BRMS) running like a fine tuned machine.