:awestruct-layout: product-resources

== More Resources

http://www.redhat.com/resourcelibrary/whitepapers/open-source-bpm-whitepaper[Is an open source business process management solution right for you?]::
  Increased availability of highly functional enterprise open source business process management (BPM) technology is bringing
  the benefits of BPM solutions within reach of more companies and projects. If you are considering deploying BPM solutions,
  but have been daunted by the cost, footprint, risk, lack of flexibility, or complexity of proprietary options, an
  enterprise open source approach may be just what you are looking for.

http://www.redhat.com/resourcelibrary/whitepapers/red-hat-jboss-bpm-suite-6-technology-overview[Red Hat JBoss BPM Suite 6 technology overview]
  A business process initiative can be a challenge. Red Hat速 JBoss速 BPM Suite incorporates all the key elements needed
  by business process management (BPM) projects to document, simulate, manage, automate, and monitor business processes
  and policies. It begins by bridging the gap in communication between business and IT, fostering more effective
  collaboration so changes can be made more easily and quickly.

http://www.redhat.com/about/events-webinars/webinars/2013-06-06-BRMS-in-action[Red Hat JBoss BRMS in action]
  Having a solid business rules management system (BRMS) can help you create an application foundation that can handle the unexpected.
  Join our webinar to see a live demo of Red Hat速 JBoss速 BRMS and discover the advantages of maintaining business rules outside of application code.
