:awestruct-layout: product-get-started
:awestruct-interpolate: true

== Prerequisites section title
Prerequisites

== Prerequisites section
1. Java SE Development Kit 8 (JDK), we recommend OpenJDK or Oracle JDK.


== Step1 Duration
5 minutes

== Step2 Duration
5 minutes



== Step1 Content

*Download, install and configure JBoss A-MQ:*

1. *Download and extract:*
+
a. Download the latest version of Red Hat JBoss A-MQ. The latest
at the time of this writing is link:#{site.download_manager_file_base_url}/jboss-amq-6.3.0.GA.zip[Red Hat JBoss A-MQ 6.3.0 GA].
b. Unzip JBoss-AQ to any destination. The document will refer to this directory as AMQ_HOME
* On Windows or Mac, you can extract the contents of the ZIP archive by double clicking on the ZIP file.
* On Red Hat Enterprise Linux, open a terminal window in the target machine and navigate to where the ZIP file was downloaded. Extract the ZIP file by executing the following command:
+
`unzip jboss-a-mq-6.2.1.redhat-084.zip`
+
2. *Add users to A-MQ:*
+
Edit the file `AMQ_HOME/etc/user.properties`. Uncomment the last line so that systems can connect and access the message broker. The last line of the user.properties file has a `#` mark as the first character. Delete it and save the file. The edited last line should now look similar to this:
+
`admin=admin,admin,manager,viewer,Operator,Maintainer,Deployer, Auditor,Administrator,SuperUser`
+
3. *Start the A-MQ broker:* Scripts to start and stop the A-MQ broker are found within the `AMQ_HOME/bin` directory.
* For Windows: Double-click on the `AMQ/bin/start.bat` file and accept security pop-ups as they appear.
* For Red Hat Enterprise Linux and Mac: Execute the following command:
+
`AMQ_HOME/bin/start`
+
TIP: To check the status of the A-MQ broker you can execute the status script found in the same directory as the start script. To learn more about the various scripts see the link:https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_A-MQ/6.2/html/Console_Reference/index.html[customer portal].​
+
video::184305760[vimeo]

+
* *Next Steps:* Congratulate yourself. You have just installed and started the JBoss A-MQ Broker. Next up, Install the developer environment...

== Step2 Content
*Connecting to A-MQ:*

1. *Current runtime status:*
+
a. You may execute following command to check thes messages have been enqueue/dequeued

* For Linux/MAC:
+
`AMQ_HOME/bin/client activemq:dstat`

* For Windows:
+
`AMQ_HOME\bin\client.bat activemq:dstat`
    
b. Or simply go to the adminstration console and login with *ID:admin* and *PASSWORD:admin*
+
`http://localhost:8181`


2. *Produce and consume messages*
+
a. Sending messages to broker

* For Linux/MAC:
+
`AMQ_HOME/bin/client "activemq:producer --user <Username> --password <Password>"`

* For Windows:
+
`AMQ_HOME\bin\client.bat "activemq:producer --user <Username> --password <Password>"`

b. Consume messages from broker:

* For Linux/MAC:
+
`AMQ_HOME/bin/client "activemq:consumer --user <Username> --password <Password>"`

* For Windows:
+
`AMQ_HOME\bin\client.bat "activemq:consumer --user <Username> --password <Password>"`
+

video::184305594[vimeo]

+

Congratulate yourself! You’ve just sent and received messages via Red Hat JBoss A­MQ. Visit frequently to view more tutorials on connecting via MQTT, STOMP and other topics around A­MQ.
