:awestruct-layout: product-overview
:leveloffset: 1

== Overview

JBoss A-MQ is a high performance, flexible messaging platform that delivers information safely, reliably and enables Internet of Things (IoT). JBoss A-MQ can be deployed, and easily managed, in any configuration so you can deploy a network of brokers across your infrastructure whether they are on premise, in the Cloud, or in a hybrid configuration.


== Features1

=== High performance messaging

A reliable messaging platform that supports standard messaging paradigms for a real-time enterprise.

== Icon1

[.fa .fa-comments .fa-5x .fa-fw]#&nbsp;#


== Features2

=== Cross-language and multi-protocol support

Allows native connectivity from applications written in Java, C, C++. Multiple transport protocols for exchanging data between applications, services and devices. Supports JMS 1.1, TCP, SSL, STOMP, NMS, MQTT, AMQP 1.0.

== Icon2
[.fa .fa-arrows-alt .fa-5x .fa-fw]#&nbsp;#


== Features3

=== Cloud ready

Deploy on premise, in the cloud or in a hybrid conﬁguration.

== Icon3

[.fa .fa-cloud .fa-5x .fa-fw]#&nbsp;#

== Detail

Core messaging is provided by Apache ActiveMQ supporting different messaging paradigms like publish-subscribe, point-to-point, store-and-forward. Multi-protocol support (JMS 1.1, TCP, SSL, STOMP, NMS) and multi-client support (Java, C, C++) enables real-time messaging with all enterprise assets. In addition JBoss A-MQ is hosted on a lightweight OSGI-based runtime container, Apache Karaf. Fuse IDE is available along with JBDS to provide an easy-to-use integration development environment.

We encourage you to download JBoss A-MQ, and see for yourself if it meets your needs.


== Resources

- https://www.jboss.org/products/amq/fusebyexample.html[FuseByExample] is a set of demos created by JBoss Fuse and JBoss A-MQ consultants based on their experience with customers.

- Check out JBoss A-MQ in https://engage.redhat.com/integration-middleware-fuse-s-201404231024[The Forrester Wave: Hybrid integration, 2014]
