:awestruct-layout: product-overview

== Overview

JBoss A-MQ is a high performance, flexible, cost-effective messaging platform that delivers information safely and reliably with a small footprint. JBoss A-MQ can be deployed, and easily managed, in any configuration so you can deploy a network of brokers across your infrastructure whether they are on premise, in the Cloud, or in a hybrid configuration.

Core messaging is provided by Apache ActiveMQ supporting different messaging paradigms like publish-subscribe, point-to-point, store-and-forward. Multi-protocol support (JMS 1.1, TCP, SSL, STOMP, NMS) and multi-client support (Java, C, C++) enables real-time messaging with all enterprise assets. In addition JBoss A-MQ is hosted on a lightweight OSGI-based runtime container, Apache Karaf. Fuse IDE is available along with JBDS to provide an easy-to-use integration development environment.

We encourage you to download JBoss A-MQ, and see for yourself if it meets your needs. 

== Resources

- https://www.jboss.org/products/amq/fusebyexample.html[FuseByExample] is a set of demos created by JBoss Fuse and JBoss A-MQ consultants based on their experience with customers.

== Articles

http://www.ossmentor.com/2014/02/devnation-by-and-for-developers.html[DevNation - By and For Developers]::
  AN OPEN SOURCE CONFERENCE, BY AND FOR DEVELOPERS ACROSS THE GLOBE April 13 - 16, 2014 | San Francisco, CA | USA...

http://www.ossmentor.com/2014/02/red-hat-summit-2014-agenda.html[Red Hat Summit 2014 Agenda]::
  In technology, and in life, we are always moving forward. There is no time to stand still. We must constantly evolve.   From a hobbyist's dream to a foundation for the modern enterprise — our...

http://www.ossmentor.com/2014/02/fuse-service-works-v6-is-ga.html[Fuse Service Works v6 is GA!]::
  We are very happy to announce the general availability of JBoss Fuse Service Works (FSW) v6.  It is documented and available for download on the customer support portal [1] [2] in all regions and for all channels...