name: Red Hat Development Suite
abbreviated_name: Red Hat Development Suite
product_logo: enterprise-app-platform.png
current_version: 1.1.0
documentation_path: red-hat-jboss-enterprise-application-platform
product_category: application-development
youtube_album: https://www.youtube.com/playlist?list=PLf3vm0UK6HKpAr_6VUi6nkoSQDov8fuZg
ignore_forums: true
index:
  desc: |
    A fully integrated development environment for modern enterprise development.
description: 'A fully integrated development environment for modern enterprise development.'
guides:
  Release_Notes_and_Known_Issues:
    formats:
      html:
        url: https://access.redhat.com/documentation/en/red-hat-development-suite/1.1/paged/release-notes-and-known-issues/
      html-single:
        url: https://access.redhat.com/documentation/en/red-hat-development-suite/1.1/single/release-notes-and-known-issues/
      pdf:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_Development_Suite-1.1-Release_Notes_and_Known_Issues-en-US/Red_Hat_Development_Suite-1.1-Release_Notes_and_Known_Issues-en-US.pdf
      epub:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_Development_Suite-1.1-Release_Notes_and_Known_Issues-en-US/Red_Hat_Development_Suite-1.1-Release_Notes_and_Known_Issues-en-US.epub
  Installation_Guide:
    formats:
      html:
        url: https://access.redhat.com/documentation/en/red-hat-development-suite/1.1/paged/installation-guide/
      html-single:
        url: https://access.redhat.com/documentation/en/red-hat-development-suite/1.1/single/installation-guide/
      pdf:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_Development_Suite-1.1-Installation_Guide-en-US/Red_Hat_Development_Suite-1.1-Installation_Guide-en-US.pdf
      epub:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_Development_Suite-1.1-Installation_Guide-en-US/Red_Hat_Development_Suite-1.1-Installation_Guide-en-US.epub
  Getting_Started_Guide:
    formats:
      html:
        url: https://access.redhat.com/documentation/en/red-hat-container-development-kit/2.2/paged/getting-started-guide/
      html-single:
        url: https://access.redhat.com/documentation/en/red-hat-container-development-kit/2.2/single/getting-started-guide/
      pdf:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_Container_Development_Kit-2.2-Getting_Started_Guide-en-US/Red_Hat_Container_Development_Kit-2.2-Getting_Started_Guide-en-US.pdf
      epub:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_Container_Development_Kit-2.2-Getting_Started_Guide-en-US/Red_Hat_Container_Development_Kit-2.2-Getting_Started_Guide-en-US.epub

