:awestruct-layout: product-overview

== Overview

JBoss Fuse is an open source Enterprise Service Bus (ESB) with an elastic footprint that supports integration beyond the data center. The lack of license fees and the ability to deploy JBoss Fuse in several different configurations advances intelligent integration to all facets of your business – on premise or in the Cloud.

JBoss Fuse combines core Enterprise Service Bus capabilities (based on Apache Camel, Apache CXF, Apache ActiveMQ), Apache Karaf and Fuse Fabric in a single integrated distribution.

image::/images/products/fuse/esbtofuse[]

Core messaging is provided by Apache ActiveMQ, services framework (SOAP, XML/HTTP, RESTful HTTP) is provided by Apache CXF and integration framework is provided by Apache Camel. Apache Karaf provides a lightweight OSGI-based runtime container. Fuse IDE is available along with JBDS to provide an easy-to-use integration development environment.

We encourage you to download JBoss Fuse, and see for yourself if it meets your needs. 

== Resources

- https://www.jboss.org/products/fuse/fusebyexample.html[FuseByExample] is a set of examples created by Fuse consultants based on their experience with customers.

