:awestruct-layout: solution-adoption
:awestruct-interpolate: true
:page-drupal_type: rhd_solution_overview

Your web applications are not just Java - at a minimum they also have HTML, CSS, and JavaScript.  And for some ideas, Ruby, Python, or Node may be a better approach.  How do you allow the right tool for the right problem while still maintaining application and environment integrity along with an environment that is supportable?

Taking that polyglot to the next step, how do you create, orchestrate, and publish an API that is language agnostic so your product community can build on the great work you did?

Keep reading to get some ideas on how Red Hat Web & API products can help with these challenges and more.

[discrete]
[[languages]]
==== Java
A high-level multipurpose language well suited for the web.  Java and link:http://openjdk.java.net/[OpenJDK] are integral parts of the RHEL platform.  Download yourself a copy of link:#{site.base_url}/products/devstudio[JBoss Developer Studio], pick a server and start building your application today.

Also available is link:http://icedtea.classpath.org/wiki/Thermostat[Thermostat], an instrumentation tool for the Hotspot JVM, with support for monitoring multiple JVM instances on multiple hosts, optionally in a cloud environment.

|=====
| *Language* | *Channel*
| Java 1.6 | java-1.6.0-openjdk
| Java 1.7 | java-1.7.0-openjdk
| Java 1.8 | java-1.8.0-openjdk
| Maven 3.0.5 | maven30
| link:https://rhn.redhat.com/errata/RHEA-2015-0883.html[Common Java Packages 1.1] | rh-java-common
| Thermostat | thermostat1-thermostat
|=====



[discrete]
===== Web Servers and frameworks

. Get the tools
  .. link:#{site.base_url}/products/devstudio/get-started[Get Started] with JBoss Developer Studio..
. Choose an application or web server
  * link:#{site.base_url}/products/eap/download/[Download] *JBoss EAP* or launch EAP on link:https://hub.openshift.com/quickstarts/95-jboss-eap-6-4[OpenShift]
  * *Apache Tomcat* is part of link:#{site.base_url}/products/webserver/download/[JBoss Web Server] and is also available on link:https://hub.openshift.com/quickstarts/96-tomcat-7-jboss-ews-2-0[OpenShift]
. link:#{site.base_url}/products/eap/learn/#!project=eap&randomize=true[Check out] one of the many quickstarts, tutorials and demos availble.
. Learn how to manage dependencies with link:#{site.base_url}/web-and-api-development/learn/#!query=maven[Maven]

// * Using Angular and RESTFul services link:#{site.base_url}/web-and-api-development/learn/#!sys_type=quickstart&query=Angular[Get Started]


''''

[discrete]
===== Perl
_Want a Dancer applicaiton backed by MySQL?  Or maybe you're looking for Mojolicious and MongoDB?_  Perl is a high-level, general purpose dynamic language.  With link:#{site.base_url}/products/softwarecollections[Software Collections] and link:#{site.base_url}/products/openshift[OpenShift] you can easily deploy and run Perl applications using your favorite frameworks and databases.

|=====
| *Language* | *Channel*
| Perl 5.10 | link:https://hub.openshift.com/quickstarts/100-perl-5-10[Launch Perl on OpenShift]
| Perl 5.16.3 |	perl516
| Perl 5.20.1	| rh-perl520
|=====

''''

[discrete]
===== PHP
PHP is a general-purpose server-side scripting language originally designed for Web development to produce dynamic Web pages. Popular development frameworks include CakePHP, Zend, Symfony, and CodeIgniter.

|=====
| *Language* | *Channel*
| PHP 5.4 | php54 +
link:https://hub.openshift.com/quickstarts/101-php-5-4[Launch PHP 5.4 on OpenShift]
| PHP 5.5 | php55
| PHP 5.6 | rh-php56
| Perl 5.20.1	| rh-perl520
|=====

''''

[discrete]
===== Python
Another general-purpose, high-level programming language, Python differentiates itself with a design philosophy that emphasizes code readability. Popular development frameworks include: Django, Bottle, Pylons, Zope and TurboGears.

|=====
| *Language* | *Channel*
| Python 2.7.8 | python 27
| Python 3.3.2 | python 33 +
link:https://hub.openshift.com/quickstarts/103-python-3-3[Launch Python 3.3 on OpenShift]
| Python 3.4.2 | rh-python 34
|=====

''''

[discrete]
===== Ruby
Ruby, the dynamic, reflective, general-purpose object-oriented programming language and its popular development framework Ruby on Rails is supported by Red Hat.

|=====
| *Language* | *Channel*
| Ruby 1.9.3 | ruby19
| Ruby 2.0.0 | ruby200 +
link:https://hub.openshift.com/quickstarts/106-ruby-2-0[Launch Ruby on OpenShift]
| Ruby 2.2.2 | rh-ruby22
| Ruby on Rails 4.0.2 | ror40 +
link:https://hub.openshift.com/quickstarts/76-ruby-on-rails-4[Launch Ruby on Rails on OpenShift]
| Ruby on Rails 4.1.5 | rh-ror41
|=====


''''

[discrete]
[[apis]]
=== Integration and API
Whether you are publishing services or consuming someone else's APIs integration can be tricky.  Take a look at using link:#{site.base_url}/products/fuse[Fuse], link:#{site.base_url}/products/amq[A-MQ] and link:#{site.base_url}/products/datavirt[Data Virtualization] to make the job that much easier.

[discrete]
===== REST
Representational State Transfer (REST) works well with a API-centric web applications. RESTEasy makes it simple to expose your services via JAX-RS.


* link:#{site.base_url}/web-and-api-development/learn/#!query=REST[Get started] exposing a RESTFul API.

[discrete]
===== Fuse
Fuse is a small footprint enterprise service bus (ESB) that lets you build, deploy and integrate applications and services.

* link:#{site.base_url}/products/fuse/get-started[Get Started] with Fuse.
* link:#{site.base_url}/products/fuse/learn[Learn] more about integrating with Fuse.
* Check out a series of examples on link:https://github.com/FuseByExample[GitHub]
* link:https://hub.openshift.com/quickstarts/40-jboss-fuse-6-1[Launch] fuse on OpenShift

[discrete]
===== Data Virtualization
Need to expose your data as a service?  JBoss Data Virtualization makes it simple whether you have a single data source or many.

* Creating data services link:#{site.base_url}/products/datavirt/learn[Get Started]

[discrete]
===== A-MQ
A-MQ gives you a high performance, cross-platform multi-language messaging system that can be deployed across your infrastructure.

* link:#{site.base_url}/products/amq/learn[Get started] using A-MQ




////
[discrete]
=== Choose a platform

* Getting started with link:#{site.base_url}/products/eap[JBoss EAP]
  * Try a simple link:#{site.base_url}/quickstarts/eap/helloworld/index.html[Hello World]
  * or link:https://hub.openshift.com/quickstarts/deploy/95-jboss-eap-6-4[launch EAP on OpenShift]
* Using Apache HTTP Server or Apache Tomcat
  * with link:#{site.base_url}/products/webserver[JBoss Web Server] link:simple[Get Started]
  * launch today on OpenShift link:https://hub.openshift.com/quickstarts/deploy/96-tomcat-7-jboss-ews-2-0[Get Started]
  * install and use modern versions of Apache HTTP and Tomcat with Software Collections link:##[Get Started]
'''


'''

[discrete]
=== Integration and API

* Getting Started with Fuse link:#[Get Started]
  * link:https://github.com/FuseByExample/HelloCamel[Hello Camel]
* Exposing a RESTFul API link:#[Get Started]
* Creating data services link:#[Get Started]

'''
////
