source "https://rubygems.org"

gem 'docker-api', :require => 'docker'

group :test do
  gem 'mocha'
  # Useful for running the tests on the commandline, and technically they are required
  gem 'minitest'
  gem 'minitest-reporters'
  gem 'nokogiri'
end
