source "https://rubygems.org"

gem 'gpgme'
gem 'docker-api', :require => 'docker'
gem 'typhoeus'
gem 'akamai-edgegrid', '1.0.6'

group :test do
  gem 'mocha'
  # Useful for running the tests on the commandline, and technically they are required
  gem 'minitest'
  gem 'minitest-reporters'
  gem 'nokogiri'
  gem 'webmock'
end
