= Docker integration
Jason Porter jporter@redhat.com
2015-07-08

== Current status

I have drupal up and running and awestruct pushing pages into drupal. This is also all loaded up into docker images using a combination of docker-compose and our own orchestration script (`control.rb`), further information about getting started with all of that can be had in the README document.

== Next steps

=== Drupal in docker

Currently drupal is setup each time the docker image is stared via the `run.sh` script in `../_drupal/scripts/run.sh`. All, or at least the majority of this script should be put into the Dockerfile so the developer does not incur this penalty each time.

I believe the biggest hurdle for this is the database settings for drupal. I have found some good information about using environment variables at https://bryce.fisher-fleig.org/blog/settings-php-hack-keep-credentials-out-of-your-code/. I believe if we use the current environment variables set by docker we should be able to keep a drupal settings file under version control and add that to the final install. Another option is to look at creating our own drupal distribution. I believe the customer portal team is doing this, but I was not able to figure out how to properly make this work. Ben has all the info on that.

=== docker image tagging and reuse

We need a place to host our docker images, somewhere the rest of the world will not be able to pull them down. Maybe that isn't a concern now that everything is public, I'm not sure. If we're based on CentOS for everything then it probably doesn't matter either. If we can tag an image and have it include things like database changes we'll be much closer to having a better development environment for people, but this is probably just a nice to have. We also need to reuse these tagged images in the `control.rb` script.

=== Drupal push improvements

We need to look further into what the other teams have done with the documentation push and reuse some of the code and infrastructure.
