:awestruct-layout: product-overview

== Overview
JBoss A-MQ is a high performance, flexible, cost-effective messaging platform that delivers information safely and reliably with a small footprint. JBoss A-MQ can be deployed, and easily managed, in any configuration so you can deploy a network of brokers across your infrastructure whether they are on premise, in the Cloud, or in a hybrid configuration.

Core messaging is provided by Apache ActiveMQ supporting different messaging paradigms like publish-subscribe, point-to-point, store-and-forward. Multi-protocol support (JMS 1.1, TCP, SSL, STOMP, NMS) and multi-client support (Java, C, C++) enables real-time messaging with all enterprise assets. In addition JBoss A-MQ is hosted on a lightweight OSGI-based runtime container, Apache Karaf. Fuse IDE is available along with JBDS to provide an easy-to-use integration development environment.

We encourage to download JBoss A-MQ, and see for yourself if it meets your needs. 

== Resources

- https://access.redhat.com/knowledge/docs/JBoss_A-MQ/[JBoss A-MQ 6.0 Documentation]
- Discuss on JBoss https://community.jboss.org/en/jbosseap[EAP Forums]
- https://www.jboss.org/products/amq/fusebyexample.html[FuseByExample] is a set of demos created by Fuse and A-MQ consultants based on their experience with customers.

